#!/usr/bin/env bash
# Cursor Cloud `start` — per-boot. Local infra via bun dw setup.
# Infisical: persist Cursor's INFISICAL_TOKEN (Token Auth) into env.sh / cache.
# No `infisical login`. Does not wrap node_modules/.bin/infisical.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
cd "$ROOT"
export PATH="$ROOT/node_modules/.bin:/usr/local/bin:$HOME/.bun/bin:$PATH"

export CLOUD_AGENT=1
# ai-sync still copies skills when DW_HEADLESS=1; keep until that CLI reads CLOUD_AGENT.
export DW_HEADLESS=1
append_once() {
	local file="$1"
	local line="$2"
	touch "$file"
	grep -qxF "$line" "$file" 2>/dev/null || echo "$line" >>"$file"
}

append_once "${HOME}/.bashrc" 'export CLOUD_AGENT=1'
append_once "${HOME}/.bashrc" 'export DW_HEADLESS=1'

env_sh="${HOME}/.autumn-agent/env.sh"
mkdir -p "${HOME}/.autumn-agent"

# Token Auth access token from Cursor. Persist so later shells that miss
# Runtime Secrets can still `infisical run`. No universal-auth login.
if [ -n "${INFISICAL_TOKEN:-}" ]; then
	mkdir -p "${HOME}/.cache"
	printf '%s' "$INFISICAL_TOKEN" > "${HOME}/.cache/autumn-infisical-token"
	chmod 600 "${HOME}/.cache/autumn-infisical-token"
	echo "[cursor-cloud-start] Infisical token ready"
else
	echo "[cursor-cloud-start] INFISICAL_TOKEN unset — set it as a Team Runtime Secret"
	echo "[cursor-cloud-start] (machine identity → Token Auth → Create Token)."
	echo "[cursor-cloud-start] Repo .cursor/environment.json wins over the team env — Team-scoped secrets, not Environment."
fi

cat > "$env_sh" <<ENVSH
# Generated by scripts/setup/cursor-cloud/start.sh — sourced from bashrc / BASH_ENV / zshenv.
export CLOUD_AGENT=1
export DW_HEADLESS=1
export PATH="${ROOT}/node_modules/.bin:/usr/local/bin:\$HOME/.bun/bin:\$PATH"
if [ -z "\${INFISICAL_TOKEN:-}" ] && [ -s "\${HOME}/.cache/autumn-infisical-token" ]; then
  INFISICAL_TOKEN="\$(cat "\${HOME}/.cache/autumn-infisical-token")"
  export INFISICAL_TOKEN
fi
if [ -z "\${INFISICAL_PROJECT_ID:-}" ] && [ -f "${ROOT}/.infisical.json" ]; then
  INFISICAL_PROJECT_ID="\$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("workspaceId") or "")' "${ROOT}/.infisical.json" 2>/dev/null || true)"
  [ -n "\$INFISICAL_PROJECT_ID" ] && export INFISICAL_PROJECT_ID
fi
ENVSH
chmod 600 "$env_sh"

append_once "${HOME}/.bashrc" ". ${env_sh}"
append_once "${HOME}/.bashrc" "export BASH_ENV=${env_sh}"
append_once "${HOME}/.profile" ". ${env_sh}"
if [ -n "${ZDOTDIR:-}" ]; then
	append_once "${ZDOTDIR}/.zshenv" ". ${env_sh}"
else
	append_once "${HOME}/.zshenv" ". ${env_sh}"
fi
export BASH_ENV="$env_sh"
# Current start process (and anything it execs) should see Infisical too.
# shellcheck disable=SC1090
. "$env_sh"

BUN="${HOME}/.bun/bin/bun"
if [ ! -x "$BUN" ]; then
	BUN="$(command -v bun || true)"
fi

# Skills first. Infisical + bun dw setup can take minutes; the chat catalog
# will not refresh after this process later writes ~/.cursor/skills.
if [ -f ai/package.json ] && [ -n "$BUN" ]; then
	if [ ! -f "${HOME}/.cursor/skills/tdd/SKILL.md" ]; then
		echo "[cursor-cloud-start] ~/.cursor/skills missing — running bun ai sync --copy"
		"$BUN" ai/src/cli.ts sync --copy || echo "[cursor-cloud-start] bun ai sync failed (skills may be missing)"
	fi
	"$BUN" "$ROOT/scripts/setup/cursor-cloud/cursorCloud.ts" mark-skills || true
	"$BUN" "$ROOT/scripts/setup/cursor-cloud/cursorCloud.ts" agents-md || true
fi

infisical_printenv() {
	local key="$1"
	local pulled st
	if [ -n "${!key:-}" ]; then
		return 0
	fi
	command -v infisical >/dev/null 2>&1 || return 0
	set +e
	pulled="$(infisical run --env=dev --recursive --silent -- printenv "$key" 2>/dev/null)"
	st=$?
	set -e
	if [ "$st" -eq 0 ]; then
		pulled="${pulled%%$'\n'*}"
		if [ -n "$pulled" ]; then
			export "$key=$pulled"
		fi
	fi
}

persist_export() {
	local key="$1"
	[ -n "${!key:-}" ] || return 0
	grep -v "^export ${key}=" "$env_sh" >"${env_sh}.tmp" || true
	mv "${env_sh}.tmp" "$env_sh"
	printf 'export %s=%q\n' "$key" "${!key}" >>"$env_sh"
	chmod 600 "$env_sh"
}

infisical_printenv EXECUTOR_API_KEY
persist_export EXECUTOR_API_KEY
if [ -n "$BUN" ]; then
	"$BUN" "$ROOT/scripts/setup/cursor-cloud/cursorCloud.ts" mcp || \
		echo "[cursor-cloud-start] executor MCP configure failed (non-fatal)"
fi

# Cloudflare tunnel: Infisical `dev`. Never log the values.
infisical_printenv CLOUDFLARE_TUNNEL_API_TOKEN
infisical_printenv CLOUDFLARE_TUNNEL_ACCOUNT_ID
if [ -z "${CLOUDFLARE_TUNNEL_API_TOKEN:-}" ]; then
	infisical_printenv CLOUDFLARE_API_TOKEN
	if [ -n "${CLOUDFLARE_API_TOKEN:-}" ]; then
		export CLOUDFLARE_TUNNEL_API_TOKEN="$CLOUDFLARE_API_TOKEN"
	fi
fi
if [ -z "${CLOUDFLARE_TUNNEL_ACCOUNT_ID:-}" ]; then
	infisical_printenv CLOUDFLARE_ACCOUNT_ID
	if [ -n "${CLOUDFLARE_ACCOUNT_ID:-}" ]; then
		export CLOUDFLARE_TUNNEL_ACCOUNT_ID="$CLOUDFLARE_ACCOUNT_ID"
	fi
fi
persist_export CLOUDFLARE_TUNNEL_API_TOKEN
persist_export CLOUDFLARE_TUNNEL_ACCOUNT_ID
if [ -n "${CLOUDFLARE_TUNNEL_API_TOKEN:-}" ]; then
	umask 077
	{
		printf 'CLOUDFLARE_TUNNEL_API_TOKEN=%s\n' "$CLOUDFLARE_TUNNEL_API_TOKEN"
		if [ -n "${CLOUDFLARE_TUNNEL_ACCOUNT_ID:-}" ]; then
			printf 'CLOUDFLARE_TUNNEL_ACCOUNT_ID=%s\n' "$CLOUDFLARE_TUNNEL_ACCOUNT_ID"
		fi
	} >"${HOME}/.autumn-agent/cloudflare.env"
	chmod 600 "${HOME}/.autumn-agent/cloudflare.env"
	echo "[cursor-cloud-start] CLOUDFLARE_TUNNEL_API_TOKEN ready (len=${#CLOUDFLARE_TUNNEL_API_TOKEN})"
else
	echo "[cursor-cloud-start] CLOUDFLARE_TUNNEL_API_TOKEN unset — bun dw setup cannot create public hosts"
fi
# shellcheck disable=SC1090
. "$env_sh"

# Infra + Cloudflare public hosts. Does not start the app.
if [ -n "$BUN" ]; then
	echo "[cursor-cloud-start] bun dw setup (local infra + public URL)"
	"$BUN" dw setup || echo "[cursor-cloud-start] bun dw setup failed (non-fatal)"
fi
