
services:
  valkey:
    image: docker.io/valkey/valkey:8.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - valkey-data:/bitnami/valkey/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-h', 'localhost', '-p', '6379', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    restart: unless-stopped
    
  vite:
    build:
      context: .
      dockerfile: docker/prod.dockerfile
      target: vite-prod
    ports:
      - "3000:3000"
    restart: always

  server:
    environment:
      - REDIS_URL=redis://valkey:6379
    build:
      context: .
      dockerfile: docker/prod.dockerfile
      target: server-prod
    ports:
      - "8080:8080"
    restart: always

  localtunnel:
    image: oven/bun:latest
    build:
      dockerfile: docker/prod.dockerfile
      context: .
      target: localtunnel
    volumes:
      - ./server:/app/server
    depends_on:
      - server
    restart: unless-stopped

  workers:
    environment:  
      - REDIS_URL=redis://valkey:6379
    build:
      context: .
      dockerfile: docker/prod.dockerfile
      target: workers-prod
    restart: always

volumes:
  valkey-data:
  shared-dist:
  shared-node-modules:
  root-node-modules: