// Every customer tax ID type Stripe accepts, with the country it belongs to and
// a human label for pickers. One row per (country, type): a country with several
// registrations appears several times. Source: https://docs.stripe.com/billing/customer/tax-ids
// Kept in sync by hand, like stripeCurrencies.ts. `type` is checked against the SDK
// union, so a type the pinned SDK cannot send is left out until the SDK is bumped.

import type Stripe from "stripe";

export type StripeTaxIdType = Stripe.TaxId.Type;

export type StripeTaxIdOption = {
	/** Stable key for pickers; a type like eu_vat repeats across countries. */
	id: string;
	type: StripeTaxIdType;
	/** ISO 3166-1 alpha-2, or "EU" for the One Stop Shop scheme. */
	countryCode: string;
	country: string;
	flag: string;
	/** What the registration is called, without the country repeated. */
	label: string;
	example: string;
};

export const STRIPE_TAX_ID_OPTIONS: StripeTaxIdOption[] = [
	{
		id: "AD:ad_nrt",
		type: "ad_nrt",
		countryCode: "AD",
		country: "Andorra",
		flag: "🇦🇩",
		label: "NRT number",
		example: "A-123456-Z",
	},
	{
		id: "AE:ae_trn",
		type: "ae_trn",
		countryCode: "AE",
		country: "United Arab Emirates",
		flag: "🇦🇪",
		label: "TRN",
		example: "123456789012345",
	},
	{
		id: "AL:al_tin",
		type: "al_tin",
		countryCode: "AL",
		country: "Albania",
		flag: "🇦🇱",
		label: "Tax Identification Number",
		example: "J12345678N",
	},
	{
		id: "AM:am_tin",
		type: "am_tin",
		countryCode: "AM",
		country: "Armenia",
		flag: "🇦🇲",
		label: "Tax Identification Number",
		example: "02538904",
	},
	{
		id: "AO:ao_tin",
		type: "ao_tin",
		countryCode: "AO",
		country: "Angola",
		flag: "🇦🇴",
		label: "Tax Identification Number",
		example: "5123456789",
	},
	{
		id: "AR:ar_cuit",
		type: "ar_cuit",
		countryCode: "AR",
		country: "Argentina",
		flag: "🇦🇷",
		label: "Tax ID number",
		example: "12-3456789-01",
	},
	{
		id: "AT:eu_vat",
		type: "eu_vat",
		countryCode: "AT",
		country: "Austria",
		flag: "🇦🇹",
		label: "VAT number",
		example: "ATU12345678",
	},
	{
		id: "AU:au_abn",
		type: "au_abn",
		countryCode: "AU",
		country: "Australia",
		flag: "🇦🇺",
		label: "Business Number (AU ABN)",
		example: "12345678912",
	},
	{
		id: "AU:au_arn",
		type: "au_arn",
		countryCode: "AU",
		country: "Australia",
		flag: "🇦🇺",
		label: "Taxation Office Reference Number",
		example: "123456789123",
	},
	{
		id: "AW:aw_tin",
		type: "aw_tin",
		countryCode: "AW",
		country: "Aruba",
		flag: "🇦🇼",
		label: "Tax Identification Number",
		example: "12345678",
	},
	{
		id: "AZ:az_tin",
		type: "az_tin",
		countryCode: "AZ",
		country: "Azerbaijan",
		flag: "🇦🇿",
		label: "Tax Identification Number",
		example: "0123456789",
	},
	{
		id: "BA:ba_tin",
		type: "ba_tin",
		countryCode: "BA",
		country: "Bosnia and Herzegovina",
		flag: "🇧🇦",
		label: "Tax Identification Number",
		example: "123456789012",
	},
	{
		id: "BB:bb_tin",
		type: "bb_tin",
		countryCode: "BB",
		country: "Barbados",
		flag: "🇧🇧",
		label: "Tax Identification Number",
		example: "1123456789012",
	},
	{
		id: "BD:bd_bin",
		type: "bd_bin",
		countryCode: "BD",
		country: "Bangladesh",
		flag: "🇧🇩",
		label: "Business Identification Number",
		example: "123456789-0123",
	},
	{
		id: "BE:eu_vat",
		type: "eu_vat",
		countryCode: "BE",
		country: "Belgium",
		flag: "🇧🇪",
		label: "VAT number",
		example: "BE0123456789",
	},
	{
		id: "BF:bf_ifu",
		type: "bf_ifu",
		countryCode: "BF",
		country: "Burkina Faso",
		flag: "🇧🇫",
		label: "Tax Identification Number",
		example: "12345678A",
	},
	{
		id: "BG:bg_uic",
		type: "bg_uic",
		countryCode: "BG",
		country: "Bulgaria",
		flag: "🇧🇬",
		label: "Unified Identification Code",
		example: "123456789",
	},
	{
		id: "BG:eu_vat",
		type: "eu_vat",
		countryCode: "BG",
		country: "Bulgaria",
		flag: "🇧🇬",
		label: "VAT number",
		example: "BG0123456789",
	},
	{
		id: "BH:bh_vat",
		type: "bh_vat",
		countryCode: "BH",
		country: "Bahrain",
		flag: "🇧🇭",
		label: "VAT Number",
		example: "123456789012345",
	},
	{
		id: "BJ:bj_ifu",
		type: "bj_ifu",
		countryCode: "BJ",
		country: "Benin",
		flag: "🇧🇯",
		label: "Tax Identification Number",
		example: "1234567890123",
	},
	{
		id: "BO:bo_tin",
		type: "bo_tin",
		countryCode: "BO",
		country: "Bolivia",
		flag: "🇧🇴",
		label: "Tax ID",
		example: "123456789",
	},
	{
		id: "BR:br_cnpj",
		type: "br_cnpj",
		countryCode: "BR",
		country: "Brazil",
		flag: "🇧🇷",
		label: "CNPJ number",
		example: "01.234.456/5432-10",
	},
	{
		id: "BR:br_cpf",
		type: "br_cpf",
		countryCode: "BR",
		country: "Brazil",
		flag: "🇧🇷",
		label: "CPF number",
		example: "123.456.789-87",
	},
	{
		id: "BS:bs_tin",
		type: "bs_tin",
		countryCode: "BS",
		country: "Bahamas",
		flag: "🇧🇸",
		label: "Tax Identification Number",
		example: "123.456.789",
	},
	{
		id: "BY:by_tin",
		type: "by_tin",
		countryCode: "BY",
		country: "Belarus",
		flag: "🇧🇾",
		label: "TIN Number",
		example: "123456789",
	},
	{
		id: "CA:ca_bn",
		type: "ca_bn",
		countryCode: "CA",
		country: "Canada",
		flag: "🇨🇦",
		label: "BN",
		example: "123456789",
	},
	{
		id: "CA:ca_gst_hst",
		type: "ca_gst_hst",
		countryCode: "CA",
		country: "Canada",
		flag: "🇨🇦",
		label: "GST/HST number",
		example: "123456789RT0002",
	},
	{
		id: "CA:ca_pst_bc",
		type: "ca_pst_bc",
		countryCode: "CA",
		country: "Canada",
		flag: "🇨🇦",
		label: "PST number (British Columbia)",
		example: "PST-1234-5678",
	},
	{
		id: "CA:ca_pst_mb",
		type: "ca_pst_mb",
		countryCode: "CA",
		country: "Canada",
		flag: "🇨🇦",
		label: "PST number (Manitoba)",
		example: "123456-7",
	},
	{
		id: "CA:ca_pst_sk",
		type: "ca_pst_sk",
		countryCode: "CA",
		country: "Canada",
		flag: "🇨🇦",
		label: "PST number (Saskatchewan)",
		example: "1234567",
	},
	{
		id: "CA:ca_qst",
		type: "ca_qst",
		countryCode: "CA",
		country: "Canada",
		flag: "🇨🇦",
		label: "QST number (Québec)",
		example: "1234567890TQ1234",
	},
	{
		id: "CD:cd_nif",
		type: "cd_nif",
		countryCode: "CD",
		country: "Congo (DR)",
		flag: "🇨🇩",
		label: "Tax Identification Number",
		example: "A0123456M",
	},
	{
		id: "CH:ch_uid",
		type: "ch_uid",
		countryCode: "CH",
		country: "Switzerland",
		flag: "🇨🇭",
		label: "UID number",
		example: "CHE-123.456.789 HR",
	},
	{
		id: "CH:ch_vat",
		type: "ch_vat",
		countryCode: "CH",
		country: "Switzerland",
		flag: "🇨🇭",
		label: "VAT number",
		example: "CHE-123.456.789 MWST",
	},
	{
		id: "CL:cl_tin",
		type: "cl_tin",
		countryCode: "CL",
		country: "Chile",
		flag: "🇨🇱",
		label: "TIN",
		example: "12.345.678-K",
	},
	{
		id: "CM:cm_niu",
		type: "cm_niu",
		countryCode: "CM",
		country: "Cameroon",
		flag: "🇨🇲",
		label: "Tax Identification Number",
		example: "M123456789000L",
	},
	{
		id: "CN:cn_tin",
		type: "cn_tin",
		countryCode: "CN",
		country: "China",
		flag: "🇨🇳",
		label: "Tax ID",
		example: "123456789012345678",
	},
	{
		id: "CO:co_nit",
		type: "co_nit",
		countryCode: "CO",
		country: "Colombia",
		flag: "🇨🇴",
		label: "NIT number",
		example: "123.456.789-0",
	},
	{
		id: "CR:cr_tin",
		type: "cr_tin",
		countryCode: "CR",
		country: "Costa Rica",
		flag: "🇨🇷",
		label: "Tax ID",
		example: "1-234-567890",
	},
	{
		id: "CV:cv_nif",
		type: "cv_nif",
		countryCode: "CV",
		country: "Cape Verde",
		flag: "🇨🇻",
		label: "Tax Identification Number",
		example: "213456789",
	},
	{
		id: "CY:eu_vat",
		type: "eu_vat",
		countryCode: "CY",
		country: "Cyprus",
		flag: "🇨🇾",
		label: "VAT number",
		example: "CY12345678Z",
	},
	{
		id: "CZ:eu_vat",
		type: "eu_vat",
		countryCode: "CZ",
		country: "Czechia",
		flag: "🇨🇿",
		label: "VAT number",
		example: "CZ1234567890",
	},
	{
		id: "DE:de_stn",
		type: "de_stn",
		countryCode: "DE",
		country: "Germany",
		flag: "🇩🇪",
		label: "Tax Number (Steuernummer)",
		example: "1234567890",
	},
	{
		id: "DE:eu_vat",
		type: "eu_vat",
		countryCode: "DE",
		country: "Germany",
		flag: "🇩🇪",
		label: "VAT number",
		example: "DE123456789",
	},
	{
		id: "DK:eu_vat",
		type: "eu_vat",
		countryCode: "DK",
		country: "Denmark",
		flag: "🇩🇰",
		label: "VAT number",
		example: "DK12345678",
	},
	{
		id: "DO:do_rcn",
		type: "do_rcn",
		countryCode: "DO",
		country: "Dominican Republic",
		flag: "🇩🇴",
		label: "RCN number",
		example: "123-4567890-1",
	},
	{
		id: "EC:ec_ruc",
		type: "ec_ruc",
		countryCode: "EC",
		country: "Ecuador",
		flag: "🇪🇨",
		label: "RUC number",
		example: "1234567890001",
	},
	{
		id: "EE:eu_vat",
		type: "eu_vat",
		countryCode: "EE",
		country: "Estonia",
		flag: "🇪🇪",
		label: "VAT number",
		example: "EE123456789",
	},
	{
		id: "EG:eg_tin",
		type: "eg_tin",
		countryCode: "EG",
		country: "Egypt",
		flag: "🇪🇬",
		label: "Tax Identification Number",
		example: "123456789",
	},
	{
		id: "ES:es_cif",
		type: "es_cif",
		countryCode: "ES",
		country: "Spain",
		flag: "🇪🇸",
		label: "NIF number",
		example: "A12345678",
	},
	{
		id: "ES:eu_vat",
		type: "eu_vat",
		countryCode: "ES",
		country: "Spain",
		flag: "🇪🇸",
		label: "VAT number",
		example: "ESA1234567Z",
	},
	{
		id: "ET:et_tin",
		type: "et_tin",
		countryCode: "ET",
		country: "Ethiopia",
		flag: "🇪🇹",
		label: "Tax Identification Number",
		example: "1234567890",
	},
	{
		id: "EU:eu_oss_vat",
		type: "eu_oss_vat",
		countryCode: "EU",
		country: "European Union",
		flag: "🇪🇺",
		label: "One Stop Shop VAT number",
		example: "EU123456789",
	},
	{
		id: "FI:eu_vat",
		type: "eu_vat",
		countryCode: "FI",
		country: "Finland",
		flag: "🇫🇮",
		label: "VAT number",
		example: "FI12345678",
	},
	{
		id: "FR:eu_vat",
		type: "eu_vat",
		countryCode: "FR",
		country: "France",
		flag: "🇫🇷",
		label: "VAT number",
		example: "FRAB123456789",
	},
	{
		id: "GB:eu_vat",
		type: "eu_vat",
		countryCode: "GB",
		country: "United Kingdom",
		flag: "🇬🇧",
		label: "Northern Ireland VAT number",
		example: "XI123456789",
	},
	{
		id: "GB:gb_vat",
		type: "gb_vat",
		countryCode: "GB",
		country: "United Kingdom",
		flag: "🇬🇧",
		label: "VAT number",
		example: "GB123456789",
	},
	{
		id: "GE:ge_vat",
		type: "ge_vat",
		countryCode: "GE",
		country: "Georgia",
		flag: "🇬🇪",
		label: "VAT",
		example: "123456789",
	},
	{
		id: "GN:gn_nif",
		type: "gn_nif",
		countryCode: "GN",
		country: "Guinea",
		flag: "🇬🇳",
		label: "Tax Identification Number",
		example: "123456789",
	},
	{
		id: "GR:eu_vat",
		type: "eu_vat",
		countryCode: "GR",
		country: "Greece",
		flag: "🇬🇷",
		label: "VAT number",
		example: "EL123456789",
	},
	{
		id: "HK:hk_br",
		type: "hk_br",
		countryCode: "HK",
		country: "Hong Kong",
		flag: "🇭🇰",
		label: "BR number",
		example: "12345678",
	},
	{
		id: "HR:eu_vat",
		type: "eu_vat",
		countryCode: "HR",
		country: "Croatia",
		flag: "🇭🇷",
		label: "VAT number",
		example: "HR12345678912",
	},
	{
		id: "HR:hr_oib",
		type: "hr_oib",
		countryCode: "HR",
		country: "Croatia",
		flag: "🇭🇷",
		label: "Personal Identification Number",
		example: "12345678901",
	},
	{
		id: "HU:eu_vat",
		type: "eu_vat",
		countryCode: "HU",
		country: "Hungary",
		flag: "🇭🇺",
		label: "VAT number",
		example: "HU12345678",
	},
	{
		id: "HU:hu_tin",
		type: "hu_tin",
		countryCode: "HU",
		country: "Hungary",
		flag: "🇭🇺",
		label: "Tax number (adószám)",
		example: "12345678-1-23",
	},
	{
		id: "ID:id_npwp",
		type: "id_npwp",
		countryCode: "ID",
		country: "Indonesia",
		flag: "🇮🇩",
		label: "NPWP number",
		example: "012.345.678.9-012.345",
	},
	{
		id: "IE:eu_vat",
		type: "eu_vat",
		countryCode: "IE",
		country: "Ireland",
		flag: "🇮🇪",
		label: "VAT number",
		example: "IE1234567AB",
	},
	{
		id: "IL:il_vat",
		type: "il_vat",
		countryCode: "IL",
		country: "Israel",
		flag: "🇮🇱",
		label: "VAT",
		example: "000012345",
	},
	{
		id: "IN:in_gst",
		type: "in_gst",
		countryCode: "IN",
		country: "India",
		flag: "🇮🇳",
		label: "GST number",
		example: "12ABCDE3456FGZH",
	},
	{
		id: "IS:is_vat",
		type: "is_vat",
		countryCode: "IS",
		country: "Iceland",
		flag: "🇮🇸",
		label: "VAT",
		example: "123456",
	},
	{
		id: "IT:eu_vat",
		type: "eu_vat",
		countryCode: "IT",
		country: "Italy",
		flag: "🇮🇹",
		label: "VAT number",
		example: "IT12345678912",
	},
	{
		id: "JP:jp_cn",
		type: "jp_cn",
		countryCode: "JP",
		country: "Japan",
		flag: "🇯🇵",
		label: "Corporate Number",
		example: "1234567891234",
	},
	{
		id: "JP:jp_rn",
		type: "jp_rn",
		countryCode: "JP",
		country: "Japan",
		flag: "🇯🇵",
		label: "Registered Foreign Businesses' Registration Number",
		example: "12345",
	},
	{
		id: "JP:jp_trn",
		type: "jp_trn",
		countryCode: "JP",
		country: "Japan",
		flag: "🇯🇵",
		label: "Tax Registration Number",
		example: "T1234567891234",
	},
	{
		id: "KE:ke_pin",
		type: "ke_pin",
		countryCode: "KE",
		country: "Kenya",
		flag: "🇰🇪",
		label: "PIN",
		example: "P000111111A",
	},
	{
		id: "KG:kg_tin",
		type: "kg_tin",
		countryCode: "KG",
		country: "Kyrgyzstan",
		flag: "🇰🇬",
		label: "Tax Identification Number",
		example: "12345678901234",
	},
	{
		id: "KH:kh_tin",
		type: "kh_tin",
		countryCode: "KH",
		country: "Cambodia",
		flag: "🇰🇭",
		label: "Tax Identification Number",
		example: "1001-123456789",
	},
	{
		id: "KR:kr_brn",
		type: "kr_brn",
		countryCode: "KR",
		country: "South Korea",
		flag: "🇰🇷",
		label: "BRN",
		example: "123-45-67890",
	},
	{
		id: "KZ:kz_bin",
		type: "kz_bin",
		countryCode: "KZ",
		country: "Kazakhstan",
		flag: "🇰🇿",
		label: "Business Identification Number",
		example: "123456789012",
	},
	{
		id: "LA:la_tin",
		type: "la_tin",
		countryCode: "LA",
		country: "Laos",
		flag: "🇱🇦",
		label: "Tax Identification Number",
		example: "123456789-000",
	},
	{
		id: "LI:li_uid",
		type: "li_uid",
		countryCode: "LI",
		country: "Liechtenstein",
		flag: "🇱🇮",
		label: "UID number",
		example: "CHE123456789",
	},
	{
		id: "LI:li_vat",
		type: "li_vat",
		countryCode: "LI",
		country: "Liechtenstein",
		flag: "🇱🇮",
		label: "VAT number",
		example: "12345",
	},
	{
		id: "LT:eu_vat",
		type: "eu_vat",
		countryCode: "LT",
		country: "Lithuania",
		flag: "🇱🇹",
		label: "VAT number",
		example: "LT123456789123",
	},
	{
		id: "LU:eu_vat",
		type: "eu_vat",
		countryCode: "LU",
		country: "Luxembourg",
		flag: "🇱🇺",
		label: "VAT number",
		example: "LU12345678",
	},
	{
		id: "LV:eu_vat",
		type: "eu_vat",
		countryCode: "LV",
		country: "Latvia",
		flag: "🇱🇻",
		label: "VAT number",
		example: "LV12345678912",
	},
	{
		id: "MA:ma_vat",
		type: "ma_vat",
		countryCode: "MA",
		country: "Morocco",
		flag: "🇲🇦",
		label: "VAT Number",
		example: "12345678",
	},
	{
		id: "MD:md_vat",
		type: "md_vat",
		countryCode: "MD",
		country: "Moldova",
		flag: "🇲🇩",
		label: "VAT Number",
		example: "1234567",
	},
	{
		id: "ME:me_pib",
		type: "me_pib",
		countryCode: "ME",
		country: "Montenegro",
		flag: "🇲🇪",
		label: "PIB Number",
		example: "12345678",
	},
	{
		id: "MK:mk_vat",
		type: "mk_vat",
		countryCode: "MK",
		country: "North Macedonia",
		flag: "🇲🇰",
		label: "VAT Number",
		example: "MK1234567890123",
	},
	{
		id: "MR:mr_nif",
		type: "mr_nif",
		countryCode: "MR",
		country: "Mauritania",
		flag: "🇲🇷",
		label: "Tax Identification Number",
		example: "12345678",
	},
	{
		id: "MT:eu_vat",
		type: "eu_vat",
		countryCode: "MT",
		country: "Malta",
		flag: "🇲🇹",
		label: "VAT number",
		example: "MT12345678",
	},
	{
		id: "MX:mx_rfc",
		type: "mx_rfc",
		countryCode: "MX",
		country: "Mexico",
		flag: "🇲🇽",
		label: "RFC number",
		example: "ABC010203AB9",
	},
	{
		id: "MY:my_frp",
		type: "my_frp",
		countryCode: "MY",
		country: "Malaysia",
		flag: "🇲🇾",
		label: "FRP number",
		example: "12345678",
	},
	{
		id: "MY:my_itn",
		type: "my_itn",
		countryCode: "MY",
		country: "Malaysia",
		flag: "🇲🇾",
		label: "ITN",
		example: "C 1234567890",
	},
	{
		id: "MY:my_sst",
		type: "my_sst",
		countryCode: "MY",
		country: "Malaysia",
		flag: "🇲🇾",
		label: "SST number",
		example: "A12-3456-78912345",
	},
	{
		id: "NG:ng_tin",
		type: "ng_tin",
		countryCode: "NG",
		country: "Nigeria",
		flag: "🇳🇬",
		label: "Tax Identification Number",
		example: "12345678-0001",
	},
	{
		id: "NL:eu_vat",
		type: "eu_vat",
		countryCode: "NL",
		country: "Netherlands",
		flag: "🇳🇱",
		label: "VAT number",
		example: "NL123456789B12",
	},
	{
		id: "NO:no_vat",
		type: "no_vat",
		countryCode: "NO",
		country: "Norway",
		flag: "🇳🇴",
		label: "VAT number",
		example: "123456789MVA",
	},
	{
		id: "NO:no_voec",
		type: "no_voec",
		countryCode: "NO",
		country: "Norway",
		flag: "🇳🇴",
		label: "VAT on e-commerce number",
		example: "1234567",
	},
	{
		id: "NP:np_pan",
		type: "np_pan",
		countryCode: "NP",
		country: "Nepal",
		flag: "🇳🇵",
		label: "PAN Number",
		example: "123456789",
	},
	{
		id: "NZ:nz_gst",
		type: "nz_gst",
		countryCode: "NZ",
		country: "New Zealand",
		flag: "🇳🇿",
		label: "GST number",
		example: "123456789",
	},
	{
		id: "OM:om_vat",
		type: "om_vat",
		countryCode: "OM",
		country: "Oman",
		flag: "🇴🇲",
		label: "VAT Number",
		example: "OM1234567890",
	},
	{
		id: "PE:pe_ruc",
		type: "pe_ruc",
		countryCode: "PE",
		country: "Peru",
		flag: "🇵🇪",
		label: "RUC number",
		example: "12345678901",
	},
	{
		id: "PH:ph_tin",
		type: "ph_tin",
		countryCode: "PH",
		country: "Philippines",
		flag: "🇵🇭",
		label: "Tax Identification Number",
		example: "123456789012",
	},
	{
		id: "PL:eu_vat",
		type: "eu_vat",
		countryCode: "PL",
		country: "Poland",
		flag: "🇵🇱",
		label: "VAT number",
		example: "PL1234567890",
	},
	{
		id: "PT:eu_vat",
		type: "eu_vat",
		countryCode: "PT",
		country: "Portugal",
		flag: "🇵🇹",
		label: "VAT number",
		example: "PT123456789",
	},
	{
		id: "RO:eu_vat",
		type: "eu_vat",
		countryCode: "RO",
		country: "Romania",
		flag: "🇷🇴",
		label: "VAT number",
		example: "RO1234567891",
	},
	{
		id: "RO:ro_tin",
		type: "ro_tin",
		countryCode: "RO",
		country: "Romania",
		flag: "🇷🇴",
		label: "Tax ID number",
		example: "1234567890123",
	},
	{
		id: "RS:rs_pib",
		type: "rs_pib",
		countryCode: "RS",
		country: "Serbia",
		flag: "🇷🇸",
		label: "PIB number",
		example: "123456789",
	},
	{
		id: "RU:ru_inn",
		type: "ru_inn",
		countryCode: "RU",
		country: "Russia",
		flag: "🇷🇺",
		label: "INN",
		example: "1234567891",
	},
	{
		id: "RU:ru_kpp",
		type: "ru_kpp",
		countryCode: "RU",
		country: "Russia",
		flag: "🇷🇺",
		label: "KPP",
		example: "123456789",
	},
	{
		id: "SA:sa_vat",
		type: "sa_vat",
		countryCode: "SA",
		country: "Saudi Arabia",
		flag: "🇸🇦",
		label: "VAT",
		example: "123456789012345",
	},
	{
		id: "SE:eu_vat",
		type: "eu_vat",
		countryCode: "SE",
		country: "Sweden",
		flag: "🇸🇪",
		label: "VAT number",
		example: "SE123456789123",
	},
	{
		id: "SG:sg_gst",
		type: "sg_gst",
		countryCode: "SG",
		country: "Singapore",
		flag: "🇸🇬",
		label: "GST",
		example: "M12345678X",
	},
	{
		id: "SG:sg_uen",
		type: "sg_uen",
		countryCode: "SG",
		country: "Singapore",
		flag: "🇸🇬",
		label: "UEN",
		example: "123456789F",
	},
	{
		id: "SI:eu_vat",
		type: "eu_vat",
		countryCode: "SI",
		country: "Slovenia",
		flag: "🇸🇮",
		label: "VAT number",
		example: "SI12345678",
	},
	{
		id: "SI:si_tin",
		type: "si_tin",
		countryCode: "SI",
		country: "Slovenia",
		flag: "🇸🇮",
		label: "Tax number (davčna številka)",
		example: "12345678",
	},
	{
		id: "SK:eu_vat",
		type: "eu_vat",
		countryCode: "SK",
		country: "Slovakia",
		flag: "🇸🇰",
		label: "VAT number",
		example: "SK1234567891",
	},
	{
		id: "SN:sn_ninea",
		type: "sn_ninea",
		countryCode: "SN",
		country: "Senegal",
		flag: "🇸🇳",
		label: "NINEA Number",
		example: "12345672A2",
	},
	{
		id: "SR:sr_fin",
		type: "sr_fin",
		countryCode: "SR",
		country: "Suriname",
		flag: "🇸🇷",
		label: "FIN Number",
		example: "1234567890",
	},
	{
		id: "SV:sv_nit",
		type: "sv_nit",
		countryCode: "SV",
		country: "El Salvador",
		flag: "🇸🇻",
		label: "NIT number",
		example: "1234-567890-123-4",
	},
	{
		id: "TH:th_vat",
		type: "th_vat",
		countryCode: "TH",
		country: "Thailand",
		flag: "🇹🇭",
		label: "VAT",
		example: "1234567891234",
	},
	{
		id: "TJ:tj_tin",
		type: "tj_tin",
		countryCode: "TJ",
		country: "Tajikistan",
		flag: "🇹🇯",
		label: "Tax Identification Number",
		example: "123456789",
	},
	{
		id: "TR:tr_tin",
		type: "tr_tin",
		countryCode: "TR",
		country: "Türkiye",
		flag: "🇹🇷",
		label: "Tax Identification Number",
		example: "0123456789",
	},
	{
		id: "TW:tw_vat",
		type: "tw_vat",
		countryCode: "TW",
		country: "Taiwan",
		flag: "🇹🇼",
		label: "VAT",
		example: "12345678",
	},
	{
		id: "TZ:tz_vat",
		type: "tz_vat",
		countryCode: "TZ",
		country: "Tanzania",
		flag: "🇹🇿",
		label: "VAT Number",
		example: "12345678A",
	},
	{
		id: "UA:ua_vat",
		type: "ua_vat",
		countryCode: "UA",
		country: "Ukraine",
		flag: "🇺🇦",
		label: "VAT",
		example: "123456789",
	},
	{
		id: "UG:ug_tin",
		type: "ug_tin",
		countryCode: "UG",
		country: "Uganda",
		flag: "🇺🇬",
		label: "Tax Identification Number",
		example: "1014751879",
	},
	{
		id: "US:us_ein",
		type: "us_ein",
		countryCode: "US",
		country: "United States",
		flag: "🇺🇸",
		label: "EIN",
		example: "12-3456789",
	},
	{
		id: "UY:uy_ruc",
		type: "uy_ruc",
		countryCode: "UY",
		country: "Uruguay",
		flag: "🇺🇾",
		label: "RUC number",
		example: "123456789012",
	},
	{
		id: "UZ:uz_tin",
		type: "uz_tin",
		countryCode: "UZ",
		country: "Uzbekistan",
		flag: "🇺🇿",
		label: "TIN Number",
		example: "123456789",
	},
	{
		id: "UZ:uz_vat",
		type: "uz_vat",
		countryCode: "UZ",
		country: "Uzbekistan",
		flag: "🇺🇿",
		label: "VAT Number",
		example: "123456789",
	},
	{
		id: "VE:ve_rif",
		type: "ve_rif",
		countryCode: "VE",
		country: "Venezuela",
		flag: "🇻🇪",
		label: "RIF number",
		example: "A-12345678-9",
	},
	{
		id: "VN:vn_tin",
		type: "vn_tin",
		countryCode: "VN",
		country: "Vietnam",
		flag: "🇻🇳",
		label: "Tax ID number",
		example: "1234567890",
	},
	{
		id: "ZA:za_vat",
		type: "za_vat",
		countryCode: "ZA",
		country: "South Africa",
		flag: "🇿🇦",
		label: "VAT number",
		example: "4123456789",
	},
	{
		id: "ZM:zm_tin",
		type: "zm_tin",
		countryCode: "ZM",
		country: "Zambia",
		flag: "🇿🇲",
		label: "Tax Identification Number",
		example: "1004789012",
	},
	{
		id: "ZW:zw_tin",
		type: "zw_tin",
		countryCode: "ZW",
		country: "Zimbabwe",
		flag: "🇿🇼",
		label: "Tax Identification Number",
		example: "1234567890",
	},
];

const optionsByType = new Map(
	STRIPE_TAX_ID_OPTIONS.map((option) => [
		`${option.countryCode}:${option.type}`,
		option,
	]),
);

/** Resolves a stored Stripe tax id back to its picker option, if the country is known. */
export const findStripeTaxIdOption = ({
	type,
	countryCode,
}: {
	type: string;
	countryCode?: string | null;
}): StripeTaxIdOption | undefined => {
	if (countryCode) {
		const exact = optionsByType.get(`${countryCode.toUpperCase()}:${type}`);
		if (exact) return exact;
	}
	return STRIPE_TAX_ID_OPTIONS.find((option) => option.type === type);
};
