/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type BillingUpdateGlobals = {
  xApiVersion?: string | undefined;
};

export type BillingUpdateFeatureQuantities = {
  featureId: string;
  quantity?: number | undefined;
  adjustable?: boolean | undefined;
};

export const BillingUpdateDurationType = {
  Day: "day",
  Month: "month",
  Year: "year",
} as const;
export type BillingUpdateDurationType = ClosedEnum<
  typeof BillingUpdateDurationType
>;

export type BillingUpdateFreeTrial = {
  durationLength: number;
  durationType?: BillingUpdateDurationType | undefined;
  cardRequired?: boolean | undefined;
};

export const BillingUpdatePriceInterval = {
  OneOff: "one_off",
  Week: "week",
  Month: "month",
  Quarter: "quarter",
  SemiAnnual: "semi_annual",
  Year: "year",
} as const;
export type BillingUpdatePriceInterval = ClosedEnum<
  typeof BillingUpdatePriceInterval
>;

export type BillingUpdatePrice = {
  amount: number;
  interval: BillingUpdatePriceInterval;
  intervalCount?: number | undefined;
};

export const BillingUpdateResetInterval = {
  OneOff: "one_off",
  Minute: "minute",
  Hour: "hour",
  Day: "day",
  Week: "week",
  Month: "month",
  Quarter: "quarter",
  SemiAnnual: "semi_annual",
  Year: "year",
} as const;
export type BillingUpdateResetInterval = ClosedEnum<
  typeof BillingUpdateResetInterval
>;

export type BillingUpdateReset = {
  interval: BillingUpdateResetInterval;
  intervalCount?: number | undefined;
};

export type BillingUpdateTo = number | string;

export type BillingUpdateTier = {
  to: number | string;
  amount: number;
};

export const BillingUpdateItemPriceInterval = {
  OneOff: "one_off",
  Week: "week",
  Month: "month",
  Quarter: "quarter",
  SemiAnnual: "semi_annual",
  Year: "year",
} as const;
export type BillingUpdateItemPriceInterval = ClosedEnum<
  typeof BillingUpdateItemPriceInterval
>;

export const BillingUpdateBillingMethod = {
  Prepaid: "prepaid",
  UsageBased: "usage_based",
} as const;
export type BillingUpdateBillingMethod = ClosedEnum<
  typeof BillingUpdateBillingMethod
>;

export type BillingUpdateItemPrice = {
  amount?: number | undefined;
  tiers?: Array<BillingUpdateTier> | undefined;
  interval: BillingUpdateItemPriceInterval;
  intervalCount?: number | undefined;
  billingUnits?: number | undefined;
  billingMethod: BillingUpdateBillingMethod;
  maxPurchase?: number | undefined;
};

export const BillingUpdateOnIncrease = {
  BillImmediately: "bill_immediately",
  ProrateImmediately: "prorate_immediately",
  ProrateNextCycle: "prorate_next_cycle",
  BillNextCycle: "bill_next_cycle",
} as const;
export type BillingUpdateOnIncrease = ClosedEnum<
  typeof BillingUpdateOnIncrease
>;

export const BillingUpdateOnDecrease = {
  Prorate: "prorate",
  ProrateImmediately: "prorate_immediately",
  ProrateNextCycle: "prorate_next_cycle",
  None: "none",
  NoProrations: "no_prorations",
} as const;
export type BillingUpdateOnDecrease = ClosedEnum<
  typeof BillingUpdateOnDecrease
>;

export type BillingUpdateProration = {
  onIncrease: BillingUpdateOnIncrease;
  onDecrease: BillingUpdateOnDecrease;
};

export const BillingUpdateExpiryDurationType = {
  Month: "month",
  Forever: "forever",
} as const;
export type BillingUpdateExpiryDurationType = ClosedEnum<
  typeof BillingUpdateExpiryDurationType
>;

export type BillingUpdateRollover = {
  max?: number | undefined;
  expiryDurationType: BillingUpdateExpiryDurationType;
  expiryDurationLength?: number | undefined;
};

export type BillingUpdateItem = {
  featureId: string;
  included?: number | undefined;
  unlimited?: boolean | undefined;
  reset?: BillingUpdateReset | undefined;
  price?: BillingUpdateItemPrice | undefined;
  proration?: BillingUpdateProration | undefined;
  rollover?: BillingUpdateRollover | undefined;
};

export type BillingUpdateCustomize = {
  price?: BillingUpdatePrice | null | undefined;
  items?: Array<BillingUpdateItem> | undefined;
};

export type BillingUpdateInvoiceMode = {
  enabled: boolean;
  enableProductImmediately?: boolean | undefined;
  finalizeInvoice?: boolean | undefined;
};

export const BillingUpdateCancelAction = {
  CancelImmediately: "cancel_immediately",
  CancelEndOfCycle: "cancel_end_of_cycle",
  Uncancel: "uncancel",
} as const;
export type BillingUpdateCancelAction = ClosedEnum<
  typeof BillingUpdateCancelAction
>;

export const BillingUpdateBillingBehavior = {
  ProrateImmediately: "prorate_immediately",
  NextCycleOnly: "next_cycle_only",
} as const;
export type BillingUpdateBillingBehavior = ClosedEnum<
  typeof BillingUpdateBillingBehavior
>;

export type BillingUpdateRequest = {
  /**
   * The ID of the customer to attach the plan to.
   */
  customerId: string;
  /**
   * The ID of the entity to attach the plan to.
   */
  entityId?: string | null | undefined;
  /**
   * If this plan contains prepaid features, use this field to specify the quantity of each prepaid feature. This quantity includes the included amount and billing units defined when setting up the plan.
   */
  featureQuantities?: Array<BillingUpdateFeatureQuantities> | null | undefined;
  version?: number | undefined;
  freeTrial?: BillingUpdateFreeTrial | null | undefined;
  customize?: BillingUpdateCustomize | undefined;
  planId?: string | null | undefined;
  invoiceMode?: BillingUpdateInvoiceMode | undefined;
  cancelAction?: BillingUpdateCancelAction | undefined;
  billingBehavior?: BillingUpdateBillingBehavior | undefined;
};

export type BillingUpdateInvoice = {
  status: string | null;
  stripeId: string;
  total: number;
  currency: string;
  hostedInvoiceUrl: string | null;
};

export const BillingUpdateCode = {
  ThreedsRequired: "3ds_required",
  PaymentMethodRequired: "payment_method_required",
  PaymentFailed: "payment_failed",
} as const;
export type BillingUpdateCode = OpenEnum<typeof BillingUpdateCode>;

export type BillingUpdateRequiredAction = {
  code: BillingUpdateCode;
  reason: string;
};

/**
 * OK
 */
export type BillingUpdateResponse = {
  customerId: string;
  entityId?: string | undefined;
  invoice?: BillingUpdateInvoice | undefined;
  paymentUrl: string | null;
  requiredAction?: BillingUpdateRequiredAction | undefined;
};

/** @internal */
export type BillingUpdateFeatureQuantities$Outbound = {
  feature_id: string;
  quantity?: number | undefined;
  adjustable?: boolean | undefined;
};

/** @internal */
export const BillingUpdateFeatureQuantities$outboundSchema: z.ZodMiniType<
  BillingUpdateFeatureQuantities$Outbound,
  BillingUpdateFeatureQuantities
> = z.pipe(
  z.object({
    featureId: z.string(),
    quantity: z.optional(z.number()),
    adjustable: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      featureId: "feature_id",
    });
  }),
);

export function billingUpdateFeatureQuantitiesToJSON(
  billingUpdateFeatureQuantities: BillingUpdateFeatureQuantities,
): string {
  return JSON.stringify(
    BillingUpdateFeatureQuantities$outboundSchema.parse(
      billingUpdateFeatureQuantities,
    ),
  );
}

/** @internal */
export const BillingUpdateDurationType$outboundSchema: z.ZodMiniEnum<
  typeof BillingUpdateDurationType
> = z.enum(BillingUpdateDurationType);

/** @internal */
export type BillingUpdateFreeTrial$Outbound = {
  duration_length: number;
  duration_type: string;
  card_required: boolean;
};

/** @internal */
export const BillingUpdateFreeTrial$outboundSchema: z.ZodMiniType<
  BillingUpdateFreeTrial$Outbound,
  BillingUpdateFreeTrial
> = z.pipe(
  z.object({
    durationLength: z.number(),
    durationType: z._default(BillingUpdateDurationType$outboundSchema, "month"),
    cardRequired: z._default(z.boolean(), true),
  }),
  z.transform((v) => {
    return remap$(v, {
      durationLength: "duration_length",
      durationType: "duration_type",
      cardRequired: "card_required",
    });
  }),
);

export function billingUpdateFreeTrialToJSON(
  billingUpdateFreeTrial: BillingUpdateFreeTrial,
): string {
  return JSON.stringify(
    BillingUpdateFreeTrial$outboundSchema.parse(billingUpdateFreeTrial),
  );
}

/** @internal */
export const BillingUpdatePriceInterval$outboundSchema: z.ZodMiniEnum<
  typeof BillingUpdatePriceInterval
> = z.enum(BillingUpdatePriceInterval);

/** @internal */
export type BillingUpdatePrice$Outbound = {
  amount: number;
  interval: string;
  interval_count?: number | undefined;
};

/** @internal */
export const BillingUpdatePrice$outboundSchema: z.ZodMiniType<
  BillingUpdatePrice$Outbound,
  BillingUpdatePrice
> = z.pipe(
  z.object({
    amount: z.number(),
    interval: BillingUpdatePriceInterval$outboundSchema,
    intervalCount: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      intervalCount: "interval_count",
    });
  }),
);

export function billingUpdatePriceToJSON(
  billingUpdatePrice: BillingUpdatePrice,
): string {
  return JSON.stringify(
    BillingUpdatePrice$outboundSchema.parse(billingUpdatePrice),
  );
}

/** @internal */
export const BillingUpdateResetInterval$outboundSchema: z.ZodMiniEnum<
  typeof BillingUpdateResetInterval
> = z.enum(BillingUpdateResetInterval);

/** @internal */
export type BillingUpdateReset$Outbound = {
  interval: string;
  interval_count?: number | undefined;
};

/** @internal */
export const BillingUpdateReset$outboundSchema: z.ZodMiniType<
  BillingUpdateReset$Outbound,
  BillingUpdateReset
> = z.pipe(
  z.object({
    interval: BillingUpdateResetInterval$outboundSchema,
    intervalCount: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      intervalCount: "interval_count",
    });
  }),
);

export function billingUpdateResetToJSON(
  billingUpdateReset: BillingUpdateReset,
): string {
  return JSON.stringify(
    BillingUpdateReset$outboundSchema.parse(billingUpdateReset),
  );
}

/** @internal */
export type BillingUpdateTo$Outbound = number | string;

/** @internal */
export const BillingUpdateTo$outboundSchema: z.ZodMiniType<
  BillingUpdateTo$Outbound,
  BillingUpdateTo
> = smartUnion([z.number(), z.string()]);

export function billingUpdateToToJSON(
  billingUpdateTo: BillingUpdateTo,
): string {
  return JSON.stringify(BillingUpdateTo$outboundSchema.parse(billingUpdateTo));
}

/** @internal */
export type BillingUpdateTier$Outbound = {
  to: number | string;
  amount: number;
};

/** @internal */
export const BillingUpdateTier$outboundSchema: z.ZodMiniType<
  BillingUpdateTier$Outbound,
  BillingUpdateTier
> = z.object({
  to: smartUnion([z.number(), z.string()]),
  amount: z.number(),
});

export function billingUpdateTierToJSON(
  billingUpdateTier: BillingUpdateTier,
): string {
  return JSON.stringify(
    BillingUpdateTier$outboundSchema.parse(billingUpdateTier),
  );
}

/** @internal */
export const BillingUpdateItemPriceInterval$outboundSchema: z.ZodMiniEnum<
  typeof BillingUpdateItemPriceInterval
> = z.enum(BillingUpdateItemPriceInterval);

/** @internal */
export const BillingUpdateBillingMethod$outboundSchema: z.ZodMiniEnum<
  typeof BillingUpdateBillingMethod
> = z.enum(BillingUpdateBillingMethod);

/** @internal */
export type BillingUpdateItemPrice$Outbound = {
  amount?: number | undefined;
  tiers?: Array<BillingUpdateTier$Outbound> | undefined;
  interval: string;
  interval_count: number;
  billing_units: number;
  billing_method: string;
  max_purchase?: number | undefined;
};

/** @internal */
export const BillingUpdateItemPrice$outboundSchema: z.ZodMiniType<
  BillingUpdateItemPrice$Outbound,
  BillingUpdateItemPrice
> = z.pipe(
  z.object({
    amount: z.optional(z.number()),
    tiers: z.optional(z.array(z.lazy(() => BillingUpdateTier$outboundSchema))),
    interval: BillingUpdateItemPriceInterval$outboundSchema,
    intervalCount: z._default(z.number(), 1),
    billingUnits: z._default(z.number(), 1),
    billingMethod: BillingUpdateBillingMethod$outboundSchema,
    maxPurchase: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      intervalCount: "interval_count",
      billingUnits: "billing_units",
      billingMethod: "billing_method",
      maxPurchase: "max_purchase",
    });
  }),
);

export function billingUpdateItemPriceToJSON(
  billingUpdateItemPrice: BillingUpdateItemPrice,
): string {
  return JSON.stringify(
    BillingUpdateItemPrice$outboundSchema.parse(billingUpdateItemPrice),
  );
}

/** @internal */
export const BillingUpdateOnIncrease$outboundSchema: z.ZodMiniEnum<
  typeof BillingUpdateOnIncrease
> = z.enum(BillingUpdateOnIncrease);

/** @internal */
export const BillingUpdateOnDecrease$outboundSchema: z.ZodMiniEnum<
  typeof BillingUpdateOnDecrease
> = z.enum(BillingUpdateOnDecrease);

/** @internal */
export type BillingUpdateProration$Outbound = {
  on_increase: string;
  on_decrease: string;
};

/** @internal */
export const BillingUpdateProration$outboundSchema: z.ZodMiniType<
  BillingUpdateProration$Outbound,
  BillingUpdateProration
> = z.pipe(
  z.object({
    onIncrease: BillingUpdateOnIncrease$outboundSchema,
    onDecrease: BillingUpdateOnDecrease$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      onIncrease: "on_increase",
      onDecrease: "on_decrease",
    });
  }),
);

export function billingUpdateProrationToJSON(
  billingUpdateProration: BillingUpdateProration,
): string {
  return JSON.stringify(
    BillingUpdateProration$outboundSchema.parse(billingUpdateProration),
  );
}

/** @internal */
export const BillingUpdateExpiryDurationType$outboundSchema: z.ZodMiniEnum<
  typeof BillingUpdateExpiryDurationType
> = z.enum(BillingUpdateExpiryDurationType);

/** @internal */
export type BillingUpdateRollover$Outbound = {
  max?: number | undefined;
  expiry_duration_type: string;
  expiry_duration_length?: number | undefined;
};

/** @internal */
export const BillingUpdateRollover$outboundSchema: z.ZodMiniType<
  BillingUpdateRollover$Outbound,
  BillingUpdateRollover
> = z.pipe(
  z.object({
    max: z.optional(z.number()),
    expiryDurationType: BillingUpdateExpiryDurationType$outboundSchema,
    expiryDurationLength: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      expiryDurationType: "expiry_duration_type",
      expiryDurationLength: "expiry_duration_length",
    });
  }),
);

export function billingUpdateRolloverToJSON(
  billingUpdateRollover: BillingUpdateRollover,
): string {
  return JSON.stringify(
    BillingUpdateRollover$outboundSchema.parse(billingUpdateRollover),
  );
}

/** @internal */
export type BillingUpdateItem$Outbound = {
  feature_id: string;
  included?: number | undefined;
  unlimited?: boolean | undefined;
  reset?: BillingUpdateReset$Outbound | undefined;
  price?: BillingUpdateItemPrice$Outbound | undefined;
  proration?: BillingUpdateProration$Outbound | undefined;
  rollover?: BillingUpdateRollover$Outbound | undefined;
};

/** @internal */
export const BillingUpdateItem$outboundSchema: z.ZodMiniType<
  BillingUpdateItem$Outbound,
  BillingUpdateItem
> = z.pipe(
  z.object({
    featureId: z.string(),
    included: z.optional(z.number()),
    unlimited: z.optional(z.boolean()),
    reset: z.optional(z.lazy(() => BillingUpdateReset$outboundSchema)),
    price: z.optional(z.lazy(() => BillingUpdateItemPrice$outboundSchema)),
    proration: z.optional(z.lazy(() => BillingUpdateProration$outboundSchema)),
    rollover: z.optional(z.lazy(() => BillingUpdateRollover$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      featureId: "feature_id",
    });
  }),
);

export function billingUpdateItemToJSON(
  billingUpdateItem: BillingUpdateItem,
): string {
  return JSON.stringify(
    BillingUpdateItem$outboundSchema.parse(billingUpdateItem),
  );
}

/** @internal */
export type BillingUpdateCustomize$Outbound = {
  price?: BillingUpdatePrice$Outbound | null | undefined;
  items?: Array<BillingUpdateItem$Outbound> | undefined;
};

/** @internal */
export const BillingUpdateCustomize$outboundSchema: z.ZodMiniType<
  BillingUpdateCustomize$Outbound,
  BillingUpdateCustomize
> = z.object({
  price: z.optional(
    z.nullable(z.lazy(() => BillingUpdatePrice$outboundSchema)),
  ),
  items: z.optional(z.array(z.lazy(() => BillingUpdateItem$outboundSchema))),
});

export function billingUpdateCustomizeToJSON(
  billingUpdateCustomize: BillingUpdateCustomize,
): string {
  return JSON.stringify(
    BillingUpdateCustomize$outboundSchema.parse(billingUpdateCustomize),
  );
}

/** @internal */
export type BillingUpdateInvoiceMode$Outbound = {
  enabled: boolean;
  enable_product_immediately: boolean;
  finalize_invoice: boolean;
};

/** @internal */
export const BillingUpdateInvoiceMode$outboundSchema: z.ZodMiniType<
  BillingUpdateInvoiceMode$Outbound,
  BillingUpdateInvoiceMode
> = z.pipe(
  z.object({
    enabled: z.boolean(),
    enableProductImmediately: z._default(z.boolean(), false),
    finalizeInvoice: z._default(z.boolean(), true),
  }),
  z.transform((v) => {
    return remap$(v, {
      enableProductImmediately: "enable_product_immediately",
      finalizeInvoice: "finalize_invoice",
    });
  }),
);

export function billingUpdateInvoiceModeToJSON(
  billingUpdateInvoiceMode: BillingUpdateInvoiceMode,
): string {
  return JSON.stringify(
    BillingUpdateInvoiceMode$outboundSchema.parse(billingUpdateInvoiceMode),
  );
}

/** @internal */
export const BillingUpdateCancelAction$outboundSchema: z.ZodMiniEnum<
  typeof BillingUpdateCancelAction
> = z.enum(BillingUpdateCancelAction);

/** @internal */
export const BillingUpdateBillingBehavior$outboundSchema: z.ZodMiniEnum<
  typeof BillingUpdateBillingBehavior
> = z.enum(BillingUpdateBillingBehavior);

/** @internal */
export type BillingUpdateRequest$Outbound = {
  customer_id: string;
  entity_id?: string | null | undefined;
  feature_quantities?:
    | Array<BillingUpdateFeatureQuantities$Outbound>
    | null
    | undefined;
  version?: number | undefined;
  free_trial?: BillingUpdateFreeTrial$Outbound | null | undefined;
  customize?: BillingUpdateCustomize$Outbound | undefined;
  plan_id?: string | null | undefined;
  invoice_mode?: BillingUpdateInvoiceMode$Outbound | undefined;
  cancel_action?: string | undefined;
  billing_behavior?: string | undefined;
};

/** @internal */
export const BillingUpdateRequest$outboundSchema: z.ZodMiniType<
  BillingUpdateRequest$Outbound,
  BillingUpdateRequest
> = z.pipe(
  z.object({
    customerId: z.string(),
    entityId: z.optional(z.nullable(z.string())),
    featureQuantities: z.optional(z.nullable(z.array(z.lazy(() =>
      BillingUpdateFeatureQuantities$outboundSchema
    )))),
    version: z.optional(z.number()),
    freeTrial: z.optional(z.nullable(z.lazy(() =>
      BillingUpdateFreeTrial$outboundSchema
    ))),
    customize: z.optional(z.lazy(() =>
      BillingUpdateCustomize$outboundSchema
    )),
    planId: z.optional(z.nullable(z.string())),
    invoiceMode: z.optional(
      z.lazy(() => BillingUpdateInvoiceMode$outboundSchema),
    ),
    cancelAction: z.optional(BillingUpdateCancelAction$outboundSchema),
    billingBehavior: z.optional(BillingUpdateBillingBehavior$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      customerId: "customer_id",
      entityId: "entity_id",
      featureQuantities: "feature_quantities",
      freeTrial: "free_trial",
      planId: "plan_id",
      invoiceMode: "invoice_mode",
      cancelAction: "cancel_action",
      billingBehavior: "billing_behavior",
    });
  }),
);

export function billingUpdateRequestToJSON(
  billingUpdateRequest: BillingUpdateRequest,
): string {
  return JSON.stringify(
    BillingUpdateRequest$outboundSchema.parse(billingUpdateRequest),
  );
}

/** @internal */
export const BillingUpdateInvoice$inboundSchema: z.ZodMiniType<
  BillingUpdateInvoice,
  unknown
> = z.pipe(
  z.object({
    status: types.nullable(types.string()),
    stripe_id: types.string(),
    total: types.number(),
    currency: types.string(),
    hosted_invoice_url: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "stripe_id": "stripeId",
      "hosted_invoice_url": "hostedInvoiceUrl",
    });
  }),
);

export function billingUpdateInvoiceFromJSON(
  jsonString: string,
): SafeParseResult<BillingUpdateInvoice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BillingUpdateInvoice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BillingUpdateInvoice' from JSON`,
  );
}

/** @internal */
export const BillingUpdateCode$inboundSchema: z.ZodMiniType<
  BillingUpdateCode,
  unknown
> = openEnums.inboundSchema(BillingUpdateCode);

/** @internal */
export const BillingUpdateRequiredAction$inboundSchema: z.ZodMiniType<
  BillingUpdateRequiredAction,
  unknown
> = z.object({
  code: BillingUpdateCode$inboundSchema,
  reason: types.string(),
});

export function billingUpdateRequiredActionFromJSON(
  jsonString: string,
): SafeParseResult<BillingUpdateRequiredAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BillingUpdateRequiredAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BillingUpdateRequiredAction' from JSON`,
  );
}

/** @internal */
export const BillingUpdateResponse$inboundSchema: z.ZodMiniType<
  BillingUpdateResponse,
  unknown
> = z.pipe(
  z.object({
    customer_id: types.string(),
    entity_id: types.optional(types.string()),
    invoice: types.optional(z.lazy(() => BillingUpdateInvoice$inboundSchema)),
    payment_url: types.nullable(types.string()),
    required_action: types.optional(
      z.lazy(() => BillingUpdateRequiredAction$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "customer_id": "customerId",
      "entity_id": "entityId",
      "payment_url": "paymentUrl",
      "required_action": "requiredAction",
    });
  }),
);

export function billingUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<BillingUpdateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BillingUpdateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BillingUpdateResponse' from JSON`,
  );
}
