/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type DeleteRewardGlobals = {
  xApiVersion?: string | undefined;
};

export type DeleteRewardParams = {
  /**
   * The ID of the coupon or feature grant to delete.
   */
  id: string;
};

/**
 * OK
 */
export type DeleteRewardResponse = {
  id: string;
  deleted: true;
};

/** @internal */
export type DeleteRewardParams$Outbound = {
  id: string;
};

/** @internal */
export const DeleteRewardParams$outboundSchema: z.ZodMiniType<
  DeleteRewardParams$Outbound,
  DeleteRewardParams
> = z.object({
  id: z.string(),
});

export function deleteRewardParamsToJSON(
  deleteRewardParams: DeleteRewardParams,
): string {
  return JSON.stringify(
    DeleteRewardParams$outboundSchema.parse(deleteRewardParams),
  );
}

/** @internal */
export const DeleteRewardResponse$inboundSchema: z.ZodMiniType<
  DeleteRewardResponse,
  unknown
> = z.object({
  id: types.string(),
  deleted: types.literal(true),
});

export function deleteRewardResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteRewardResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteRewardResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteRewardResponse' from JSON`,
  );
}
