/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type FinalizeInvoiceGlobals = {
  xApiVersion?: string | undefined;
};

export type FinalizeInvoiceParams = {
  /**
   * The Autumn invoice ID to finalize.
   */
  invoiceId: string;
};

/**
 * The billing processor that owns this invoice.
 */
export const FinalizeInvoiceProcessorType = {
  Stripe: "stripe",
  Revenuecat: "revenuecat",
} as const;
/**
 * The billing processor that owns this invoice.
 */
export type FinalizeInvoiceProcessorType = OpenEnum<
  typeof FinalizeInvoiceProcessorType
>;

export type FinalizeInvoiceEntity = {
  /**
   * The entity this share of the line item is attributed to
   */
  entityId: string;
  /**
   * Quantity charged to this entity. Null on fixed-price lines.
   */
  quantity: number | null;
  /**
   * Amount attributed to this entity, pre-discount and pre-tax
   */
  amount: number;
};

export type FinalizeInvoiceItem = {
  /**
   * The Autumn invoice line item ID. Stable across reads, and can be used to reference this line in later calls.
   */
  id: string;
  /**
   * Description of the invoice line item
   */
  description: string;
  /**
   * Timestamp when the billing period starts
   */
  periodStart: number | null;
  /**
   * Timestamp when the billing period ends
   */
  periodEnd: number | null;
  /**
   * The plan this line item came from. Null for lines with no Autumn plan behind them.
   */
  planId: string | null;
  /**
   * The ID of the feature associated with this line item
   */
  featureId: string | null;
  /**
   * The name of the feature associated with this line item
   */
  featureName: string | null;
  /**
   * Quantity actually charged on this line. Null on fixed-price lines.
   */
  quantity: number | null;
  /**
   * Amount charged on this line, pre-discount and pre-tax. Negative for credits.
   */
  amount: number;
  /**
   * How this line splits by entity. Empty for customer-level lines. Only populated for invoices finalized after entity attribution shipped.
   */
  entities: Array<FinalizeInvoiceEntity>;
};

export type FinalizeInvoiceInvoice = {
  /**
   * Array of plan IDs included in this invoice
   */
  planIds: Array<string>;
  /**
   * The Stripe invoice ID
   */
  stripeId: string;
  /**
   * The billing processor that owns this invoice.
   */
  processorType: FinalizeInvoiceProcessorType;
  /**
   * The status of the invoice
   */
  status: string;
  /**
   * The total amount of the invoice
   */
  total: number;
  /**
   * The currency code for the invoice
   */
  currency: string;
  /**
   * Timestamp when the invoice was created
   */
  createdAt: number;
  /**
   * URL to the Stripe-hosted invoice page
   */
  hostedInvoiceUrl?: string | null | undefined;
  /**
   * The Autumn invoice ID
   */
  id: string;
  /**
   * The ID of the customer this invoice belongs to. Null for customers created without an ID.
   */
  customerId: string | null;
  /**
   * The ID of the entity this invoice belongs to, if entity-scoped
   */
  entityId: string | null;
  /**
   * The amount paid on the invoice. Null on invoices recorded before amounts paid were tracked.
   */
  amountPaid: number | null;
  /**
   * The total amount refunded on the invoice
   */
  refundedAmount: number;
  /**
   * Line items on the invoice, one per line as shown in Stripe. Capped at 100. Empty for invoices recorded before line item storage.
   */
  items?: Array<FinalizeInvoiceItem> | undefined;
};

/**
 * OK
 */
export type FinalizeInvoiceResponse = {
  invoice: FinalizeInvoiceInvoice;
};

/** @internal */
export type FinalizeInvoiceParams$Outbound = {
  invoice_id: string;
};

/** @internal */
export const FinalizeInvoiceParams$outboundSchema: z.ZodMiniType<
  FinalizeInvoiceParams$Outbound,
  FinalizeInvoiceParams
> = z.pipe(
  z.object({
    invoiceId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      invoiceId: "invoice_id",
    });
  }),
);

export function finalizeInvoiceParamsToJSON(
  finalizeInvoiceParams: FinalizeInvoiceParams,
): string {
  return JSON.stringify(
    FinalizeInvoiceParams$outboundSchema.parse(finalizeInvoiceParams),
  );
}

/** @internal */
export const FinalizeInvoiceProcessorType$inboundSchema: z.ZodMiniType<
  FinalizeInvoiceProcessorType,
  unknown
> = openEnums.inboundSchema(FinalizeInvoiceProcessorType);

/** @internal */
export const FinalizeInvoiceEntity$inboundSchema: z.ZodMiniType<
  FinalizeInvoiceEntity,
  unknown
> = z.pipe(
  z.object({
    entity_id: types.string(),
    quantity: types.nullable(types.number()),
    amount: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "entity_id": "entityId",
    });
  }),
);

export function finalizeInvoiceEntityFromJSON(
  jsonString: string,
): SafeParseResult<FinalizeInvoiceEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FinalizeInvoiceEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FinalizeInvoiceEntity' from JSON`,
  );
}

/** @internal */
export const FinalizeInvoiceItem$inboundSchema: z.ZodMiniType<
  FinalizeInvoiceItem,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    description: types.string(),
    period_start: types.nullable(types.number()),
    period_end: types.nullable(types.number()),
    plan_id: types.nullable(types.string()),
    feature_id: types.nullable(types.string()),
    feature_name: types.nullable(types.string()),
    quantity: types.nullable(types.number()),
    amount: types.number(),
    entities: z.array(z.lazy(() => FinalizeInvoiceEntity$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "period_start": "periodStart",
      "period_end": "periodEnd",
      "plan_id": "planId",
      "feature_id": "featureId",
      "feature_name": "featureName",
    });
  }),
);

export function finalizeInvoiceItemFromJSON(
  jsonString: string,
): SafeParseResult<FinalizeInvoiceItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FinalizeInvoiceItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FinalizeInvoiceItem' from JSON`,
  );
}

/** @internal */
export const FinalizeInvoiceInvoice$inboundSchema: z.ZodMiniType<
  FinalizeInvoiceInvoice,
  unknown
> = z.pipe(
  z.object({
    plan_ids: z.array(types.string()),
    stripe_id: types.string(),
    processor_type: z._default(
      FinalizeInvoiceProcessorType$inboundSchema,
      "stripe",
    ),
    status: types.string(),
    total: types.number(),
    currency: types.string(),
    created_at: types.number(),
    hosted_invoice_url: z.optional(z.nullable(types.string())),
    id: types.string(),
    customer_id: types.nullable(types.string()),
    entity_id: types.nullable(types.string()),
    amount_paid: types.nullable(types.number()),
    refunded_amount: types.number(),
    items: types.optional(
      z.array(z.lazy(() => FinalizeInvoiceItem$inboundSchema)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "plan_ids": "planIds",
      "stripe_id": "stripeId",
      "processor_type": "processorType",
      "created_at": "createdAt",
      "hosted_invoice_url": "hostedInvoiceUrl",
      "customer_id": "customerId",
      "entity_id": "entityId",
      "amount_paid": "amountPaid",
      "refunded_amount": "refundedAmount",
    });
  }),
);

export function finalizeInvoiceInvoiceFromJSON(
  jsonString: string,
): SafeParseResult<FinalizeInvoiceInvoice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FinalizeInvoiceInvoice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FinalizeInvoiceInvoice' from JSON`,
  );
}

/** @internal */
export const FinalizeInvoiceResponse$inboundSchema: z.ZodMiniType<
  FinalizeInvoiceResponse,
  unknown
> = z.object({
  invoice: z.lazy(() => FinalizeInvoiceInvoice$inboundSchema),
});

export function finalizeInvoiceResponseFromJSON(
  jsonString: string,
): SafeParseResult<FinalizeInvoiceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FinalizeInvoiceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FinalizeInvoiceResponse' from JSON`,
  );
}
