/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type GetReferralProgramGlobals = {
  xApiVersion?: string | undefined;
};

export type GetReferralProgramParams = {
  /**
   * The ID of the referral program to fetch.
   */
  id: string;
};

/**
 * When the reward is granted: on redemption, or when the redeemer checks out.
 */
export const GetReferralProgramRedeemOn = {
  CustomerCreation: "customer_creation",
  Checkout: "checkout",
} as const;
/**
 * When the reward is granted: on redemption, or when the redeemer checks out.
 */
export type GetReferralProgramRedeemOn = OpenEnum<
  typeof GetReferralProgramRedeemOn
>;

/**
 * Who receives the reward: the referrer only, or both parties.
 */
export const GetReferralProgramReceivedBy = {
  Referrer: "referrer",
  All: "all",
} as const;
/**
 * Who receives the reward: the referrer only, or both parties.
 */
export type GetReferralProgramReceivedBy = OpenEnum<
  typeof GetReferralProgramReceivedBy
>;

/**
 * OK
 */
export type GetReferralProgramCreateReferralProgramResponse = {
  /**
   * The unique identifier for the referral program.
   */
  id: string;
  /**
   * The ID of the reward granted when a code is redeemed.
   */
  rewardId: string;
  /**
   * When the reward is granted: on redemption, or when the redeemer checks out.
   */
  redeemOn: GetReferralProgramRedeemOn;
  /**
   * Who receives the reward: the referrer only, or both parties.
   */
  receivedBy: GetReferralProgramReceivedBy;
  /**
   * The maximum number of times a referral code can be redeemed.
   */
  maxRedemptions?: number | null | undefined;
  /**
   * The plans whose checkout triggers the reward. Only used when redeem_on is checkout.
   */
  planIds?: Array<string> | null | undefined;
  /**
   * Whether checkouts that start a trial should skip granting the reward.
   */
  excludeTrial?: boolean | null | undefined;
  /**
   * The Unix timestamp (in milliseconds) when the referral program was created.
   */
  createdAt: number;
};

/** @internal */
export type GetReferralProgramParams$Outbound = {
  id: string;
};

/** @internal */
export const GetReferralProgramParams$outboundSchema: z.ZodMiniType<
  GetReferralProgramParams$Outbound,
  GetReferralProgramParams
> = z.object({
  id: z.string(),
});

export function getReferralProgramParamsToJSON(
  getReferralProgramParams: GetReferralProgramParams,
): string {
  return JSON.stringify(
    GetReferralProgramParams$outboundSchema.parse(getReferralProgramParams),
  );
}

/** @internal */
export const GetReferralProgramRedeemOn$inboundSchema: z.ZodMiniType<
  GetReferralProgramRedeemOn,
  unknown
> = openEnums.inboundSchema(GetReferralProgramRedeemOn);

/** @internal */
export const GetReferralProgramReceivedBy$inboundSchema: z.ZodMiniType<
  GetReferralProgramReceivedBy,
  unknown
> = openEnums.inboundSchema(GetReferralProgramReceivedBy);

/** @internal */
export const GetReferralProgramCreateReferralProgramResponse$inboundSchema:
  z.ZodMiniType<GetReferralProgramCreateReferralProgramResponse, unknown> = z
    .pipe(
      z.object({
        id: types.string(),
        reward_id: types.string(),
        redeem_on: GetReferralProgramRedeemOn$inboundSchema,
        received_by: GetReferralProgramReceivedBy$inboundSchema,
        max_redemptions: z.optional(z.nullable(types.number())),
        plan_ids: z.optional(z.nullable(z.array(types.string()))),
        exclude_trial: z.optional(z.nullable(types.boolean())),
        created_at: types.number(),
      }),
      z.transform((v) => {
        return remap$(v, {
          "reward_id": "rewardId",
          "redeem_on": "redeemOn",
          "received_by": "receivedBy",
          "max_redemptions": "maxRedemptions",
          "plan_ids": "planIds",
          "exclude_trial": "excludeTrial",
          "created_at": "createdAt",
        });
      }),
    );

export function getReferralProgramCreateReferralProgramResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetReferralProgramCreateReferralProgramResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetReferralProgramCreateReferralProgramResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetReferralProgramCreateReferralProgramResponse' from JSON`,
  );
}
