/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import {
  GetPlanBasePrice,
  GetPlanBasePrice$inboundSchema,
  GetPlanBillingControls,
  GetPlanBillingControls$inboundSchema,
  GetPlanConfig,
  GetPlanConfig$inboundSchema,
  GetPlanCustomerEligibility,
  GetPlanCustomerEligibility$inboundSchema,
  GetPlanEnv,
  GetPlanEnv$inboundSchema,
  GetPlanFreeTrial,
  GetPlanFreeTrial$inboundSchema,
  GetPlanFreeTrialParams,
  GetPlanFreeTrialParams$inboundSchema,
  GetPlanItem,
  GetPlanItem$inboundSchema,
  GetPlanPlanItem,
  GetPlanPlanItem$inboundSchema,
  GetPlanPlanItemFilter,
  GetPlanPlanItemFilter$inboundSchema,
  GetPlanPrice,
  GetPlanPrice$inboundSchema,
  GetPlanProcessors,
  GetPlanProcessors$inboundSchema,
  GetPlanVariantDetailsAutoTopup,
  GetPlanVariantDetailsAutoTopup$inboundSchema,
  GetPlanVariantDetailsSpendLimit,
  GetPlanVariantDetailsSpendLimit$inboundSchema,
  GetPlanVariantDetailsUsageAlert,
  GetPlanVariantDetailsUsageAlert$inboundSchema,
  GetPlanVariantDetailsUsageLimit,
  GetPlanVariantDetailsUsageLimit$inboundSchema,
} from "./get-plan-variant-details-usage-alert.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type GetPlanVariantDetailsOverageAllowed = {
  /**
   * The feature ID this overage allowed control applies to.
   */
  featureId: string;
  /**
   * Whether overage is allowed for this feature.
   */
  enabled: boolean;
};

/**
 * Override the plan's billing controls (auto top-ups, spend limits, usage limits, usage alerts, overage allowed) for this customer.
 */
export type GetPlanVariantDetailsBillingControls = {
  /**
   * List of auto top-up configurations per feature.
   */
  autoTopups?: Array<GetPlanVariantDetailsAutoTopup> | undefined;
  /**
   * List of overage spend limits per feature (caps overage spend).
   */
  spendLimits?: Array<GetPlanVariantDetailsSpendLimit> | undefined;
  /**
   * List of hard usage caps per feature (max units per interval).
   */
  usageLimits?: Array<GetPlanVariantDetailsUsageLimit> | undefined;
  /**
   * List of usage alert configurations per feature.
   */
  usageAlerts?: Array<GetPlanVariantDetailsUsageAlert> | undefined;
  /**
   * List of overage allowed controls per feature. When enabled, usage can exceed balance.
   */
  overageAllowed?: Array<GetPlanVariantDetailsOverageAllowed> | undefined;
};

/**
 * Billing interval (e.g. 'month', 'year').
 */
export const GetPlanPriceUpsertLicenseInterval = {
  OneOff: "one_off",
  Week: "week",
  Month: "month",
  Quarter: "quarter",
  SemiAnnual: "semi_annual",
  Year: "year",
} as const;
/**
 * Billing interval (e.g. 'month', 'year').
 */
export type GetPlanPriceUpsertLicenseInterval = OpenEnum<
  typeof GetPlanPriceUpsertLicenseInterval
>;

export type GetPlanUpsertLicenseAdditionalCurrency = {
  /**
   * Three-letter Stripe-supported currency code (e.g. 'eur', 'gbp').
   */
  currency: string;
  /**
   * Price amount in this currency. Set explicitly per currency, not converted from the base amount.
   */
  amount: number;
};

/**
 * Base price configuration for a plan.
 */
export type GetPlanUpsertLicenseBasePrice = {
  /**
   * Base price amount for the plan, in major currency units (e.g. dollars).
   */
  amount: number;
  /**
   * Billing interval (e.g. 'month', 'year').
   */
  interval: GetPlanPriceUpsertLicenseInterval;
  /**
   * Number of intervals per billing cycle. Defaults to 1.
   */
  intervalCount: number;
  /**
   * Base price amounts in additional currencies. The base 'amount' is in the org's default currency.
   */
  additionalCurrencies?:
    | Array<GetPlanUpsertLicenseAdditionalCurrency>
    | undefined;
};

export type GetPlanUpsertLicenseThresholdBilling = {
  threshold: number;
};

/**
 * Interval at which balance resets (e.g. 'month', 'year'). For consumable features only.
 */
export const GetPlanUpsertLicenseResetInterval = {
  OneOff: "one_off",
  Minute: "minute",
  Hour: "hour",
  Day: "day",
  Week: "week",
  Month: "month",
  Quarter: "quarter",
  SemiAnnual: "semi_annual",
  Year: "year",
} as const;
/**
 * Interval at which balance resets (e.g. 'month', 'year'). For consumable features only.
 */
export type GetPlanUpsertLicenseResetInterval = OpenEnum<
  typeof GetPlanUpsertLicenseResetInterval
>;

/**
 * Reset configuration for consumable features. Omit for non-consumable features like seats.
 */
export type GetPlanUpsertLicenseReset = {
  /**
   * Interval at which balance resets (e.g. 'month', 'year'). For consumable features only.
   */
  interval: GetPlanUpsertLicenseResetInterval;
  /**
   * Number of intervals between resets. Defaults to 1.
   */
  intervalCount: number;
};

export type GetPlanUpsertLicenseAddItemAdditionalCurrency = {
  /**
   * Three-letter Stripe-supported currency code (e.g. 'eur', 'gbp').
   */
  currency: string;
  /**
   * Price amount in this currency. Set explicitly per currency, not converted from the base amount.
   */
  amount: number;
};

export type GetPlanUpsertLicensePriceTo = number | string;

export type GetPlanUpsertLicenseTierAdditionalCurrency = {
  /**
   * Three-letter Stripe-supported currency code (e.g. 'eur', 'gbp').
   */
  currency: string;
  /**
   * Per-unit amount for this tier in this currency.
   */
  amount?: number | undefined;
  /**
   * Flat amount for this tier in this currency, if the tier uses one.
   */
  flatAmount?: number | undefined;
};

export type GetPlanUpsertLicensePriceTier = {
  to: number | string;
  amount: number;
  flatAmount?: number | undefined;
  additionalCurrencies?:
    | Array<GetPlanUpsertLicenseTierAdditionalCurrency>
    | undefined;
};

export const GetPlanUpsertLicenseTierBehavior = {
  Graduated: "graduated",
  Volume: "volume",
} as const;
export type GetPlanUpsertLicenseTierBehavior = OpenEnum<
  typeof GetPlanUpsertLicenseTierBehavior
>;

/**
 * Billing interval. For consumable features, should match reset.interval.
 */
export const GetPlanUpsertLicenseAddItemPriceInterval = {
  OneOff: "one_off",
  Week: "week",
  Month: "month",
  Quarter: "quarter",
  SemiAnnual: "semi_annual",
  Year: "year",
} as const;
/**
 * Billing interval. For consumable features, should match reset.interval.
 */
export type GetPlanUpsertLicenseAddItemPriceInterval = OpenEnum<
  typeof GetPlanUpsertLicenseAddItemPriceInterval
>;

/**
 * 'prepaid' for upfront payment (seats), 'usage_based' for pay-as-you-go.
 */
export const GetPlanUpsertLicenseAddItemBillingMethod = {
  Prepaid: "prepaid",
  UsageBased: "usage_based",
} as const;
/**
 * 'prepaid' for upfront payment (seats), 'usage_based' for pay-as-you-go.
 */
export type GetPlanUpsertLicenseAddItemBillingMethod = OpenEnum<
  typeof GetPlanUpsertLicenseAddItemBillingMethod
>;

/**
 * Pricing for usage beyond included units. Omit for free features.
 */
export type GetPlanUpsertLicensePrice = {
  /**
   * Price per billing_units after included usage. Either 'amount' or 'tiers' is required.
   */
  amount?: number | undefined;
  /**
   * Amounts in additional currencies for this flat price. The base 'amount' is in the org's default currency. Only valid with 'amount', not 'tiers'.
   */
  additionalCurrencies?:
    | Array<GetPlanUpsertLicenseAddItemAdditionalCurrency>
    | undefined;
  /**
   * Tiered pricing.  Either 'amount' or 'tiers' is required.
   */
  tiers?: Array<GetPlanUpsertLicensePriceTier> | undefined;
  tierBehavior?: GetPlanUpsertLicenseTierBehavior | undefined;
  /**
   * Billing interval. For consumable features, should match reset.interval.
   */
  interval: GetPlanUpsertLicenseAddItemPriceInterval;
  /**
   * Number of intervals per billing cycle. Defaults to 1.
   */
  intervalCount: number;
  /**
   * Units per price increment. Usage is rounded UP when billed (e.g. billing_units=100 means 101 rounds to 200).
   */
  billingUnits: number;
  /**
   * 'prepaid' for upfront payment (seats), 'usage_based' for pay-as-you-go.
   */
  billingMethod: GetPlanUpsertLicenseAddItemBillingMethod;
  /**
   * Max units purchasable beyond included. E.g. included=100, max_purchase=300 allows 400 total. Null for no limit.
   */
  maxPurchase?: number | null | undefined;
};

/**
 * Billing behavior when quantity increases mid-cycle.
 */
export const GetPlanUpsertLicenseOnIncrease = {
  BillImmediately: "bill_immediately",
  ProrateImmediately: "prorate_immediately",
  ProrateNextCycle: "prorate_next_cycle",
  BillNextCycle: "bill_next_cycle",
} as const;
/**
 * Billing behavior when quantity increases mid-cycle.
 */
export type GetPlanUpsertLicenseOnIncrease = OpenEnum<
  typeof GetPlanUpsertLicenseOnIncrease
>;

/**
 * Credit behavior when quantity decreases mid-cycle.
 */
export const GetPlanUpsertLicenseOnDecrease = {
  Prorate: "prorate",
  ProrateImmediately: "prorate_immediately",
  ProrateNextCycle: "prorate_next_cycle",
  None: "none",
  NoProrations: "no_prorations",
} as const;
/**
 * Credit behavior when quantity decreases mid-cycle.
 */
export type GetPlanUpsertLicenseOnDecrease = OpenEnum<
  typeof GetPlanUpsertLicenseOnDecrease
>;

/**
 * Proration settings for prepaid features. Controls mid-cycle quantity change billing.
 */
export type GetPlanUpsertLicenseProration = {
  /**
   * Billing behavior when quantity increases mid-cycle.
   */
  onIncrease: GetPlanUpsertLicenseOnIncrease;
  /**
   * Credit behavior when quantity decreases mid-cycle.
   */
  onDecrease: GetPlanUpsertLicenseOnDecrease;
};

/**
 * When rolled over units expire.
 */
export const GetPlanUpsertLicenseExpiryDurationType = {
  Month: "month",
  Forever: "forever",
} as const;
/**
 * When rolled over units expire.
 */
export type GetPlanUpsertLicenseExpiryDurationType = OpenEnum<
  typeof GetPlanUpsertLicenseExpiryDurationType
>;

/**
 * Rollover config for unused units. If set, unused included units carry over.
 */
export type GetPlanUpsertLicenseRollover = {
  /**
   * Max rollover units. Omit for unlimited rollover.
   */
  max?: number | undefined;
  /**
   * Maximum rollover as a percentage (0-100) of included + prepaid grant. Mutually exclusive with max.
   */
  maxPercentage?: number | undefined;
  /**
   * When rolled over units expire.
   */
  expiryDurationType: GetPlanUpsertLicenseExpiryDurationType;
  /**
   * Number of periods before expiry.
   */
  expiryDurationLength?: number | undefined;
};

export const GetPlanUpsertLicenseDuration = {
  Day: "day",
  Week: "week",
  Month: "month",
  Year: "year",
} as const;
export type GetPlanUpsertLicenseDuration = OpenEnum<
  typeof GetPlanUpsertLicenseDuration
>;

/**
 * Purchased units expire this long after each purchase. One-off prepaid consumable items only.
 */
export type GetPlanUpsertLicenseExpiry = {
  duration: GetPlanUpsertLicenseDuration;
  length: number;
};

export type GetPlanDimensionsUpsertLicense4 = {
  /**
   * Event properties this entry applies to. Every key must equal the tracked property, compared as strings.
   */
  match: { [k: string]: string };
  /**
   * Breaks ties between dimensions that match the same number of keys. Higher wins.
   */
  priority?: number | undefined;
  /**
   * Credits consumed per billing-unit group when this dimension matches.
   */
  creditCost: number;
};

export const GetPlanDimensionsToUpsertLicenseEnum2 = {
  Inf: "inf",
} as const;
export type GetPlanDimensionsToUpsertLicenseEnum2 = ClosedEnum<
  typeof GetPlanDimensionsToUpsertLicenseEnum2
>;

/**
 * Inclusive upper usage boundary for this graduated tier. The final tier must be 'inf'.
 */
export type GetPlanDimensionsUpsertLicenseToUnion2 =
  | number
  | GetPlanDimensionsToUpsertLicenseEnum2;

export type GetPlanDimensionsUpsertLicenseTier2 = {
  /**
   * Inclusive upper usage boundary for this graduated tier. The final tier must be 'inf'.
   */
  to: number | GetPlanDimensionsToUpsertLicenseEnum2;
  /**
   * Credits consumed per billing-unit group within this tier.
   */
  creditCost: number;
};

export type GetPlanDimensionsUpsertLicense3 = {
  /**
   * Event properties this entry applies to. Every key must equal the tracked property, compared as strings.
   */
  match: { [k: string]: string };
  /**
   * Breaks ties between dimensions that match the same number of keys. Higher wins.
   */
  priority?: number | undefined;
  tierBehavior: "graduated";
  tiers: Array<GetPlanDimensionsUpsertLicenseTier2>;
};

export type GetPlanUpsertLicenseDimensionsUnion2 =
  | GetPlanDimensionsUpsertLicense3
  | GetPlanDimensionsUpsertLicense4;

export type GetPlanUpsertLicenseMultipliers2 = {
  /**
   * Event properties this entry applies to. Every key must equal the tracked property, compared as strings.
   */
  match: { [k: string]: string };
  /**
   * Multiplies the matched rate. All matching multipliers stack.
   */
  factor?: number | undefined;
  /**
   * Added to the rate after every factor is applied, in credits per billing-unit group.
   */
  add?: number | undefined;
};

export type GetPlanCreditSchemaUpsertLicense2 = {
  /**
   * ID of the metered feature that draws from this credit system.
   */
  meteredFeatureId: string;
  /**
   * Number of metered-feature units priced together. Defaults to one when omitted.
   */
  billingUnits?: number | undefined;
  /**
   * Named rates chosen by event properties. The most specific match sets the rate; with no match the item's own rate applies.
   */
  dimensions?: {
    [k: string]:
      | GetPlanDimensionsUpsertLicense3
      | GetPlanDimensionsUpsertLicense4;
  } | undefined;
  /**
   * Named adjustments chosen by event properties. Every match applies: factors multiply, then adds are summed.
   */
  multipliers?: { [k: string]: GetPlanUpsertLicenseMultipliers2 } | undefined;
  /**
   * Credits consumed per billing-unit group.
   */
  creditCost: number;
};

export type GetPlanDimensionsUpsertLicense2 = {
  /**
   * Event properties this entry applies to. Every key must equal the tracked property, compared as strings.
   */
  match: { [k: string]: string };
  /**
   * Breaks ties between dimensions that match the same number of keys. Higher wins.
   */
  priority?: number | undefined;
  /**
   * Credits consumed per billing-unit group when this dimension matches.
   */
  creditCost: number;
};

export const GetPlanDimensionsToUpsertLicenseEnum1 = {
  Inf: "inf",
} as const;
export type GetPlanDimensionsToUpsertLicenseEnum1 = ClosedEnum<
  typeof GetPlanDimensionsToUpsertLicenseEnum1
>;

/**
 * Inclusive upper usage boundary for this graduated tier. The final tier must be 'inf'.
 */
export type GetPlanDimensionsUpsertLicenseToUnion1 =
  | number
  | GetPlanDimensionsToUpsertLicenseEnum1;

export type GetPlanDimensionsUpsertLicenseTier1 = {
  /**
   * Inclusive upper usage boundary for this graduated tier. The final tier must be 'inf'.
   */
  to: number | GetPlanDimensionsToUpsertLicenseEnum1;
  /**
   * Credits consumed per billing-unit group within this tier.
   */
  creditCost: number;
};

export type GetPlanDimensionsUpsertLicense1 = {
  /**
   * Event properties this entry applies to. Every key must equal the tracked property, compared as strings.
   */
  match: { [k: string]: string };
  /**
   * Breaks ties between dimensions that match the same number of keys. Higher wins.
   */
  priority?: number | undefined;
  tierBehavior: "graduated";
  tiers: Array<GetPlanDimensionsUpsertLicenseTier1>;
};

export type GetPlanUpsertLicenseDimensionsUnion1 =
  | GetPlanDimensionsUpsertLicense1
  | GetPlanDimensionsUpsertLicense2;

export type GetPlanUpsertLicenseMultipliers1 = {
  /**
   * Event properties this entry applies to. Every key must equal the tracked property, compared as strings.
   */
  match: { [k: string]: string };
  /**
   * Multiplies the matched rate. All matching multipliers stack.
   */
  factor?: number | undefined;
  /**
   * Added to the rate after every factor is applied, in credits per billing-unit group.
   */
  add?: number | undefined;
};

export const GetPlanToUpsertLicenseEnum = {
  Inf: "inf",
} as const;
export type GetPlanToUpsertLicenseEnum = ClosedEnum<
  typeof GetPlanToUpsertLicenseEnum
>;

/**
 * Inclusive upper usage boundary for this graduated tier. The final tier must be 'inf'.
 */
export type GetPlanUpsertLicenseFeatureOverrideToUnion =
  | number
  | GetPlanToUpsertLicenseEnum;

export type GetPlanUpsertLicenseFeatureOverrideTier = {
  /**
   * Inclusive upper usage boundary for this graduated tier. The final tier must be 'inf'.
   */
  to: number | GetPlanToUpsertLicenseEnum;
  /**
   * Credits consumed per billing-unit group within this tier.
   */
  creditCost: number;
};

export type GetPlanCreditSchemaUpsertLicense1 = {
  /**
   * ID of the metered feature that draws from this credit system.
   */
  meteredFeatureId: string;
  /**
   * Number of metered-feature units priced together. Defaults to one when omitted.
   */
  billingUnits?: number | undefined;
  /**
   * Named rates chosen by event properties. The most specific match sets the rate; with no match the item's own rate applies.
   */
  dimensions?: {
    [k: string]:
      | GetPlanDimensionsUpsertLicense1
      | GetPlanDimensionsUpsertLicense2;
  } | undefined;
  /**
   * Named adjustments chosen by event properties. Every match applies: factors multiply, then adds are summed.
   */
  multipliers?: { [k: string]: GetPlanUpsertLicenseMultipliers1 } | undefined;
  tierBehavior: "graduated";
  tiers: Array<GetPlanUpsertLicenseFeatureOverrideTier>;
};

export type GetPlanUpsertLicenseCreditSchemaUnion =
  | GetPlanCreditSchemaUpsertLicense1
  | GetPlanCreditSchemaUpsertLicense2;

export type GetPlanUpsertLicenseProviderMarkups = {
  markup: number;
};

export type GetPlanUpsertLicenseModelMarkups = {
  markup?: number | undefined;
  inputCost?: number | undefined;
  outputCost?: number | undefined;
};

/**
 * For AI credit system features: replaces the feature's markup chain entirely for customers on this plan. An unset level means no markup at that level rather than inheriting the feature's.
 */
export type GetPlanUpsertLicenseMarkups = {
  /**
   * Default percentage markup for customers on this plan. Use -100 to make usage free.
   */
  defaultMarkup?: number | undefined;
  /**
   * Per-provider markup percentages for customers on this plan.
   */
  providerMarkups?:
    | { [k: string]: GetPlanUpsertLicenseProviderMarkups }
    | null
    | undefined;
  /**
   * Per-model markup overrides for customers on this plan.
   */
  modelMarkups?:
    | { [k: string]: GetPlanUpsertLicenseModelMarkups }
    | null
    | undefined;
};

/**
 * Overrides fields of this item's feature for customers on this plan (e.g. a credit system's credit_schema).
 */
export type GetPlanUpsertLicenseFeatureOverride = {
  /**
   * For credit system features: replaces the feature's credit_schema entirely for customers on this plan.
   */
  creditSchema?:
    | Array<
      GetPlanCreditSchemaUpsertLicense1 | GetPlanCreditSchemaUpsertLicense2
    >
    | undefined;
  /**
   * For AI credit system features: replaces the feature's markup chain entirely for customers on this plan. An unset level means no markup at that level rather than inheriting the feature's.
   */
  markups?: GetPlanUpsertLicenseMarkups | undefined;
};

/**
 * Configuration for a feature item in a plan, including usage limits, pricing, and rollover settings.
 */
export type GetPlanUpsertLicensePlanItem = {
  /**
   * Bills this many feature units when outstanding overage reaches it.
   */
  thresholdBilling?: GetPlanUpsertLicenseThresholdBilling | null | undefined;
  /**
   * The ID of the feature to configure.
   */
  featureId: string;
  /**
   * Number of free units included. Balance resets to this each interval for consumable features.
   */
  included?: number | undefined;
  /**
   * If true, customer has unlimited access to this feature.
   */
  unlimited?: boolean | undefined;
  /**
   * Whether entity-level grants contribute to a shared customer balance.
   */
  pooled: boolean;
  /**
   * Reset configuration for consumable features. Omit for non-consumable features like seats.
   */
  reset?: GetPlanUpsertLicenseReset | undefined;
  /**
   * Pricing for usage beyond included units. Omit for free features.
   */
  price?: GetPlanUpsertLicensePrice | undefined;
  /**
   * Proration settings for prepaid features. Controls mid-cycle quantity change billing.
   */
  proration?: GetPlanUpsertLicenseProration | undefined;
  /**
   * Rollover config for unused units. If set, unused included units carry over.
   */
  rollover?: GetPlanUpsertLicenseRollover | undefined;
  /**
   * Purchased units expire this long after each purchase. One-off prepaid consumable items only.
   */
  expiry?: GetPlanUpsertLicenseExpiry | undefined;
  /**
   * Overrides fields of this item's feature for customers on this plan (e.g. a credit system's credit_schema).
   */
  featureOverride?: GetPlanUpsertLicenseFeatureOverride | undefined;
};

/**
 * Match items with this billing method (prepaid or usage_based).
 */
export const GetPlanUpsertLicenseRemoveItemBillingMethod = {
  Prepaid: "prepaid",
  UsageBased: "usage_based",
} as const;
/**
 * Match items with this billing method (prepaid or usage_based).
 */
export type GetPlanUpsertLicenseRemoveItemBillingMethod = OpenEnum<
  typeof GetPlanUpsertLicenseRemoveItemBillingMethod
>;

export const GetPlanIntervalUpsertLicenseRemoveItemEnum2 = {
  OneOff: "one_off",
  Minute: "minute",
  Hour: "hour",
  Day: "day",
  Week: "week",
  Month: "month",
  Quarter: "quarter",
  SemiAnnual: "semi_annual",
  Year: "year",
} as const;
export type GetPlanIntervalUpsertLicenseRemoveItemEnum2 = OpenEnum<
  typeof GetPlanIntervalUpsertLicenseRemoveItemEnum2
>;

export const GetPlanIntervalUpsertLicenseRemoveItemEnum1 = {
  OneOff: "one_off",
  Week: "week",
  Month: "month",
  Quarter: "quarter",
  SemiAnnual: "semi_annual",
  Year: "year",
} as const;
export type GetPlanIntervalUpsertLicenseRemoveItemEnum1 = OpenEnum<
  typeof GetPlanIntervalUpsertLicenseRemoveItemEnum1
>;

/**
 * Match items with this interval. Accepts either a BillingInterval (price-side) or a ResetInterval (reset-side, includes day/hour/minute) so price-less items keyed by reset.interval can be disambiguated.
 */
export type GetPlanUpsertLicenseIntervalUnion =
  | GetPlanIntervalUpsertLicenseRemoveItemEnum1
  | GetPlanIntervalUpsertLicenseRemoveItemEnum2;

/**
 * Filter for matching plan items. All provided fields must match (AND).
 */
export type GetPlanUpsertLicensePlanItemFilter = {
  /**
   * Match items linked to this feature.
   */
  featureId?: string | undefined;
  /**
   * Match items with this billing method (prepaid or usage_based).
   */
  billingMethod?: GetPlanUpsertLicenseRemoveItemBillingMethod | undefined;
  /**
   * Match items with this interval. Accepts either a BillingInterval (price-side) or a ResetInterval (reset-side, includes day/hour/minute) so price-less items keyed by reset.interval can be disambiguated.
   */
  interval?:
    | GetPlanIntervalUpsertLicenseRemoveItemEnum1
    | GetPlanIntervalUpsertLicenseRemoveItemEnum2
    | undefined;
  /**
   * Match items with this interval_count. Disambiguates between items that share an interval but differ in count.
   */
  intervalCount?: number | undefined;
  /**
   * Match items whose grant equals this included usage. Omitted is a wildcard.
   */
  included?: number | undefined;
};

export type GetPlanUpsertLicenseCustomize = {
  price?: GetPlanUpsertLicenseBasePrice | null | undefined;
  addItems?: Array<GetPlanUpsertLicensePlanItem> | undefined;
  removeItems?: Array<GetPlanUpsertLicensePlanItemFilter> | undefined;
};

export type GetPlanUpsertLicense = {
  licensePlanId: string;
  versionSlug?: string | undefined;
  included?: number | undefined;
  prepaidOnly?: boolean | undefined;
  customize?: GetPlanUpsertLicenseCustomize | null | undefined;
  metadata?: { [k: string]: any } | undefined;
};

export type GetPlanRemoveLicense = {
  licensePlanId: string;
};

/**
 * The customization that transforms the base plan into this variant.
 */
export type GetPlanCustomize = {
  /**
   * Override the base price of the plan. Pass null to remove the base price.
   */
  price?: GetPlanBasePrice | null | undefined;
  /**
   * Items to add to the plan.
   */
  addItems?: Array<GetPlanPlanItem> | undefined;
  /**
   * Filters selecting items to remove from the plan.
   */
  removeItems?: Array<GetPlanPlanItemFilter> | undefined;
  /**
   * Override the plan's default free trial. Pass an object to set a custom trial, or null to remove the trial entirely.
   */
  freeTrial?: GetPlanFreeTrialParams | null | undefined;
  /**
   * Override the plan's billing controls (auto top-ups, spend limits, usage limits, usage alerts, overage allowed) for this customer.
   */
  billingControls?: GetPlanVariantDetailsBillingControls | undefined;
  /**
   * License links to add or override for this customer, keyed by license_plan_id. Omitted fields inherit the plan catalog link (included defaults to 1 when the license is not in the catalog). A bare entry restores the license to pure catalog inheritance.
   */
  upsertLicenses?: Array<GetPlanUpsertLicense> | undefined;
  /**
   * License links to drop, keyed by license_plan_id. Parallel to remove_items.
   */
  removeLicenses?: Array<GetPlanRemoveLicense> | undefined;
};

/**
 * Details about how this variant relates to its latest base plan.
 */
export type GetPlanVariantDetails = {
  /**
   * The ID of the base plan this variant was derived from.
   */
  basePlanId: string;
  /**
   * The customization that transforms the base plan into this variant.
   */
  customize?: GetPlanCustomize | undefined;
};

/**
 * A plan defines a set of features, pricing, and entitlements that can be attached to customers.
 */
export type GetPlanResponse = {
  /**
   * Unique identifier for the plan.
   */
  id: string;
  /**
   * Display name of the plan.
   */
  name: string;
  /**
   * Optional description of the plan.
   */
  description: string | null;
  /**
   * Group identifier for organizing related plans. Plans in the same group are mutually exclusive.
   */
  group: string | null;
  /**
   * Version number of the plan. Incremented when plan configuration changes.
   */
  version: number;
  /**
   * User-facing version identity. Defaults to v{n} when the version is minted.
   */
  versionSlug?: string | null | undefined;
  /**
   * Whether this is the active version of the plan. At most one version is active.
   */
  active?: boolean | undefined;
  /**
   * Whether this is an add-on plan that can be attached alongside a main plan.
   */
  addOn: boolean;
  /**
   * If true, this plan is automatically attached when a customer is created. Used for free plans.
   */
  autoEnable: boolean;
  /**
   * Base recurring price for the plan. Null for free plans or usage-only plans.
   */
  price: GetPlanPrice | null;
  /**
   * Feature configurations included in this plan. Each item defines included units, pricing, and reset behavior for a feature.
   */
  items: Array<GetPlanItem>;
  /**
   * Payment processors this plan is connected to. Omitted when unset.
   */
  processors?: GetPlanProcessors | undefined;
  /**
   * Free trial configuration. If set, new customers can try this plan before being charged.
   */
  freeTrial?: GetPlanFreeTrial | undefined;
  /**
   * Unix timestamp (ms) when the plan was created.
   */
  createdAt: number;
  /**
   * Environment this plan belongs to ('sandbox' or 'live').
   */
  env: GetPlanEnv;
  /**
   * Whether the plan is archived. Archived plans cannot be attached to new customers.
   */
  archived: boolean;
  /**
   * Miscellaneous plan-level configuration flags.
   */
  config: GetPlanConfig;
  /**
   * Plan-level billing controls used as customer defaults.
   */
  billingControls?: GetPlanBillingControls | undefined;
  /**
   * Arbitrary key-value metadata defined by you for your own use. Shared across all versions of the plan.
   */
  metadata: { [k: string]: any };
  customerEligibility?: GetPlanCustomerEligibility | undefined;
  /**
   * Deprecated. Use variant_details.base_plan_id instead. If this is a variant, the ID of the base plan it was created from.
   */
  baseVariantId: string | null;
  /**
   * Details about how this variant relates to its latest base plan.
   */
  variantDetails?: GetPlanVariantDetails | undefined;
};

/** @internal */
export const GetPlanVariantDetailsOverageAllowed$inboundSchema: z.ZodMiniType<
  GetPlanVariantDetailsOverageAllowed,
  unknown
> = z.pipe(
  z.object({
    feature_id: types.string(),
    enabled: z._default(types.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      "feature_id": "featureId",
    });
  }),
);

export function getPlanVariantDetailsOverageAllowedFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanVariantDetailsOverageAllowed, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanVariantDetailsOverageAllowed$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanVariantDetailsOverageAllowed' from JSON`,
  );
}

/** @internal */
export const GetPlanVariantDetailsBillingControls$inboundSchema: z.ZodMiniType<
  GetPlanVariantDetailsBillingControls,
  unknown
> = z.pipe(
  z.object({
    auto_topups: types.optional(
      z.array(GetPlanVariantDetailsAutoTopup$inboundSchema),
    ),
    spend_limits: types.optional(
      z.array(GetPlanVariantDetailsSpendLimit$inboundSchema),
    ),
    usage_limits: types.optional(
      z.array(GetPlanVariantDetailsUsageLimit$inboundSchema),
    ),
    usage_alerts: types.optional(
      z.array(GetPlanVariantDetailsUsageAlert$inboundSchema),
    ),
    overage_allowed: types.optional(
      z.array(z.lazy(() => GetPlanVariantDetailsOverageAllowed$inboundSchema)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "auto_topups": "autoTopups",
      "spend_limits": "spendLimits",
      "usage_limits": "usageLimits",
      "usage_alerts": "usageAlerts",
      "overage_allowed": "overageAllowed",
    });
  }),
);

export function getPlanVariantDetailsBillingControlsFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanVariantDetailsBillingControls, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanVariantDetailsBillingControls$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanVariantDetailsBillingControls' from JSON`,
  );
}

/** @internal */
export const GetPlanPriceUpsertLicenseInterval$inboundSchema: z.ZodMiniType<
  GetPlanPriceUpsertLicenseInterval,
  unknown
> = openEnums.inboundSchema(GetPlanPriceUpsertLicenseInterval);

/** @internal */
export const GetPlanUpsertLicenseAdditionalCurrency$inboundSchema:
  z.ZodMiniType<GetPlanUpsertLicenseAdditionalCurrency, unknown> = z.object({
    currency: types.string(),
    amount: types.number(),
  });

export function getPlanUpsertLicenseAdditionalCurrencyFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseAdditionalCurrency, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanUpsertLicenseAdditionalCurrency$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseAdditionalCurrency' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseBasePrice$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseBasePrice,
  unknown
> = z.pipe(
  z.object({
    amount: types.number(),
    interval: GetPlanPriceUpsertLicenseInterval$inboundSchema,
    interval_count: z._default(types.number(), 1),
    additional_currencies: types.optional(
      z.array(
        z.lazy(() => GetPlanUpsertLicenseAdditionalCurrency$inboundSchema),
      ),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "interval_count": "intervalCount",
      "additional_currencies": "additionalCurrencies",
    });
  }),
);

export function getPlanUpsertLicenseBasePriceFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseBasePrice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanUpsertLicenseBasePrice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseBasePrice' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseThresholdBilling$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseThresholdBilling,
  unknown
> = z.object({
  threshold: types.number(),
});

export function getPlanUpsertLicenseThresholdBillingFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseThresholdBilling, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanUpsertLicenseThresholdBilling$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseThresholdBilling' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseResetInterval$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseResetInterval,
  unknown
> = openEnums.inboundSchema(GetPlanUpsertLicenseResetInterval);

/** @internal */
export const GetPlanUpsertLicenseReset$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseReset,
  unknown
> = z.pipe(
  z.object({
    interval: GetPlanUpsertLicenseResetInterval$inboundSchema,
    interval_count: z._default(types.number(), 1),
  }),
  z.transform((v) => {
    return remap$(v, {
      "interval_count": "intervalCount",
    });
  }),
);

export function getPlanUpsertLicenseResetFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseReset, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanUpsertLicenseReset$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseReset' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseAddItemAdditionalCurrency$inboundSchema:
  z.ZodMiniType<GetPlanUpsertLicenseAddItemAdditionalCurrency, unknown> = z
    .object({
      currency: types.string(),
      amount: types.number(),
    });

export function getPlanUpsertLicenseAddItemAdditionalCurrencyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetPlanUpsertLicenseAddItemAdditionalCurrency,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanUpsertLicenseAddItemAdditionalCurrency$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetPlanUpsertLicenseAddItemAdditionalCurrency' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicensePriceTo$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicensePriceTo,
  unknown
> = smartUnion([types.number(), types.string()]);

export function getPlanUpsertLicensePriceToFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicensePriceTo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanUpsertLicensePriceTo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicensePriceTo' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseTierAdditionalCurrency$inboundSchema:
  z.ZodMiniType<GetPlanUpsertLicenseTierAdditionalCurrency, unknown> = z.pipe(
    z.object({
      currency: types.string(),
      amount: types.optional(types.number()),
      flat_amount: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "flat_amount": "flatAmount",
      });
    }),
  );

export function getPlanUpsertLicenseTierAdditionalCurrencyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetPlanUpsertLicenseTierAdditionalCurrency,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanUpsertLicenseTierAdditionalCurrency$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetPlanUpsertLicenseTierAdditionalCurrency' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicensePriceTier$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicensePriceTier,
  unknown
> = z.pipe(
  z.object({
    to: smartUnion([types.number(), types.string()]),
    amount: types.number(),
    flat_amount: types.optional(types.number()),
    additional_currencies: types.optional(z.array(z.lazy(() =>
      GetPlanUpsertLicenseTierAdditionalCurrency$inboundSchema
    ))),
  }),
  z.transform((v) => {
    return remap$(v, {
      "flat_amount": "flatAmount",
      "additional_currencies": "additionalCurrencies",
    });
  }),
);

export function getPlanUpsertLicensePriceTierFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicensePriceTier, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanUpsertLicensePriceTier$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicensePriceTier' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseTierBehavior$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseTierBehavior,
  unknown
> = openEnums.inboundSchema(GetPlanUpsertLicenseTierBehavior);

/** @internal */
export const GetPlanUpsertLicenseAddItemPriceInterval$inboundSchema:
  z.ZodMiniType<GetPlanUpsertLicenseAddItemPriceInterval, unknown> = openEnums
    .inboundSchema(GetPlanUpsertLicenseAddItemPriceInterval);

/** @internal */
export const GetPlanUpsertLicenseAddItemBillingMethod$inboundSchema:
  z.ZodMiniType<GetPlanUpsertLicenseAddItemBillingMethod, unknown> = openEnums
    .inboundSchema(GetPlanUpsertLicenseAddItemBillingMethod);

/** @internal */
export const GetPlanUpsertLicensePrice$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicensePrice,
  unknown
> = z.pipe(
  z.object({
    amount: types.optional(types.number()),
    additional_currencies: types.optional(z.array(z.lazy(() =>
      GetPlanUpsertLicenseAddItemAdditionalCurrency$inboundSchema
    ))),
    tiers: types.optional(z.array(z.lazy(() =>
      GetPlanUpsertLicensePriceTier$inboundSchema
    ))),
    tier_behavior: types.optional(
      GetPlanUpsertLicenseTierBehavior$inboundSchema,
    ),
    interval: GetPlanUpsertLicenseAddItemPriceInterval$inboundSchema,
    interval_count: z._default(types.number(), 1),
    billing_units: z._default(types.number(), 1),
    billing_method: GetPlanUpsertLicenseAddItemBillingMethod$inboundSchema,
    max_purchase: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "additional_currencies": "additionalCurrencies",
      "tier_behavior": "tierBehavior",
      "interval_count": "intervalCount",
      "billing_units": "billingUnits",
      "billing_method": "billingMethod",
      "max_purchase": "maxPurchase",
    });
  }),
);

export function getPlanUpsertLicensePriceFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicensePrice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanUpsertLicensePrice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicensePrice' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseOnIncrease$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseOnIncrease,
  unknown
> = openEnums.inboundSchema(GetPlanUpsertLicenseOnIncrease);

/** @internal */
export const GetPlanUpsertLicenseOnDecrease$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseOnDecrease,
  unknown
> = openEnums.inboundSchema(GetPlanUpsertLicenseOnDecrease);

/** @internal */
export const GetPlanUpsertLicenseProration$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseProration,
  unknown
> = z.pipe(
  z.object({
    on_increase: GetPlanUpsertLicenseOnIncrease$inboundSchema,
    on_decrease: GetPlanUpsertLicenseOnDecrease$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "on_increase": "onIncrease",
      "on_decrease": "onDecrease",
    });
  }),
);

export function getPlanUpsertLicenseProrationFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseProration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanUpsertLicenseProration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseProration' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseExpiryDurationType$inboundSchema:
  z.ZodMiniType<GetPlanUpsertLicenseExpiryDurationType, unknown> = openEnums
    .inboundSchema(GetPlanUpsertLicenseExpiryDurationType);

/** @internal */
export const GetPlanUpsertLicenseRollover$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseRollover,
  unknown
> = z.pipe(
  z.object({
    max: types.optional(types.number()),
    max_percentage: types.optional(types.number()),
    expiry_duration_type: GetPlanUpsertLicenseExpiryDurationType$inboundSchema,
    expiry_duration_length: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "max_percentage": "maxPercentage",
      "expiry_duration_type": "expiryDurationType",
      "expiry_duration_length": "expiryDurationLength",
    });
  }),
);

export function getPlanUpsertLicenseRolloverFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseRollover, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanUpsertLicenseRollover$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseRollover' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseDuration$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseDuration,
  unknown
> = openEnums.inboundSchema(GetPlanUpsertLicenseDuration);

/** @internal */
export const GetPlanUpsertLicenseExpiry$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseExpiry,
  unknown
> = z.object({
  duration: GetPlanUpsertLicenseDuration$inboundSchema,
  length: types.number(),
});

export function getPlanUpsertLicenseExpiryFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseExpiry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanUpsertLicenseExpiry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseExpiry' from JSON`,
  );
}

/** @internal */
export const GetPlanDimensionsUpsertLicense4$inboundSchema: z.ZodMiniType<
  GetPlanDimensionsUpsertLicense4,
  unknown
> = z.pipe(
  z.object({
    match: z.record(z.string(), types.string()),
    priority: types.optional(types.number()),
    credit_cost: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "credit_cost": "creditCost",
    });
  }),
);

export function getPlanDimensionsUpsertLicense4FromJSON(
  jsonString: string,
): SafeParseResult<GetPlanDimensionsUpsertLicense4, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanDimensionsUpsertLicense4$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanDimensionsUpsertLicense4' from JSON`,
  );
}

/** @internal */
export const GetPlanDimensionsToUpsertLicenseEnum2$inboundSchema: z.ZodMiniEnum<
  typeof GetPlanDimensionsToUpsertLicenseEnum2
> = z.enum(GetPlanDimensionsToUpsertLicenseEnum2);

/** @internal */
export const GetPlanDimensionsUpsertLicenseToUnion2$inboundSchema:
  z.ZodMiniType<GetPlanDimensionsUpsertLicenseToUnion2, unknown> = smartUnion([
    types.number(),
    GetPlanDimensionsToUpsertLicenseEnum2$inboundSchema,
  ]);

export function getPlanDimensionsUpsertLicenseToUnion2FromJSON(
  jsonString: string,
): SafeParseResult<GetPlanDimensionsUpsertLicenseToUnion2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanDimensionsUpsertLicenseToUnion2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanDimensionsUpsertLicenseToUnion2' from JSON`,
  );
}

/** @internal */
export const GetPlanDimensionsUpsertLicenseTier2$inboundSchema: z.ZodMiniType<
  GetPlanDimensionsUpsertLicenseTier2,
  unknown
> = z.pipe(
  z.object({
    to: smartUnion([
      types.number(),
      GetPlanDimensionsToUpsertLicenseEnum2$inboundSchema,
    ]),
    credit_cost: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "credit_cost": "creditCost",
    });
  }),
);

export function getPlanDimensionsUpsertLicenseTier2FromJSON(
  jsonString: string,
): SafeParseResult<GetPlanDimensionsUpsertLicenseTier2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanDimensionsUpsertLicenseTier2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanDimensionsUpsertLicenseTier2' from JSON`,
  );
}

/** @internal */
export const GetPlanDimensionsUpsertLicense3$inboundSchema: z.ZodMiniType<
  GetPlanDimensionsUpsertLicense3,
  unknown
> = z.pipe(
  z.object({
    match: z.record(z.string(), types.string()),
    priority: types.optional(types.number()),
    tier_behavior: types.literal("graduated"),
    tiers: z.array(
      z.lazy(() => GetPlanDimensionsUpsertLicenseTier2$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "tier_behavior": "tierBehavior",
    });
  }),
);

export function getPlanDimensionsUpsertLicense3FromJSON(
  jsonString: string,
): SafeParseResult<GetPlanDimensionsUpsertLicense3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanDimensionsUpsertLicense3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanDimensionsUpsertLicense3' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseDimensionsUnion2$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseDimensionsUnion2,
  unknown
> = smartUnion([
  z.lazy(() => GetPlanDimensionsUpsertLicense3$inboundSchema),
  z.lazy(() => GetPlanDimensionsUpsertLicense4$inboundSchema),
]);

export function getPlanUpsertLicenseDimensionsUnion2FromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseDimensionsUnion2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanUpsertLicenseDimensionsUnion2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseDimensionsUnion2' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseMultipliers2$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseMultipliers2,
  unknown
> = z.object({
  match: z.record(z.string(), types.string()),
  factor: types.optional(types.number()),
  add: types.optional(types.number()),
});

export function getPlanUpsertLicenseMultipliers2FromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseMultipliers2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanUpsertLicenseMultipliers2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseMultipliers2' from JSON`,
  );
}

/** @internal */
export const GetPlanCreditSchemaUpsertLicense2$inboundSchema: z.ZodMiniType<
  GetPlanCreditSchemaUpsertLicense2,
  unknown
> = z.pipe(
  z.object({
    metered_feature_id: types.string(),
    billing_units: types.optional(types.number()),
    dimensions: types.optional(z.record(
      z.string(),
      smartUnion([
        z.lazy(() => GetPlanDimensionsUpsertLicense3$inboundSchema),
        z.lazy(() => GetPlanDimensionsUpsertLicense4$inboundSchema),
      ]),
    )),
    multipliers: types.optional(z.record(
      z.string(),
      z.lazy(() => GetPlanUpsertLicenseMultipliers2$inboundSchema),
    )),
    credit_cost: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "metered_feature_id": "meteredFeatureId",
      "billing_units": "billingUnits",
      "credit_cost": "creditCost",
    });
  }),
);

export function getPlanCreditSchemaUpsertLicense2FromJSON(
  jsonString: string,
): SafeParseResult<GetPlanCreditSchemaUpsertLicense2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanCreditSchemaUpsertLicense2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanCreditSchemaUpsertLicense2' from JSON`,
  );
}

/** @internal */
export const GetPlanDimensionsUpsertLicense2$inboundSchema: z.ZodMiniType<
  GetPlanDimensionsUpsertLicense2,
  unknown
> = z.pipe(
  z.object({
    match: z.record(z.string(), types.string()),
    priority: types.optional(types.number()),
    credit_cost: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "credit_cost": "creditCost",
    });
  }),
);

export function getPlanDimensionsUpsertLicense2FromJSON(
  jsonString: string,
): SafeParseResult<GetPlanDimensionsUpsertLicense2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanDimensionsUpsertLicense2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanDimensionsUpsertLicense2' from JSON`,
  );
}

/** @internal */
export const GetPlanDimensionsToUpsertLicenseEnum1$inboundSchema: z.ZodMiniEnum<
  typeof GetPlanDimensionsToUpsertLicenseEnum1
> = z.enum(GetPlanDimensionsToUpsertLicenseEnum1);

/** @internal */
export const GetPlanDimensionsUpsertLicenseToUnion1$inboundSchema:
  z.ZodMiniType<GetPlanDimensionsUpsertLicenseToUnion1, unknown> = smartUnion([
    types.number(),
    GetPlanDimensionsToUpsertLicenseEnum1$inboundSchema,
  ]);

export function getPlanDimensionsUpsertLicenseToUnion1FromJSON(
  jsonString: string,
): SafeParseResult<GetPlanDimensionsUpsertLicenseToUnion1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanDimensionsUpsertLicenseToUnion1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanDimensionsUpsertLicenseToUnion1' from JSON`,
  );
}

/** @internal */
export const GetPlanDimensionsUpsertLicenseTier1$inboundSchema: z.ZodMiniType<
  GetPlanDimensionsUpsertLicenseTier1,
  unknown
> = z.pipe(
  z.object({
    to: smartUnion([
      types.number(),
      GetPlanDimensionsToUpsertLicenseEnum1$inboundSchema,
    ]),
    credit_cost: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "credit_cost": "creditCost",
    });
  }),
);

export function getPlanDimensionsUpsertLicenseTier1FromJSON(
  jsonString: string,
): SafeParseResult<GetPlanDimensionsUpsertLicenseTier1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanDimensionsUpsertLicenseTier1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanDimensionsUpsertLicenseTier1' from JSON`,
  );
}

/** @internal */
export const GetPlanDimensionsUpsertLicense1$inboundSchema: z.ZodMiniType<
  GetPlanDimensionsUpsertLicense1,
  unknown
> = z.pipe(
  z.object({
    match: z.record(z.string(), types.string()),
    priority: types.optional(types.number()),
    tier_behavior: types.literal("graduated"),
    tiers: z.array(
      z.lazy(() => GetPlanDimensionsUpsertLicenseTier1$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "tier_behavior": "tierBehavior",
    });
  }),
);

export function getPlanDimensionsUpsertLicense1FromJSON(
  jsonString: string,
): SafeParseResult<GetPlanDimensionsUpsertLicense1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanDimensionsUpsertLicense1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanDimensionsUpsertLicense1' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseDimensionsUnion1$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseDimensionsUnion1,
  unknown
> = smartUnion([
  z.lazy(() => GetPlanDimensionsUpsertLicense1$inboundSchema),
  z.lazy(() => GetPlanDimensionsUpsertLicense2$inboundSchema),
]);

export function getPlanUpsertLicenseDimensionsUnion1FromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseDimensionsUnion1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanUpsertLicenseDimensionsUnion1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseDimensionsUnion1' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseMultipliers1$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseMultipliers1,
  unknown
> = z.object({
  match: z.record(z.string(), types.string()),
  factor: types.optional(types.number()),
  add: types.optional(types.number()),
});

export function getPlanUpsertLicenseMultipliers1FromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseMultipliers1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanUpsertLicenseMultipliers1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseMultipliers1' from JSON`,
  );
}

/** @internal */
export const GetPlanToUpsertLicenseEnum$inboundSchema: z.ZodMiniEnum<
  typeof GetPlanToUpsertLicenseEnum
> = z.enum(GetPlanToUpsertLicenseEnum);

/** @internal */
export const GetPlanUpsertLicenseFeatureOverrideToUnion$inboundSchema:
  z.ZodMiniType<GetPlanUpsertLicenseFeatureOverrideToUnion, unknown> =
    smartUnion([types.number(), GetPlanToUpsertLicenseEnum$inboundSchema]);

export function getPlanUpsertLicenseFeatureOverrideToUnionFromJSON(
  jsonString: string,
): SafeParseResult<
  GetPlanUpsertLicenseFeatureOverrideToUnion,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanUpsertLicenseFeatureOverrideToUnion$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetPlanUpsertLicenseFeatureOverrideToUnion' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseFeatureOverrideTier$inboundSchema:
  z.ZodMiniType<GetPlanUpsertLicenseFeatureOverrideTier, unknown> = z.pipe(
    z.object({
      to: smartUnion([
        types.number(),
        GetPlanToUpsertLicenseEnum$inboundSchema,
      ]),
      credit_cost: types.number(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "credit_cost": "creditCost",
      });
    }),
  );

export function getPlanUpsertLicenseFeatureOverrideTierFromJSON(
  jsonString: string,
): SafeParseResult<
  GetPlanUpsertLicenseFeatureOverrideTier,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanUpsertLicenseFeatureOverrideTier$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetPlanUpsertLicenseFeatureOverrideTier' from JSON`,
  );
}

/** @internal */
export const GetPlanCreditSchemaUpsertLicense1$inboundSchema: z.ZodMiniType<
  GetPlanCreditSchemaUpsertLicense1,
  unknown
> = z.pipe(
  z.object({
    metered_feature_id: types.string(),
    billing_units: types.optional(types.number()),
    dimensions: types.optional(z.record(
      z.string(),
      smartUnion([
        z.lazy(() => GetPlanDimensionsUpsertLicense1$inboundSchema),
        z.lazy(() => GetPlanDimensionsUpsertLicense2$inboundSchema),
      ]),
    )),
    multipliers: types.optional(z.record(
      z.string(),
      z.lazy(() => GetPlanUpsertLicenseMultipliers1$inboundSchema),
    )),
    tier_behavior: types.literal("graduated"),
    tiers: z.array(z.lazy(() =>
      GetPlanUpsertLicenseFeatureOverrideTier$inboundSchema
    )),
  }),
  z.transform((v) => {
    return remap$(v, {
      "metered_feature_id": "meteredFeatureId",
      "billing_units": "billingUnits",
      "tier_behavior": "tierBehavior",
    });
  }),
);

export function getPlanCreditSchemaUpsertLicense1FromJSON(
  jsonString: string,
): SafeParseResult<GetPlanCreditSchemaUpsertLicense1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanCreditSchemaUpsertLicense1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanCreditSchemaUpsertLicense1' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseCreditSchemaUnion$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseCreditSchemaUnion,
  unknown
> = smartUnion([
  z.lazy(() => GetPlanCreditSchemaUpsertLicense1$inboundSchema),
  z.lazy(() => GetPlanCreditSchemaUpsertLicense2$inboundSchema),
]);

export function getPlanUpsertLicenseCreditSchemaUnionFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseCreditSchemaUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanUpsertLicenseCreditSchemaUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseCreditSchemaUnion' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseProviderMarkups$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseProviderMarkups,
  unknown
> = z.object({
  markup: types.number(),
});

export function getPlanUpsertLicenseProviderMarkupsFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseProviderMarkups, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanUpsertLicenseProviderMarkups$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseProviderMarkups' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseModelMarkups$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseModelMarkups,
  unknown
> = z.pipe(
  z.object({
    markup: types.optional(types.number()),
    input_cost: types.optional(types.number()),
    output_cost: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "input_cost": "inputCost",
      "output_cost": "outputCost",
    });
  }),
);

export function getPlanUpsertLicenseModelMarkupsFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseModelMarkups, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanUpsertLicenseModelMarkups$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseModelMarkups' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseMarkups$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseMarkups,
  unknown
> = z.pipe(
  z.object({
    default_markup: types.optional(types.number()),
    provider_markups: z.optional(z.nullable(z.record(
      z.string(),
      z.lazy(() => GetPlanUpsertLicenseProviderMarkups$inboundSchema),
    ))),
    model_markups: z.optional(z.nullable(z.record(
      z.string(),
      z.lazy(() => GetPlanUpsertLicenseModelMarkups$inboundSchema),
    ))),
  }),
  z.transform((v) => {
    return remap$(v, {
      "default_markup": "defaultMarkup",
      "provider_markups": "providerMarkups",
      "model_markups": "modelMarkups",
    });
  }),
);

export function getPlanUpsertLicenseMarkupsFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseMarkups, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanUpsertLicenseMarkups$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseMarkups' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseFeatureOverride$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseFeatureOverride,
  unknown
> = z.pipe(
  z.object({
    credit_schema: types.optional(z.array(smartUnion([
      z.lazy(() => GetPlanCreditSchemaUpsertLicense1$inboundSchema),
      z.lazy(() =>
        GetPlanCreditSchemaUpsertLicense2$inboundSchema
      ),
    ]))),
    markups: types.optional(z.lazy(() =>
      GetPlanUpsertLicenseMarkups$inboundSchema
    )),
  }),
  z.transform((v) => {
    return remap$(v, {
      "credit_schema": "creditSchema",
    });
  }),
);

export function getPlanUpsertLicenseFeatureOverrideFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseFeatureOverride, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanUpsertLicenseFeatureOverride$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseFeatureOverride' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicensePlanItem$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicensePlanItem,
  unknown
> = z.pipe(
  z.object({
    threshold_billing: z.optional(z.nullable(z.lazy(() =>
      GetPlanUpsertLicenseThresholdBilling$inboundSchema
    ))),
    feature_id: types.string(),
    included: types.optional(types.number()),
    unlimited: types.optional(types.boolean()),
    pooled: z._default(types.boolean(), false),
    reset: types.optional(z.lazy(() =>
      GetPlanUpsertLicenseReset$inboundSchema
    )),
    price: types.optional(
      z.lazy(() => GetPlanUpsertLicensePrice$inboundSchema),
    ),
    proration: types.optional(
      z.lazy(() => GetPlanUpsertLicenseProration$inboundSchema),
    ),
    rollover: types.optional(
      z.lazy(() => GetPlanUpsertLicenseRollover$inboundSchema),
    ),
    expiry: types.optional(
      z.lazy(() => GetPlanUpsertLicenseExpiry$inboundSchema),
    ),
    feature_override: types.optional(
      z.lazy(() => GetPlanUpsertLicenseFeatureOverride$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "threshold_billing": "thresholdBilling",
      "feature_id": "featureId",
      "feature_override": "featureOverride",
    });
  }),
);

export function getPlanUpsertLicensePlanItemFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicensePlanItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanUpsertLicensePlanItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicensePlanItem' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseRemoveItemBillingMethod$inboundSchema:
  z.ZodMiniType<GetPlanUpsertLicenseRemoveItemBillingMethod, unknown> =
    openEnums.inboundSchema(GetPlanUpsertLicenseRemoveItemBillingMethod);

/** @internal */
export const GetPlanIntervalUpsertLicenseRemoveItemEnum2$inboundSchema:
  z.ZodMiniType<GetPlanIntervalUpsertLicenseRemoveItemEnum2, unknown> =
    openEnums.inboundSchema(GetPlanIntervalUpsertLicenseRemoveItemEnum2);

/** @internal */
export const GetPlanIntervalUpsertLicenseRemoveItemEnum1$inboundSchema:
  z.ZodMiniType<GetPlanIntervalUpsertLicenseRemoveItemEnum1, unknown> =
    openEnums.inboundSchema(GetPlanIntervalUpsertLicenseRemoveItemEnum1);

/** @internal */
export const GetPlanUpsertLicenseIntervalUnion$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseIntervalUnion,
  unknown
> = smartUnion([
  GetPlanIntervalUpsertLicenseRemoveItemEnum1$inboundSchema,
  GetPlanIntervalUpsertLicenseRemoveItemEnum2$inboundSchema,
]);

export function getPlanUpsertLicenseIntervalUnionFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseIntervalUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanUpsertLicenseIntervalUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseIntervalUnion' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicensePlanItemFilter$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicensePlanItemFilter,
  unknown
> = z.pipe(
  z.object({
    feature_id: types.optional(types.string()),
    billing_method: types.optional(
      GetPlanUpsertLicenseRemoveItemBillingMethod$inboundSchema,
    ),
    interval: types.optional(
      smartUnion([
        GetPlanIntervalUpsertLicenseRemoveItemEnum1$inboundSchema,
        GetPlanIntervalUpsertLicenseRemoveItemEnum2$inboundSchema,
      ]),
    ),
    interval_count: types.optional(types.number()),
    included: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "feature_id": "featureId",
      "billing_method": "billingMethod",
      "interval_count": "intervalCount",
    });
  }),
);

export function getPlanUpsertLicensePlanItemFilterFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicensePlanItemFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlanUpsertLicensePlanItemFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicensePlanItemFilter' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicenseCustomize$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicenseCustomize,
  unknown
> = z.pipe(
  z.object({
    price: z.optional(
      z.nullable(z.lazy(() => GetPlanUpsertLicenseBasePrice$inboundSchema)),
    ),
    add_items: types.optional(
      z.array(z.lazy(() => GetPlanUpsertLicensePlanItem$inboundSchema)),
    ),
    remove_items: types.optional(
      z.array(z.lazy(() => GetPlanUpsertLicensePlanItemFilter$inboundSchema)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "add_items": "addItems",
      "remove_items": "removeItems",
    });
  }),
);

export function getPlanUpsertLicenseCustomizeFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicenseCustomize, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanUpsertLicenseCustomize$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicenseCustomize' from JSON`,
  );
}

/** @internal */
export const GetPlanUpsertLicense$inboundSchema: z.ZodMiniType<
  GetPlanUpsertLicense,
  unknown
> = z.pipe(
  z.object({
    license_plan_id: types.string(),
    version_slug: types.optional(types.string()),
    included: types.optional(types.number()),
    prepaid_only: types.optional(types.boolean()),
    customize: z.optional(
      z.nullable(z.lazy(() => GetPlanUpsertLicenseCustomize$inboundSchema)),
    ),
    metadata: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "license_plan_id": "licensePlanId",
      "version_slug": "versionSlug",
      "prepaid_only": "prepaidOnly",
    });
  }),
);

export function getPlanUpsertLicenseFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanUpsertLicense, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanUpsertLicense$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanUpsertLicense' from JSON`,
  );
}

/** @internal */
export const GetPlanRemoveLicense$inboundSchema: z.ZodMiniType<
  GetPlanRemoveLicense,
  unknown
> = z.pipe(
  z.object({
    license_plan_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "license_plan_id": "licensePlanId",
    });
  }),
);

export function getPlanRemoveLicenseFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanRemoveLicense, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanRemoveLicense$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanRemoveLicense' from JSON`,
  );
}

/** @internal */
export const GetPlanCustomize$inboundSchema: z.ZodMiniType<
  GetPlanCustomize,
  unknown
> = z.pipe(
  z.object({
    price: z.optional(z.nullable(GetPlanBasePrice$inboundSchema)),
    add_items: types.optional(z.array(GetPlanPlanItem$inboundSchema)),
    remove_items: types.optional(z.array(GetPlanPlanItemFilter$inboundSchema)),
    free_trial: z.optional(z.nullable(GetPlanFreeTrialParams$inboundSchema)),
    billing_controls: types.optional(
      z.lazy(() => GetPlanVariantDetailsBillingControls$inboundSchema),
    ),
    upsert_licenses: types.optional(
      z.array(z.lazy(() => GetPlanUpsertLicense$inboundSchema)),
    ),
    remove_licenses: types.optional(
      z.array(z.lazy(() => GetPlanRemoveLicense$inboundSchema)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "add_items": "addItems",
      "remove_items": "removeItems",
      "free_trial": "freeTrial",
      "billing_controls": "billingControls",
      "upsert_licenses": "upsertLicenses",
      "remove_licenses": "removeLicenses",
    });
  }),
);

export function getPlanCustomizeFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanCustomize, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanCustomize$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanCustomize' from JSON`,
  );
}

/** @internal */
export const GetPlanVariantDetails$inboundSchema: z.ZodMiniType<
  GetPlanVariantDetails,
  unknown
> = z.pipe(
  z.object({
    base_plan_id: types.string(),
    customize: types.optional(z.lazy(() => GetPlanCustomize$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "base_plan_id": "basePlanId",
    });
  }),
);

export function getPlanVariantDetailsFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanVariantDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanVariantDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanVariantDetails' from JSON`,
  );
}

/** @internal */
export const GetPlanResponse$inboundSchema: z.ZodMiniType<
  GetPlanResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    name: types.string(),
    description: types.nullable(types.string()),
    group: types.nullable(types.string()),
    version: types.number(),
    version_slug: z.optional(z.nullable(types.string())),
    active: types.optional(types.boolean()),
    add_on: types.boolean(),
    auto_enable: types.boolean(),
    price: types.nullable(GetPlanPrice$inboundSchema),
    items: z.array(GetPlanItem$inboundSchema),
    processors: types.optional(GetPlanProcessors$inboundSchema),
    free_trial: types.optional(GetPlanFreeTrial$inboundSchema),
    created_at: types.number(),
    env: GetPlanEnv$inboundSchema,
    archived: types.boolean(),
    config: GetPlanConfig$inboundSchema,
    billing_controls: types.optional(GetPlanBillingControls$inboundSchema),
    metadata: z.record(z.string(), z.any()),
    customer_eligibility: types.optional(
      GetPlanCustomerEligibility$inboundSchema,
    ),
    base_variant_id: types.nullable(types.string()),
    variant_details: types.optional(
      z.lazy(() => GetPlanVariantDetails$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "version_slug": "versionSlug",
      "add_on": "addOn",
      "auto_enable": "autoEnable",
      "free_trial": "freeTrial",
      "created_at": "createdAt",
      "billing_controls": "billingControls",
      "customer_eligibility": "customerEligibility",
      "base_variant_id": "baseVariantId",
      "variant_details": "variantDetails",
    });
  }),
);

export function getPlanResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanResponse' from JSON`,
  );
}
