/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type ListWebhooksGlobals = {
  xApiVersion?: string | undefined;
};

/**
 * No body. Lists every webhook in the environment of the calling key.
 */
export type ListWebhooksParams = {};

export type ListWebhooksList = {
  /**
   * The webhook's ID. Webhooks made in the dashboard show their `ep_…` ID.
   */
  id: string;
  /**
   * The URL Autumn sends events to.
   */
  url: string;
  /**
   * A note for your own reference.
   */
  description: string | null;
  /**
   * The events sent to this webhook, as `WebhookEventType` names; a type newer than your client is returned as-is. Empty only for a webhook made in the dashboard that receives every event.
   */
  events: Array<string>;
  /**
   * When true, no events are sent to the webhook.
   */
  disabled: boolean;
  /**
   * When the webhook was created, ms since epoch.
   */
  createdAt: number;
  /**
   * When the webhook was last changed, ms since epoch.
   */
  updatedAt: number;
};

/**
 * OK
 */
export type ListWebhooksResponse = {
  /**
   * The environment's webhooks.
   */
  list: Array<ListWebhooksList>;
};

/** @internal */
export type ListWebhooksParams$Outbound = {};

/** @internal */
export const ListWebhooksParams$outboundSchema: z.ZodMiniType<
  ListWebhooksParams$Outbound,
  ListWebhooksParams
> = z.object({});

export function listWebhooksParamsToJSON(
  listWebhooksParams: ListWebhooksParams,
): string {
  return JSON.stringify(
    ListWebhooksParams$outboundSchema.parse(listWebhooksParams),
  );
}

/** @internal */
export const ListWebhooksList$inboundSchema: z.ZodMiniType<
  ListWebhooksList,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    url: types.string(),
    description: types.nullable(types.string()),
    events: z.array(types.string()),
    disabled: types.boolean(),
    created_at: types.number(),
    updated_at: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function listWebhooksListFromJSON(
  jsonString: string,
): SafeParseResult<ListWebhooksList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListWebhooksList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListWebhooksList' from JSON`,
  );
}

/** @internal */
export const ListWebhooksResponse$inboundSchema: z.ZodMiniType<
  ListWebhooksResponse,
  unknown
> = z.object({
  list: z.array(z.lazy(() => ListWebhooksList$inboundSchema)),
});

export function listWebhooksResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListWebhooksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListWebhooksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListWebhooksResponse' from JSON`,
  );
}
