/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type ListRewardsGlobals = {
  xApiVersion?: string | undefined;
};

export type RewardsListParams = {};

/**
 * The type of discount: percentage_discount, fixed_discount, or invoice_credits.
 */
export const CouponType = {
  PercentageDiscount: "percentage_discount",
  FixedDiscount: "fixed_discount",
  InvoiceCredits: "invoice_credits",
} as const;
/**
 * The type of discount: percentage_discount, fixed_discount, or invoice_credits.
 */
export type CouponType = OpenEnum<typeof CouponType>;

/**
 * The unit of time the duration is measured in.
 */
export const DurationType = {
  OneOff: "one_off",
  Months: "months",
  Forever: "forever",
} as const;
/**
 * The unit of time the duration is measured in.
 */
export type DurationType = OpenEnum<typeof DurationType>;

/**
 * How long the coupon applies once redeemed.
 */
export type ListRewardsDuration = {
  /**
   * The unit of time the duration is measured in.
   */
  type: DurationType;
  /**
   * The number of `type` periods the duration lasts, or null when the type has no length (e.g. one_off, forever).
   */
  length: number | null;
};

export type CouponPromoCode = {
  /**
   * The promo code customers enter to redeem the coupon.
   */
  code: string;
  /**
   * Maximum number of times this promo code can be redeemed across all customers, or null for unlimited.
   */
  globalMaxRedemption?: number | null | undefined;
  /**
   * Whether this promo code can only be applied to a customer's first transaction.
   */
  firstTimeTransaction?: boolean | null | undefined;
};

export type Coupon = {
  /**
   * The unique identifier for the coupon.
   */
  id: string;
  /**
   * A human-readable name for the coupon.
   */
  name?: string | null | undefined;
  /**
   * The type of discount: percentage_discount, fixed_discount, or invoice_credits.
   */
  type: CouponType;
  /**
   * The discount value. A percentage for percentage_discount, or an amount for fixed_discount / invoice_credits.
   */
  value: number;
  /**
   * How long the coupon applies once redeemed.
   */
  duration: ListRewardsDuration;
  /**
   * The plan IDs the coupon applies to, or null when it applies to all plans.
   */
  planIds: Array<string> | null;
  /**
   * The promo codes customers can use to redeem the coupon.
   */
  promoCodes: Array<CouponPromoCode>;
  /**
   * The Unix timestamp (in milliseconds) when the coupon was created.
   */
  createdAt: number;
};

/**
 * The unit of time the duration is measured in.
 */
export const ExpiryType = {
  Day: "day",
  Week: "week",
  Month: "month",
  Year: "year",
} as const;
/**
 * The unit of time the duration is measured in.
 */
export type ExpiryType = OpenEnum<typeof ExpiryType>;

export type Expiry = {
  /**
   * The unit of time the duration is measured in.
   */
  type: ExpiryType;
  /**
   * The number of `type` periods the duration lasts, or null when the type has no length (e.g. one_off, forever).
   */
  length: number | null;
};

export type Grant = {
  /**
   * The feature ID this grant applies to.
   */
  featureId: string;
  /**
   * The amount of the feature granted, or null for boolean features.
   */
  included: number | null;
  /**
   * How long the granted amount lasts before expiring, or null for a permanent grant.
   */
  expiry: Expiry | null;
};

export type FeatureGrantPromoCode = {
  /**
   * The promo code customers enter to redeem the feature grant.
   */
  code: string;
  /**
   * Maximum number of times this promo code can be redeemed, or null for unlimited.
   */
  maxUses: number | null;
};

export type FeatureGrant = {
  /**
   * The unique identifier for the feature grant.
   */
  id: string;
  /**
   * A human-readable name for the feature grant.
   */
  name?: string | null | undefined;
  /**
   * The feature grants awarded when the grant is redeemed.
   */
  grants: Array<Grant>;
  /**
   * The promo codes customers can use to redeem the feature grant.
   */
  promoCodes: Array<FeatureGrantPromoCode>;
  /**
   * The Unix timestamp (in milliseconds) when the feature grant was created.
   */
  createdAt: number;
};

/**
 * OK
 */
export type ListRewardsResponse = {
  /**
   * The list of coupons configured for the organization.
   */
  coupons: Array<Coupon>;
  /**
   * The list of feature grants configured for the organization.
   */
  featureGrants: Array<FeatureGrant>;
};

/** @internal */
export type RewardsListParams$Outbound = {};

/** @internal */
export const RewardsListParams$outboundSchema: z.ZodMiniType<
  RewardsListParams$Outbound,
  RewardsListParams
> = z.object({});

export function rewardsListParamsToJSON(
  rewardsListParams: RewardsListParams,
): string {
  return JSON.stringify(
    RewardsListParams$outboundSchema.parse(rewardsListParams),
  );
}

/** @internal */
export const CouponType$inboundSchema: z.ZodMiniType<CouponType, unknown> =
  openEnums.inboundSchema(CouponType);

/** @internal */
export const DurationType$inboundSchema: z.ZodMiniType<DurationType, unknown> =
  openEnums.inboundSchema(DurationType);

/** @internal */
export const ListRewardsDuration$inboundSchema: z.ZodMiniType<
  ListRewardsDuration,
  unknown
> = z.object({
  type: DurationType$inboundSchema,
  length: types.nullable(types.number()),
});

export function listRewardsDurationFromJSON(
  jsonString: string,
): SafeParseResult<ListRewardsDuration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListRewardsDuration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListRewardsDuration' from JSON`,
  );
}

/** @internal */
export const CouponPromoCode$inboundSchema: z.ZodMiniType<
  CouponPromoCode,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    global_max_redemption: z.optional(z.nullable(types.number())),
    first_time_transaction: z.optional(z.nullable(types.boolean())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "global_max_redemption": "globalMaxRedemption",
      "first_time_transaction": "firstTimeTransaction",
    });
  }),
);

export function couponPromoCodeFromJSON(
  jsonString: string,
): SafeParseResult<CouponPromoCode, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CouponPromoCode$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CouponPromoCode' from JSON`,
  );
}

/** @internal */
export const Coupon$inboundSchema: z.ZodMiniType<Coupon, unknown> = z.pipe(
  z.object({
    id: types.string(),
    name: z.optional(z.nullable(types.string())),
    type: CouponType$inboundSchema,
    value: types.number(),
    duration: z.lazy(() => ListRewardsDuration$inboundSchema),
    plan_ids: types.nullable(z.array(types.string())),
    promo_codes: z.array(z.lazy(() => CouponPromoCode$inboundSchema)),
    created_at: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "plan_ids": "planIds",
      "promo_codes": "promoCodes",
      "created_at": "createdAt",
    });
  }),
);

export function couponFromJSON(
  jsonString: string,
): SafeParseResult<Coupon, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Coupon$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Coupon' from JSON`,
  );
}

/** @internal */
export const ExpiryType$inboundSchema: z.ZodMiniType<ExpiryType, unknown> =
  openEnums.inboundSchema(ExpiryType);

/** @internal */
export const Expiry$inboundSchema: z.ZodMiniType<Expiry, unknown> = z.object({
  type: ExpiryType$inboundSchema,
  length: types.nullable(types.number()),
});

export function expiryFromJSON(
  jsonString: string,
): SafeParseResult<Expiry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Expiry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Expiry' from JSON`,
  );
}

/** @internal */
export const Grant$inboundSchema: z.ZodMiniType<Grant, unknown> = z.pipe(
  z.object({
    feature_id: types.string(),
    included: types.nullable(types.number()),
    expiry: types.nullable(z.lazy(() => Expiry$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "feature_id": "featureId",
    });
  }),
);

export function grantFromJSON(
  jsonString: string,
): SafeParseResult<Grant, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Grant$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Grant' from JSON`,
  );
}

/** @internal */
export const FeatureGrantPromoCode$inboundSchema: z.ZodMiniType<
  FeatureGrantPromoCode,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    max_uses: types.nullable(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "max_uses": "maxUses",
    });
  }),
);

export function featureGrantPromoCodeFromJSON(
  jsonString: string,
): SafeParseResult<FeatureGrantPromoCode, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FeatureGrantPromoCode$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FeatureGrantPromoCode' from JSON`,
  );
}

/** @internal */
export const FeatureGrant$inboundSchema: z.ZodMiniType<FeatureGrant, unknown> =
  z.pipe(
    z.object({
      id: types.string(),
      name: z.optional(z.nullable(types.string())),
      grants: z.array(z.lazy(() => Grant$inboundSchema)),
      promo_codes: z.array(z.lazy(() => FeatureGrantPromoCode$inboundSchema)),
      created_at: types.number(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "promo_codes": "promoCodes",
        "created_at": "createdAt",
      });
    }),
  );

export function featureGrantFromJSON(
  jsonString: string,
): SafeParseResult<FeatureGrant, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FeatureGrant$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FeatureGrant' from JSON`,
  );
}

/** @internal */
export const ListRewardsResponse$inboundSchema: z.ZodMiniType<
  ListRewardsResponse,
  unknown
> = z.pipe(
  z.object({
    coupons: z.array(z.lazy(() => Coupon$inboundSchema)),
    feature_grants: z.array(z.lazy(() => FeatureGrant$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "feature_grants": "featureGrants",
    });
  }),
);

export function listRewardsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListRewardsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListRewardsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListRewardsResponse' from JSON`,
  );
}
