/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type ListReferralProgramsGlobals = {
  xApiVersion?: string | undefined;
};

export type ListReferralProgramsParams = {};

/**
 * When the reward is granted: on redemption, or when the redeemer checks out.
 */
export const ListReferralProgramsRedeemOn = {
  CustomerCreation: "customer_creation",
  Checkout: "checkout",
} as const;
/**
 * When the reward is granted: on redemption, or when the redeemer checks out.
 */
export type ListReferralProgramsRedeemOn = OpenEnum<
  typeof ListReferralProgramsRedeemOn
>;

/**
 * Who receives the reward: the referrer only, or both parties.
 */
export const ListReferralProgramsReceivedBy = {
  Referrer: "referrer",
  All: "all",
} as const;
/**
 * Who receives the reward: the referrer only, or both parties.
 */
export type ListReferralProgramsReceivedBy = OpenEnum<
  typeof ListReferralProgramsReceivedBy
>;

export type ListReferralProgramsList = {
  /**
   * The unique identifier for the referral program.
   */
  id: string;
  /**
   * The ID of the reward granted when a code is redeemed.
   */
  rewardId: string;
  /**
   * When the reward is granted: on redemption, or when the redeemer checks out.
   */
  redeemOn: ListReferralProgramsRedeemOn;
  /**
   * Who receives the reward: the referrer only, or both parties.
   */
  receivedBy: ListReferralProgramsReceivedBy;
  /**
   * The maximum number of times a referral code can be redeemed.
   */
  maxRedemptions?: number | null | undefined;
  /**
   * The plans whose checkout triggers the reward. Only used when redeem_on is checkout.
   */
  planIds?: Array<string> | null | undefined;
  /**
   * Whether checkouts that start a trial should skip granting the reward.
   */
  excludeTrial?: boolean | null | undefined;
  /**
   * The Unix timestamp (in milliseconds) when the referral program was created.
   */
  createdAt: number;
};

/**
 * OK
 */
export type ListReferralProgramsResponse = {
  list: Array<ListReferralProgramsList>;
};

/** @internal */
export type ListReferralProgramsParams$Outbound = {};

/** @internal */
export const ListReferralProgramsParams$outboundSchema: z.ZodMiniType<
  ListReferralProgramsParams$Outbound,
  ListReferralProgramsParams
> = z.object({});

export function listReferralProgramsParamsToJSON(
  listReferralProgramsParams: ListReferralProgramsParams,
): string {
  return JSON.stringify(
    ListReferralProgramsParams$outboundSchema.parse(listReferralProgramsParams),
  );
}

/** @internal */
export const ListReferralProgramsRedeemOn$inboundSchema: z.ZodMiniType<
  ListReferralProgramsRedeemOn,
  unknown
> = openEnums.inboundSchema(ListReferralProgramsRedeemOn);

/** @internal */
export const ListReferralProgramsReceivedBy$inboundSchema: z.ZodMiniType<
  ListReferralProgramsReceivedBy,
  unknown
> = openEnums.inboundSchema(ListReferralProgramsReceivedBy);

/** @internal */
export const ListReferralProgramsList$inboundSchema: z.ZodMiniType<
  ListReferralProgramsList,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    reward_id: types.string(),
    redeem_on: ListReferralProgramsRedeemOn$inboundSchema,
    received_by: ListReferralProgramsReceivedBy$inboundSchema,
    max_redemptions: z.optional(z.nullable(types.number())),
    plan_ids: z.optional(z.nullable(z.array(types.string()))),
    exclude_trial: z.optional(z.nullable(types.boolean())),
    created_at: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "reward_id": "rewardId",
      "redeem_on": "redeemOn",
      "received_by": "receivedBy",
      "max_redemptions": "maxRedemptions",
      "plan_ids": "planIds",
      "exclude_trial": "excludeTrial",
      "created_at": "createdAt",
    });
  }),
);

export function listReferralProgramsListFromJSON(
  jsonString: string,
): SafeParseResult<ListReferralProgramsList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListReferralProgramsList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListReferralProgramsList' from JSON`,
  );
}

/** @internal */
export const ListReferralProgramsResponse$inboundSchema: z.ZodMiniType<
  ListReferralProgramsResponse,
  unknown
> = z.object({
  list: z.array(z.lazy(() => ListReferralProgramsList$inboundSchema)),
});

export function listReferralProgramsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListReferralProgramsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListReferralProgramsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListReferralProgramsResponse' from JSON`,
  );
}
