/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { Plan, Plan$inboundSchema } from "./plan.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type PreviewMultiUpdateGlobals = {
  xApiVersion?: string | undefined;
};

/**
 * Action to perform for cancellation. 'cancel_immediately' cancels now with prorated refund, 'cancel_end_of_cycle' cancels at period end, 'uncancel' reverses a pending cancellation.
 */
export const PreviewMultiUpdateCancelAction = {
  CancelImmediately: "cancel_immediately",
  CancelEndOfCycle: "cancel_end_of_cycle",
  Uncancel: "uncancel",
} as const;
/**
 * Action to perform for cancellation. 'cancel_immediately' cancels now with prorated refund, 'cancel_end_of_cycle' cancels at period end, 'uncancel' reverses a pending cancellation.
 */
export type PreviewMultiUpdateCancelAction = ClosedEnum<
  typeof PreviewMultiUpdateCancelAction
>;

/**
 * How to handle proration for this update. 'prorate_immediately' charges/credits prorated amounts now, 'none' skips creating any charges.
 */
export const PreviewMultiUpdateProrationBehavior = {
  ProrateImmediately: "prorate_immediately",
  None: "none",
} as const;
/**
 * How to handle proration for this update. 'prorate_immediately' charges/credits prorated amounts now, 'none' skips creating any charges.
 */
export type PreviewMultiUpdateProrationBehavior = ClosedEnum<
  typeof PreviewMultiUpdateProrationBehavior
>;

export type PreviewMultiUpdateUpdate = {
  /**
   * The ID of the plan to update. Optional if subscription_id is provided.
   */
  planId?: string | undefined;
  /**
   * A unique ID to identify the subscription to update. Useful when a customer has multiple products with the same plan.
   */
  subscriptionId?: string | undefined;
  /**
   * The ID of the entity this update targets. Overrides the top-level entity_id for this update.
   */
  entityId?: string | undefined;
  /**
   * Action to perform for cancellation. 'cancel_immediately' cancels now with prorated refund, 'cancel_end_of_cycle' cancels at period end, 'uncancel' reverses a pending cancellation.
   */
  cancelAction: PreviewMultiUpdateCancelAction;
  /**
   * How to handle proration for this update. 'prorate_immediately' charges/credits prorated amounts now, 'none' skips creating any charges.
   */
  prorationBehavior?: PreviewMultiUpdateProrationBehavior | undefined;
};

export type PreviewMultiUpdateParams = {
  /**
   * The ID of the customer to update plans for.
   */
  customerId: string;
  /**
   * The ID of the entity to update plans for. Individual updates can override this with their own entity_id.
   */
  entityId?: string | undefined;
  /**
   * The list of plan updates to apply to the customer.
   */
  updates: Array<PreviewMultiUpdateUpdate>;
};

export type PreviewMultiUpdateDiscount = {
  amountOff: number;
  percentOff?: number | undefined;
  rewardId?: string | undefined;
  rewardName?: string | undefined;
};

/**
 * The period of time that this line item is being charged for.
 */
export type PreviewMultiUpdateLineItemPeriod = {
  /**
   * The start of the period in milliseconds since the Unix epoch.
   */
  start: number;
  /**
   * The end of the period in milliseconds since the Unix epoch.
   */
  end: number;
};

export type PreviewMultiUpdateLineItem = {
  /**
   * The name of the line item to display to the customer if you're building a UI. It will either be the plan name or the feature name.
   */
  displayName: string;
  /**
   * A detailed description of the line item.
   */
  description: string;
  /**
   * The amount in cents before discounts and tax for this line item.
   */
  subtotal: number;
  /**
   * The final amount in cents after discounts and tax for this line item.
   */
  total: number;
  /**
   * List of discounts applied to this line item.
   */
  discounts?: Array<PreviewMultiUpdateDiscount> | undefined;
  /**
   * The ID of the plan that this line item belongs to.
   */
  planId: string;
  /**
   * The ID of the feature that this line item belongs to.
   */
  featureId: string | null;
  /**
   * The period of time that this line item is being charged for.
   */
  period?: PreviewMultiUpdateLineItemPeriod | undefined;
  /**
   * The quantity of the line item.
   */
  quantity: number;
};

export type PreviewMultiUpdateNextCycleDiscount = {
  amountOff: number;
  percentOff?: number | undefined;
  rewardId?: string | undefined;
  rewardName?: string | undefined;
};

/**
 * The period of time that this line item is being charged for.
 */
export type PreviewMultiUpdateNextCycleLineItemPeriod = {
  /**
   * The start of the period in milliseconds since the Unix epoch.
   */
  start: number;
  /**
   * The end of the period in milliseconds since the Unix epoch.
   */
  end: number;
};

export type PreviewMultiUpdateNextCycleLineItem = {
  /**
   * The name of the line item to display to the customer if you're building a UI. It will either be the plan name or the feature name.
   */
  displayName: string;
  /**
   * A detailed description of the line item.
   */
  description: string;
  /**
   * The amount in cents before discounts and tax for this line item.
   */
  subtotal: number;
  /**
   * The final amount in cents after discounts and tax for this line item.
   */
  total: number;
  /**
   * List of discounts applied to this line item.
   */
  discounts?: Array<PreviewMultiUpdateNextCycleDiscount> | undefined;
  /**
   * The ID of the plan that this line item belongs to.
   */
  planId: string;
  /**
   * The ID of the feature that this line item belongs to.
   */
  featureId: string | null;
  /**
   * The period of time that this line item is being charged for.
   */
  period?: PreviewMultiUpdateNextCycleLineItemPeriod | undefined;
  /**
   * The quantity of the line item.
   */
  quantity: number;
};

/**
 * The period of time that this line item is being charged for.
 */
export type PreviewMultiUpdateUsageLineItemPeriod = {
  /**
   * The start of the period in milliseconds since the Unix epoch.
   */
  start: number;
  /**
   * The end of the period in milliseconds since the Unix epoch.
   */
  end: number;
};

export type PreviewMultiUpdateUsageLineItem = {
  /**
   * The name of the line item to display to the customer if you're building a UI. It will either be the plan name or the feature name.
   */
  displayName: string;
  /**
   * The ID of the plan that this line item belongs to.
   */
  planId: string;
  /**
   * The ID of the feature that this line item belongs to.
   */
  featureId: string | null;
  /**
   * The period of time that this line item is being charged for.
   */
  period?: PreviewMultiUpdateUsageLineItemPeriod | undefined;
};

/**
 * Preview of the next billing cycle, if applicable. This shows what the customer will be charged in subsequent cycles.
 */
export type PreviewMultiUpdateNextCycle = {
  /**
   * Unix timestamp (milliseconds) when the next billing cycle starts.
   */
  startsAt: number;
  /**
   * The total amount in cents before discounts and tax for the next cycle.
   */
  subtotal: number;
  /**
   * The final amount in cents after discounts and tax for the next cycle.
   */
  total: number;
  /**
   * List of line items for the next billing cycle.
   */
  lineItems: Array<PreviewMultiUpdateNextCycleLineItem>;
  /**
   * List of line items for usage-based features in the next cycle.
   */
  usageLineItems: Array<PreviewMultiUpdateUsageLineItem>;
};

export type PreviewMultiUpdateIncomingFeatureQuantity = {
  /**
   * The ID of the adjustable feature included in this change.
   */
  featureId: string;
  /**
   * The quantity that will apply for this feature in the change.
   */
  quantity: number;
};

export type PreviewMultiUpdateIncoming = {
  /**
   * The ID of the plan affected by this preview change.
   */
  planId: string;
  plan?: Plan | undefined;
  /**
   * The feature quantity selections associated with this plan change.
   */
  featureQuantities: Array<PreviewMultiUpdateIncomingFeatureQuantity>;
  /**
   * When this change takes effect, in milliseconds since the Unix epoch, or null if it applies immediately.
   */
  effectiveAt: number | null;
  /**
   * When this plan was canceled, in milliseconds since the Unix epoch, or null if it is not canceled.
   */
  canceledAt: number | null;
  /**
   * When this plan expires, in milliseconds since the Unix epoch, or null if it does not expire.
   */
  expiresAt: number | null;
};

export type PreviewMultiUpdateOutgoingFeatureQuantity = {
  /**
   * The ID of the adjustable feature included in this change.
   */
  featureId: string;
  /**
   * The quantity that will apply for this feature in the change.
   */
  quantity: number;
};

export type PreviewMultiUpdateOutgoing = {
  /**
   * The ID of the plan affected by this preview change.
   */
  planId: string;
  plan?: Plan | undefined;
  /**
   * The feature quantity selections associated with this plan change.
   */
  featureQuantities: Array<PreviewMultiUpdateOutgoingFeatureQuantity>;
  /**
   * When this change takes effect, in milliseconds since the Unix epoch, or null if it applies immediately.
   */
  effectiveAt: number | null;
  /**
   * When this plan was canceled, in milliseconds since the Unix epoch, or null if it is not canceled.
   */
  canceledAt: number | null;
  /**
   * When this plan expires, in milliseconds since the Unix epoch, or null if it does not expire.
   */
  expiresAt: number | null;
};

export type PreviewMultiUpdateSubscription = {
  /**
   * The ID of the customer.
   */
  customerId: string;
  /**
   * List of line items for the current billing period.
   */
  lineItems: Array<PreviewMultiUpdateLineItem>;
  /**
   * The total amount in cents before discounts and tax for the current billing period.
   */
  subtotal: number;
  /**
   * The final amount in cents after discounts and tax for the current billing period.
   */
  total: number;
  /**
   * The three-letter ISO currency code (e.g., 'usd').
   */
  currency: string;
  /**
   * Preview of the next billing cycle, if applicable. This shows what the customer will be charged in subsequent cycles.
   */
  nextCycle?: PreviewMultiUpdateNextCycle | undefined;
  /**
   * Expand the response with additional data.
   */
  expand?: Array<string> | undefined;
  /**
   * Products or subscription changes being added or updated.
   */
  incoming: Array<PreviewMultiUpdateIncoming>;
  /**
   * Products or subscription changes being removed or ended.
   */
  outgoing: Array<PreviewMultiUpdateOutgoing>;
  /**
   * The IDs of the plans updated on this subscription.
   */
  planIds: Array<string>;
};

/**
 * OK
 */
export type MultiUpdatePreviewResponse = {
  /**
   * The ID of the customer the preview applies to.
   */
  customerId: string;
  /**
   * The three-letter ISO currency code (e.g., 'usd').
   */
  currency: string;
  /**
   * The combined amount due today across all subscriptions (sum of subscriptions[].total).
   */
  total: number;
  /**
   * One preview per affected Stripe subscription. Updates to plans without a subscription (free plans) produce no entry.
   */
  subscriptions: Array<PreviewMultiUpdateSubscription>;
};

/** @internal */
export const PreviewMultiUpdateCancelAction$outboundSchema: z.ZodMiniEnum<
  typeof PreviewMultiUpdateCancelAction
> = z.enum(PreviewMultiUpdateCancelAction);

/** @internal */
export const PreviewMultiUpdateProrationBehavior$outboundSchema: z.ZodMiniEnum<
  typeof PreviewMultiUpdateProrationBehavior
> = z.enum(PreviewMultiUpdateProrationBehavior);

/** @internal */
export type PreviewMultiUpdateUpdate$Outbound = {
  plan_id?: string | undefined;
  subscription_id?: string | undefined;
  entity_id?: string | undefined;
  cancel_action: string;
  proration_behavior?: string | undefined;
};

/** @internal */
export const PreviewMultiUpdateUpdate$outboundSchema: z.ZodMiniType<
  PreviewMultiUpdateUpdate$Outbound,
  PreviewMultiUpdateUpdate
> = z.pipe(
  z.object({
    planId: z.optional(z.string()),
    subscriptionId: z.optional(z.string()),
    entityId: z.optional(z.string()),
    cancelAction: PreviewMultiUpdateCancelAction$outboundSchema,
    prorationBehavior: z.optional(
      PreviewMultiUpdateProrationBehavior$outboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      planId: "plan_id",
      subscriptionId: "subscription_id",
      entityId: "entity_id",
      cancelAction: "cancel_action",
      prorationBehavior: "proration_behavior",
    });
  }),
);

export function previewMultiUpdateUpdateToJSON(
  previewMultiUpdateUpdate: PreviewMultiUpdateUpdate,
): string {
  return JSON.stringify(
    PreviewMultiUpdateUpdate$outboundSchema.parse(previewMultiUpdateUpdate),
  );
}

/** @internal */
export type PreviewMultiUpdateParams$Outbound = {
  customer_id: string;
  entity_id?: string | undefined;
  updates: Array<PreviewMultiUpdateUpdate$Outbound>;
};

/** @internal */
export const PreviewMultiUpdateParams$outboundSchema: z.ZodMiniType<
  PreviewMultiUpdateParams$Outbound,
  PreviewMultiUpdateParams
> = z.pipe(
  z.object({
    customerId: z.string(),
    entityId: z.optional(z.string()),
    updates: z.array(z.lazy(() => PreviewMultiUpdateUpdate$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      customerId: "customer_id",
      entityId: "entity_id",
    });
  }),
);

export function previewMultiUpdateParamsToJSON(
  previewMultiUpdateParams: PreviewMultiUpdateParams,
): string {
  return JSON.stringify(
    PreviewMultiUpdateParams$outboundSchema.parse(previewMultiUpdateParams),
  );
}

/** @internal */
export const PreviewMultiUpdateDiscount$inboundSchema: z.ZodMiniType<
  PreviewMultiUpdateDiscount,
  unknown
> = z.pipe(
  z.object({
    amount_off: types.number(),
    percent_off: types.optional(types.number()),
    reward_id: types.optional(types.string()),
    reward_name: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "amount_off": "amountOff",
      "percent_off": "percentOff",
      "reward_id": "rewardId",
      "reward_name": "rewardName",
    });
  }),
);

export function previewMultiUpdateDiscountFromJSON(
  jsonString: string,
): SafeParseResult<PreviewMultiUpdateDiscount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewMultiUpdateDiscount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewMultiUpdateDiscount' from JSON`,
  );
}

/** @internal */
export const PreviewMultiUpdateLineItemPeriod$inboundSchema: z.ZodMiniType<
  PreviewMultiUpdateLineItemPeriod,
  unknown
> = z.object({
  start: types.number(),
  end: types.number(),
});

export function previewMultiUpdateLineItemPeriodFromJSON(
  jsonString: string,
): SafeParseResult<PreviewMultiUpdateLineItemPeriod, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewMultiUpdateLineItemPeriod$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewMultiUpdateLineItemPeriod' from JSON`,
  );
}

/** @internal */
export const PreviewMultiUpdateLineItem$inboundSchema: z.ZodMiniType<
  PreviewMultiUpdateLineItem,
  unknown
> = z.pipe(
  z.object({
    display_name: types.string(),
    description: types.string(),
    subtotal: types.number(),
    total: types.number(),
    discounts: types.optional(
      z.array(z.lazy(() => PreviewMultiUpdateDiscount$inboundSchema)),
    ),
    plan_id: types.string(),
    feature_id: types.nullable(types.string()),
    period: types.optional(
      z.lazy(() => PreviewMultiUpdateLineItemPeriod$inboundSchema),
    ),
    quantity: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "display_name": "displayName",
      "plan_id": "planId",
      "feature_id": "featureId",
    });
  }),
);

export function previewMultiUpdateLineItemFromJSON(
  jsonString: string,
): SafeParseResult<PreviewMultiUpdateLineItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewMultiUpdateLineItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewMultiUpdateLineItem' from JSON`,
  );
}

/** @internal */
export const PreviewMultiUpdateNextCycleDiscount$inboundSchema: z.ZodMiniType<
  PreviewMultiUpdateNextCycleDiscount,
  unknown
> = z.pipe(
  z.object({
    amount_off: types.number(),
    percent_off: types.optional(types.number()),
    reward_id: types.optional(types.string()),
    reward_name: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "amount_off": "amountOff",
      "percent_off": "percentOff",
      "reward_id": "rewardId",
      "reward_name": "rewardName",
    });
  }),
);

export function previewMultiUpdateNextCycleDiscountFromJSON(
  jsonString: string,
): SafeParseResult<PreviewMultiUpdateNextCycleDiscount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PreviewMultiUpdateNextCycleDiscount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewMultiUpdateNextCycleDiscount' from JSON`,
  );
}

/** @internal */
export const PreviewMultiUpdateNextCycleLineItemPeriod$inboundSchema:
  z.ZodMiniType<PreviewMultiUpdateNextCycleLineItemPeriod, unknown> = z.object({
    start: types.number(),
    end: types.number(),
  });

export function previewMultiUpdateNextCycleLineItemPeriodFromJSON(
  jsonString: string,
): SafeParseResult<
  PreviewMultiUpdateNextCycleLineItemPeriod,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PreviewMultiUpdateNextCycleLineItemPeriod$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PreviewMultiUpdateNextCycleLineItemPeriod' from JSON`,
  );
}

/** @internal */
export const PreviewMultiUpdateNextCycleLineItem$inboundSchema: z.ZodMiniType<
  PreviewMultiUpdateNextCycleLineItem,
  unknown
> = z.pipe(
  z.object({
    display_name: types.string(),
    description: types.string(),
    subtotal: types.number(),
    total: types.number(),
    discounts: types.optional(
      z.array(z.lazy(() => PreviewMultiUpdateNextCycleDiscount$inboundSchema)),
    ),
    plan_id: types.string(),
    feature_id: types.nullable(types.string()),
    period: types.optional(
      z.lazy(() => PreviewMultiUpdateNextCycleLineItemPeriod$inboundSchema),
    ),
    quantity: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "display_name": "displayName",
      "plan_id": "planId",
      "feature_id": "featureId",
    });
  }),
);

export function previewMultiUpdateNextCycleLineItemFromJSON(
  jsonString: string,
): SafeParseResult<PreviewMultiUpdateNextCycleLineItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PreviewMultiUpdateNextCycleLineItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewMultiUpdateNextCycleLineItem' from JSON`,
  );
}

/** @internal */
export const PreviewMultiUpdateUsageLineItemPeriod$inboundSchema: z.ZodMiniType<
  PreviewMultiUpdateUsageLineItemPeriod,
  unknown
> = z.object({
  start: types.number(),
  end: types.number(),
});

export function previewMultiUpdateUsageLineItemPeriodFromJSON(
  jsonString: string,
): SafeParseResult<PreviewMultiUpdateUsageLineItemPeriod, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PreviewMultiUpdateUsageLineItemPeriod$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewMultiUpdateUsageLineItemPeriod' from JSON`,
  );
}

/** @internal */
export const PreviewMultiUpdateUsageLineItem$inboundSchema: z.ZodMiniType<
  PreviewMultiUpdateUsageLineItem,
  unknown
> = z.pipe(
  z.object({
    display_name: types.string(),
    plan_id: types.string(),
    feature_id: types.nullable(types.string()),
    period: types.optional(
      z.lazy(() => PreviewMultiUpdateUsageLineItemPeriod$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "display_name": "displayName",
      "plan_id": "planId",
      "feature_id": "featureId",
    });
  }),
);

export function previewMultiUpdateUsageLineItemFromJSON(
  jsonString: string,
): SafeParseResult<PreviewMultiUpdateUsageLineItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewMultiUpdateUsageLineItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewMultiUpdateUsageLineItem' from JSON`,
  );
}

/** @internal */
export const PreviewMultiUpdateNextCycle$inboundSchema: z.ZodMiniType<
  PreviewMultiUpdateNextCycle,
  unknown
> = z.pipe(
  z.object({
    starts_at: types.number(),
    subtotal: types.number(),
    total: types.number(),
    line_items: z.array(
      z.lazy(() => PreviewMultiUpdateNextCycleLineItem$inboundSchema),
    ),
    usage_line_items: z.array(
      z.lazy(() => PreviewMultiUpdateUsageLineItem$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "starts_at": "startsAt",
      "line_items": "lineItems",
      "usage_line_items": "usageLineItems",
    });
  }),
);

export function previewMultiUpdateNextCycleFromJSON(
  jsonString: string,
): SafeParseResult<PreviewMultiUpdateNextCycle, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewMultiUpdateNextCycle$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewMultiUpdateNextCycle' from JSON`,
  );
}

/** @internal */
export const PreviewMultiUpdateIncomingFeatureQuantity$inboundSchema:
  z.ZodMiniType<PreviewMultiUpdateIncomingFeatureQuantity, unknown> = z.pipe(
    z.object({
      feature_id: types.string(),
      quantity: types.number(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "feature_id": "featureId",
      });
    }),
  );

export function previewMultiUpdateIncomingFeatureQuantityFromJSON(
  jsonString: string,
): SafeParseResult<
  PreviewMultiUpdateIncomingFeatureQuantity,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PreviewMultiUpdateIncomingFeatureQuantity$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PreviewMultiUpdateIncomingFeatureQuantity' from JSON`,
  );
}

/** @internal */
export const PreviewMultiUpdateIncoming$inboundSchema: z.ZodMiniType<
  PreviewMultiUpdateIncoming,
  unknown
> = z.pipe(
  z.object({
    plan_id: types.string(),
    plan: types.optional(Plan$inboundSchema),
    feature_quantities: z.array(
      z.lazy(() => PreviewMultiUpdateIncomingFeatureQuantity$inboundSchema),
    ),
    effective_at: types.nullable(types.number()),
    canceled_at: types.nullable(types.number()),
    expires_at: types.nullable(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "plan_id": "planId",
      "feature_quantities": "featureQuantities",
      "effective_at": "effectiveAt",
      "canceled_at": "canceledAt",
      "expires_at": "expiresAt",
    });
  }),
);

export function previewMultiUpdateIncomingFromJSON(
  jsonString: string,
): SafeParseResult<PreviewMultiUpdateIncoming, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewMultiUpdateIncoming$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewMultiUpdateIncoming' from JSON`,
  );
}

/** @internal */
export const PreviewMultiUpdateOutgoingFeatureQuantity$inboundSchema:
  z.ZodMiniType<PreviewMultiUpdateOutgoingFeatureQuantity, unknown> = z.pipe(
    z.object({
      feature_id: types.string(),
      quantity: types.number(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "feature_id": "featureId",
      });
    }),
  );

export function previewMultiUpdateOutgoingFeatureQuantityFromJSON(
  jsonString: string,
): SafeParseResult<
  PreviewMultiUpdateOutgoingFeatureQuantity,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PreviewMultiUpdateOutgoingFeatureQuantity$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PreviewMultiUpdateOutgoingFeatureQuantity' from JSON`,
  );
}

/** @internal */
export const PreviewMultiUpdateOutgoing$inboundSchema: z.ZodMiniType<
  PreviewMultiUpdateOutgoing,
  unknown
> = z.pipe(
  z.object({
    plan_id: types.string(),
    plan: types.optional(Plan$inboundSchema),
    feature_quantities: z.array(
      z.lazy(() => PreviewMultiUpdateOutgoingFeatureQuantity$inboundSchema),
    ),
    effective_at: types.nullable(types.number()),
    canceled_at: types.nullable(types.number()),
    expires_at: types.nullable(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "plan_id": "planId",
      "feature_quantities": "featureQuantities",
      "effective_at": "effectiveAt",
      "canceled_at": "canceledAt",
      "expires_at": "expiresAt",
    });
  }),
);

export function previewMultiUpdateOutgoingFromJSON(
  jsonString: string,
): SafeParseResult<PreviewMultiUpdateOutgoing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewMultiUpdateOutgoing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewMultiUpdateOutgoing' from JSON`,
  );
}

/** @internal */
export const PreviewMultiUpdateSubscription$inboundSchema: z.ZodMiniType<
  PreviewMultiUpdateSubscription,
  unknown
> = z.pipe(
  z.object({
    customer_id: types.string(),
    line_items: z.array(z.lazy(() => PreviewMultiUpdateLineItem$inboundSchema)),
    subtotal: types.number(),
    total: types.number(),
    currency: types.string(),
    next_cycle: types.optional(
      z.lazy(() => PreviewMultiUpdateNextCycle$inboundSchema),
    ),
    expand: types.optional(z.array(types.string())),
    incoming: z.array(z.lazy(() => PreviewMultiUpdateIncoming$inboundSchema)),
    outgoing: z.array(z.lazy(() => PreviewMultiUpdateOutgoing$inboundSchema)),
    plan_ids: z.array(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "customer_id": "customerId",
      "line_items": "lineItems",
      "next_cycle": "nextCycle",
      "plan_ids": "planIds",
    });
  }),
);

export function previewMultiUpdateSubscriptionFromJSON(
  jsonString: string,
): SafeParseResult<PreviewMultiUpdateSubscription, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewMultiUpdateSubscription$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewMultiUpdateSubscription' from JSON`,
  );
}

/** @internal */
export const MultiUpdatePreviewResponse$inboundSchema: z.ZodMiniType<
  MultiUpdatePreviewResponse,
  unknown
> = z.pipe(
  z.object({
    customer_id: types.string(),
    currency: types.string(),
    total: types.number(),
    subscriptions: z.array(
      z.lazy(() => PreviewMultiUpdateSubscription$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "customer_id": "customerId",
    });
  }),
);

export function multiUpdatePreviewResponseFromJSON(
  jsonString: string,
): SafeParseResult<MultiUpdatePreviewResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MultiUpdatePreviewResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MultiUpdatePreviewResponse' from JSON`,
  );
}
