/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type ResetSandboxGlobals = {
  xApiVersion?: string | undefined;
};

/**
 * No body. Resets the sandbox the calling key belongs to — there is no id to pass.
 */
export type ResetSandboxParams = {};

/**
 * OK
 */
export type ResetSandboxResponse = {
  /**
   * Always true when the sandbox was reset.
   */
  success: true;
};

/** @internal */
export type ResetSandboxParams$Outbound = {};

/** @internal */
export const ResetSandboxParams$outboundSchema: z.ZodMiniType<
  ResetSandboxParams$Outbound,
  ResetSandboxParams
> = z.object({});

export function resetSandboxParamsToJSON(
  resetSandboxParams: ResetSandboxParams,
): string {
  return JSON.stringify(
    ResetSandboxParams$outboundSchema.parse(resetSandboxParams),
  );
}

/** @internal */
export const ResetSandboxResponse$inboundSchema: z.ZodMiniType<
  ResetSandboxResponse,
  unknown
> = z.object({
  success: types.literal(true),
});

export function resetSandboxResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResetSandboxResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResetSandboxResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResetSandboxResponse' from JSON`,
  );
}
