/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { balancesCreate } from "../funcs/balances-create.js";
import { balancesUpdate } from "../funcs/balances-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Balances extends ClientSDK {
  /**
   * Create a balance for a customer feature.
   */
  async create(
    request: models.CreateBalanceParams,
    options?: RequestOptions,
  ): Promise<models.CreateBalanceResponse> {
    return unwrapAsync(balancesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a customer balance.
   */
  async update(
    request: models.UpdateBalanceParams,
    options?: RequestOptions,
  ): Promise<models.UpdateBalanceResponse> {
    return unwrapAsync(balancesUpdate(
      this,
      request,
      options,
    ));
  }
}
