/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { balancesCheck } from "../funcs/balances-check.js";
import { balancesCreate } from "../funcs/balances-create.js";
import { balancesTrack } from "../funcs/balances-track.js";
import { balancesUpdate } from "../funcs/balances-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Balances extends ClientSDK {
  /**
   * Create a balance for a customer feature.
   */
  async create(
    request: models.BalancesCreateRequest,
    options?: RequestOptions,
  ): Promise<models.BalancesCreateResponse> {
    return unwrapAsync(balancesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a customer balance.
   */
  async update(
    request: models.BalancesUpdateRequest,
    options?: RequestOptions,
  ): Promise<models.BalancesUpdateResponse> {
    return unwrapAsync(balancesUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Check whether usage is allowed for a customer feature.
   */
  async check(
    request: models.BalancesCheckRequest,
    options?: RequestOptions,
  ): Promise<models.BalancesCheckResponse> {
    return unwrapAsync(balancesCheck(
      this,
      request,
      options,
    ));
  }

  /**
   * Track usage for a customer feature.
   */
  async track(
    request: models.BalancesTrackRequest,
    options?: RequestOptions,
  ): Promise<models.BalancesTrackResponse> {
    return unwrapAsync(balancesTrack(
      this,
      request,
      options,
    ));
  }
}
