// NOTE: For worktree-based agent flows, bun dw writes .env.local directly via
// writeEnvLocalFiles. This file is the Cursor Cloud / agent-bootstrap path.
//
// Isolation keys (local Postgres/Redis/SQS) MUST be in this file so they win
// over Infisical after `infisical run`. Do NOT write empty Stripe/etc lines —
// loadLocalEnv overwrites process.env, and empty values would clobber Infisical.
import {
	existsSync,
	readFileSync,
	copyFileSync,
	writeFileSync,
} from "node:fs";
import { randomBytes } from "node:crypto";
import { join } from "node:path";

const root = join(import.meta.dir, "..", "..");
const serverEnvPath = join(root, "server", ".env");
const viteEnvPath = join(root, "vite", ".env");
const viteExamplePath = join(root, "vite", ".env.example");

const PASS_THROUGH = [
	"STRIPE_SANDBOX_CLIENT_ID",
	"STRIPE_SANDBOX_SECRET_KEY",
	"STRIPE_SANDBOX_WEBHOOK_SECRET",
	"STRIPE_LIVE_CLIENT_ID",
	"STRIPE_LIVE_SECRET_KEY",
	"STRIPE_LIVE_WEBHOOK_SECRET",
	"ANTHROPIC_API_KEY",
	"RESEND_API_KEY",
	"RESEND_DOMAIN",
	"SVIX_API_KEY",
	"POSTHOG_API_KEY",
	"POSTHOG_HOST",
] as const;

const genUrlSafeBase64 = ({ bytes }: { bytes: number }): string =>
	randomBytes(bytes)
		.toString("base64")
		.replace(/\+/g, "-")
		.replace(/\//g, "_")
		.replace(/=+$/g, "");

const serverPort = process.env.AGENT_SERVER_PORT ?? "8080";
const vitePort = process.env.AGENT_VITE_PORT ?? "3000";

const isolationBlock = `# -----------------------------------------------------------------------
# Generated by scripts/setup/writeAgentEnv.ts
# Isolation overlay: wins over Infisical for local services / SQS.
# Team secrets (Stripe, etc.) come from Infisical — do not put empty
# STRIPE_*= lines here or loadLocalEnv will wipe them.
# -----------------------------------------------------------------------

# Per-agent random secrets
BETTER_AUTH_SECRET=${genUrlSafeBase64({ bytes: 64 })}
ENCRYPTION_IV=${genUrlSafeBase64({ bytes: 16 })}
ENCRYPTION_PASSWORD=${genUrlSafeBase64({ bytes: 64 })}

# Local services
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/autumn
MISC_CACHE_DRAGONFLY_PUBLIC_URL=redis://localhost:6379
REDIS_URL=redis://localhost:6379

# ElasticMQ (local SQS, per-agent isolated queue)
SQS_QUEUE_URL_V2=http://localhost:9324/000000000000/autumn.fifo
SQS_QUEUE_URL=http://localhost:9324/000000000000/autumn.fifo

# ClickHouse (local)
TINYBIRD_CLICKHOUSE_URL=http://localhost:8123

# App URLs
AUTUMN_API_URL=http://localhost:${serverPort}
AUTUMN_PUBLIC_API_URL=http://localhost:${serverPort}
CLIENT_URL=http://localhost:${vitePort}

# stripe listen uses a different whsec than Infisical's dashboard endpoint
STRIPE_WEBHOOK_SKIP_VERIFY=true

NODE_ENV=development
`;

/** Drop empty pass-through keys so Infisical-injected values survive preload. */
function stripEmptyPassThrough(contents: string): {
	text: string;
	changed: boolean;
} {
	const drop = new Set<string>(PASS_THROUGH);
	const kept: string[] = [];
	let changed = false;
	for (const line of contents.split(/\r?\n/)) {
		const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
		if (m && drop.has(m[1] as (typeof PASS_THROUGH)[number]) && m[2] === "") {
			changed = true;
			continue;
		}
		kept.push(line);
	}
	if (!contents.includes("STRIPE_WEBHOOK_SKIP_VERIFY=")) {
		kept.push("STRIPE_WEBHOOK_SKIP_VERIFY=true");
		changed = true;
	}
	return { text: `${kept.join("\n").replace(/\n+$/, "")}\n`, changed };
}

if (existsSync(serverEnvPath)) {
	const existing = readFileSync(serverEnvPath, "utf-8");
	const { text, changed } = stripEmptyPassThrough(existing);
	if (changed) {
		writeFileSync(serverEnvPath, text);
		console.log(
			"[writeAgentEnv] stripped empty Infisical pass-through keys from server/.env",
		);
	} else {
		console.log(
			"[writeAgentEnv] server/.env already exists — skipping generation",
		);
	}
} else {
	writeFileSync(serverEnvPath, isolationBlock);
	console.log("[writeAgentEnv] Wrote server/.env");
}

if (!existsSync(viteEnvPath) && existsSync(viteExamplePath)) {
	copyFileSync(viteExamplePath, viteEnvPath);
	console.log("[writeAgentEnv] Wrote vite/.env from .env.example");
}
