// NOTE: For worktree-based agent flows, bun dw writes .env.local directly via
// writeEnvLocalFiles. This file is the Cursor Cloud / agent-bootstrap path.
//
// Isolation keys (local Postgres/Redis/SQS) MUST be in this file so they win
// over Infisical after `infisical run`. Do NOT write empty Stripe/etc lines —
// loadLocalEnv overwrites process.env, and empty values would clobber Infisical.
//
// Do NOT write ENCRYPTION_* / BETTER_AUTH_SECRET here. A random password
// cannot decrypt Infisical/DB-stored Dragonfly backup URLs (BAD_DECRYPT).
import { existsSync, readFileSync, copyFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dir, "..", "..");
const serverEnvPath = join(root, "server", ".env");
const viteEnvPath = join(root, "vite", ".env");
const viteExamplePath = join(root, "vite", ".env.example");

const PASS_THROUGH = [
	"STRIPE_SANDBOX_CLIENT_ID",
	"STRIPE_SANDBOX_SECRET_KEY",
	"STRIPE_SANDBOX_WEBHOOK_SECRET",
	"STRIPE_LIVE_CLIENT_ID",
	"STRIPE_LIVE_SECRET_KEY",
	"STRIPE_LIVE_WEBHOOK_SECRET",
	"ANTHROPIC_API_KEY",
	"RESEND_API_KEY",
	"RESEND_DOMAIN",
	"SVIX_API_KEY",
	"POSTHOG_API_KEY",
	"POSTHOG_HOST",
] as const;

/** Random secrets previously written here; Infisical must win. */
const STRIP_PINNED_SECRETS = new Set([
	"BETTER_AUTH_SECRET",
	"ENCRYPTION_IV",
	"ENCRYPTION_PASSWORD",
]);

const serverPort = process.env.AGENT_SERVER_PORT ?? "8080";
const vitePort = process.env.AGENT_VITE_PORT ?? "3000";

const ISOLATION: Record<string, string> = {
	DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/autumn",
	DATABASE_CRITICAL_URL: "postgresql://postgres:postgres@localhost:5432/autumn",
	REDIS_URL: "redis://localhost:6379",
	MISC_CACHE_DRAGONFLY_PUBLIC_URL: "redis://localhost:6379",
	CACHE_V2_DRAGONFLY_URL: "redis://localhost:6379",
	CACHE_V2_DRAGONFLY_PUBLIC_URL: "redis://localhost:6379",
	SQS_QUEUE_URL: "http://localhost:9324/000000000000/autumn.fifo",
	SQS_QUEUE_URL_V2: "http://localhost:9324/000000000000/autumn.fifo",
	TRACK_SQS_QUEUE_URL: "http://localhost:9324/000000000000/autumn-track.fifo",
	TRACK_ASYNC_SQS_QUEUE_URL:
		"http://localhost:9324/000000000000/autumn-track.fifo",
	TRACK_ASYNC_STANDARD_SQS_QUEUE_URL:
		"http://localhost:9324/000000000000/autumn-track-async",
	STRIPE_WEBHOOK_SQS_QUEUE_URL:
		"http://localhost:9324/000000000000/autumn-stripe-webhook.fifo",
	TINYBIRD_CLICKHOUSE_URL: "http://localhost:8123",
	AUTUMN_API_URL: `http://localhost:${serverPort}`,
	AUTUMN_PUBLIC_API_URL: `http://localhost:${serverPort}`,
	CLIENT_URL: `http://localhost:${vitePort}`,
	STRIPE_WEBHOOK_SKIP_VERIFY: "true",
	NODE_ENV: "development",
	INFISICAL_ENVIRONMENT: "dev",
	AWS_REGION: "us-east-1",
	AWS_ACCESS_KEY_ID: "x",
	AWS_SECRET_ACCESS_KEY: "x",
};

const HEADER = `# -----------------------------------------------------------------------
# Generated by scripts/setup/writeAgentEnv.ts
# Isolation overlay: wins over Infisical for local services / SQS.
# Team secrets (Stripe, ENCRYPTION_*) come from Infisical — do not pin them.
# -----------------------------------------------------------------------
`;

function parseEnvLines(contents: string): string[] {
	return contents.split(/\r?\n/);
}

function upsertIsolation(contents: string): string {
	const dropEmpty = new Set<string>(PASS_THROUGH);
	const seen = new Set<string>();
	const kept: string[] = [];
	for (const line of parseEnvLines(contents)) {
		const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
		if (!m) {
			if (line.startsWith("# Generated by scripts/setup/writeAgentEnv.ts")) {
				continue;
			}
			if (line.startsWith("# Isolation overlay:")) continue;
			if (line.startsWith("# Team secrets")) continue;
			if (line.startsWith("# Per-agent random secrets")) continue;
			if (/^# -+$/.test(line.trim()) || line.startsWith("# -------")) continue;
			kept.push(line);
			continue;
		}
		const key = m[1];
		const value = m[2];
		if (STRIP_PINNED_SECRETS.has(key)) continue;
		if (dropEmpty.has(key) && value === "") continue;
		if (key in ISOLATION) {
			kept.push(`${key}=${ISOLATION[key]}`);
			seen.add(key);
			continue;
		}
		kept.push(line);
	}
	for (const [key, value] of Object.entries(ISOLATION)) {
		if (!seen.has(key)) kept.push(`${key}=${value}`);
	}
	const body = kept.join("\n").replace(/^\n+/, "").replace(/\n+$/, "");
	return `${HEADER}\n${body}\n`;
}

const previous = existsSync(serverEnvPath)
	? readFileSync(serverEnvPath, "utf-8")
	: "";
const next = upsertIsolation(previous);
if (next !== previous) {
	writeFileSync(serverEnvPath, next);
	console.log("[writeAgentEnv] wrote isolation overlay into server/.env");
} else {
	console.log("[writeAgentEnv] server/.env isolation overlay already current");
}

if (!existsSync(viteEnvPath) && existsSync(viteExamplePath)) {
	copyFileSync(viteExamplePath, viteEnvPath);
	console.log("[writeAgentEnv] Wrote vite/.env from .env.example");
}
