import { Hono } from "hono";
import { agentRulesRpcRouter } from "@/internal/agent/rules/agentRulesRouter";
import { referralRpcRouter } from "@/internal/api/rewards/referralRouter";
import { balancesRpcRouter } from "@/internal/balances/balancesRouter";
import { billingRpcRouter } from "@/internal/billing/billingRouter";
import { catalogRpcRouter } from "@/internal/catalog/catalogRouter";
import { entityRpcRouter } from "@/internal/entities/entityRouter";
import { eventsRpcRouter } from "@/internal/events/eventsRouter";
import { featureRpcRouter } from "@/internal/features/featureRouter";
import { keysRpcRouter } from "@/internal/keys/keysRouter";
import { logsRpcRouter } from "@/internal/logs/logsRouter";
import { migrationRpcRouter } from "@/internal/migrations/v2/migrationRouter";
import { platformRpcRouter } from "@/internal/platform/platformBeta/platformRpcRouter";
import { plansRpcRouter } from "@/internal/products/productRouter";
import { sandboxesRpcRouter } from "@/internal/sandboxes/sandboxesRouter";
import type { HonoEnv } from "../honoUtils/HonoEnv";
import { customerRpcRouter } from "../internal/customers/cusRouter";

export const rpcRouter = new Hono<HonoEnv>();

// rpcRouter.use("*", responseFilterMiddleware);
// rpcRouter.use("*", secretKeyMiddleware);
// rpcRouter.use("*", orgConfigMiddleware);
// rpcRouter.use("*", apiVersionMiddleware);
// rpcRouter.use("*", refreshCacheMiddleware);
// rpcRouter.use("*", refreshProductsCacheMiddleware);
// rpcRouter.use("*", analyticsMiddleware);
// rpcRouter.use("*", rateLimitMiddleware);
// rpcRouter.use("*", queryMiddleware());
// rpcRouter.use("*", idempotencyMiddleware);

rpcRouter.route("", customerRpcRouter);
rpcRouter.route("", agentRulesRpcRouter);
rpcRouter.route("", keysRpcRouter);
rpcRouter.route("", plansRpcRouter);
rpcRouter.route("", catalogRpcRouter);
rpcRouter.route("", billingRpcRouter);
rpcRouter.route("", balancesRpcRouter);
rpcRouter.route("", eventsRpcRouter);
rpcRouter.route("", referralRpcRouter);
rpcRouter.route("", entityRpcRouter);
rpcRouter.route("", featureRpcRouter);
rpcRouter.route("", logsRpcRouter);
rpcRouter.route("", migrationRpcRouter);
rpcRouter.route("", platformRpcRouter);
rpcRouter.route("", sandboxesRpcRouter);
