import { Hono } from "hono";
import { responseFilterMiddleware } from "@/honoMiddlewares/responseFilter/responseFilterMiddleware.js";
import { referralRpcRouter } from "@/internal/api/rewards/referralRouter.js";
import { balancesRpcRouter } from "@/internal/balances/balancesRouter.js";
import { billingRpcRouter } from "@/internal/billing/billingRouter.js";
import { entityRpcRouter } from "@/internal/entities/entityRouter.js";
import { eventsRpcRouter } from "@/internal/events/eventsRouter.js";
import { plansRpcRouter } from "@/internal/products/productRouter.js";
import { analyticsMiddleware } from "../honoMiddlewares/analyticsMiddleware.js";
import { apiVersionMiddleware } from "../honoMiddlewares/apiVersionMiddleware.js";
import { idempotencyMiddleware } from "../honoMiddlewares/idempotencyMiddleware.js";
import { orgConfigMiddleware } from "../honoMiddlewares/orgConfigMiddleware.js";
import { queryMiddleware } from "../honoMiddlewares/queryMiddleware.js";
import { rateLimitMiddleware } from "../honoMiddlewares/rateLimitMiddleware.js";
import { refreshCacheMiddleware } from "../honoMiddlewares/refreshCacheMiddleware.js";
import { refreshProductsCacheMiddleware } from "../honoMiddlewares/refreshProductsCacheMiddleware.js";
import { secretKeyMiddleware } from "../honoMiddlewares/secretKeyMiddleware.js";
import type { HonoEnv } from "../honoUtils/HonoEnv.js";
import { customerRpcRouter } from "../internal/customers/cusRouter";

export const rpcRouter = new Hono<HonoEnv>();

rpcRouter.use("*", responseFilterMiddleware);
rpcRouter.use("*", secretKeyMiddleware);
rpcRouter.use("*", orgConfigMiddleware);
rpcRouter.use("*", apiVersionMiddleware);
rpcRouter.use("*", refreshCacheMiddleware);
rpcRouter.use("*", refreshProductsCacheMiddleware);
rpcRouter.use("*", analyticsMiddleware);
rpcRouter.use("*", rateLimitMiddleware);
rpcRouter.use("*", queryMiddleware());
rpcRouter.use("*", idempotencyMiddleware);

rpcRouter.route("", customerRpcRouter);
rpcRouter.route("", plansRpcRouter);
rpcRouter.route("", billingRpcRouter);
rpcRouter.route("", balancesRpcRouter);
rpcRouter.route("", eventsRpcRouter);
rpcRouter.route("", referralRpcRouter);
rpcRouter.route("", entityRpcRouter);
