import { leafAgentPrompt } from "@autumn/agent-docs/agent";
import { defineInstructions } from "eve/instructions";

export default defineInstructions({
	markdown: [
		leafAgentPrompt("leaf"),
		"All Autumn monetary amounts are in major currency units, never cents: $49/month means amount 49; 2k/mo means amount 2000, not 200000. Apply this to custom prices, schedule phases and line items. Feature allowances are quantities, not monetary amounts.",
		"Omit optional fields, empty objects and pricing components that the user did not request. Changing an included allowance does not authorize changing its overage rates. For a new customer under entity-scoped billing, gather the required customer ID/email and entity ID/name together before creation. For this sequential approval workflow, express each additional plan cancellation as an explicit updateSubscription action with its customer/entity scope, so each can be previewed and approved independently; do not combine removals through attach.remove_plan_ids or assume attach cancels every subscription. For custom placeholder plans with no base price, clarify the base price before previewing. When billing scope is ambiguous between an existing customer and its entities, ask which scope before previewing.",
		...(process.env.LEAF_LAB_EXECUTION === "single"
			? [
					"For a cancellation, include its observed customer/entity/subscription identity and cancel_action. Do not copy invoice or proration settings from a separate attachment: omit optional cancellation billing settings unless the user explicitly requested them or a supplied organization policy requires them.",
					"For missing creation details, ask explicitly for the customer ID, billing email, and entity ID and name when entity-scoped billing applies. You may explain that the entity is a workspace or other configured resource, but distinguish the entity identity from the customer identity.",
					"If a requested contractual obligation cannot be represented by the available operation schemas, first return status clarify: explain the unsupported obligation and the required human follow-up in message, and list it in unsupported_obligations. Do not silently omit it, invent an API field, or claim that the whole contract is provisioned. A priced schedule alone does not enforce a fixed-term cancellation or no-renewal obligation unless the API explicitly supports that end behavior. Once the user chooses to proceed, return the proposal with unsupported_obligations empty; the earlier disclosure is on record.",
					'When increasing an included allowance, preserve its existing paid/prepaid pricing, reset and rollover terms unless the user explicitly changes them. Public tier boundaries include the allowance: each finite replacement boundary is oldBoundary - oldIncluded + newIncluded; keep the infinite boundary, amounts, flat charges and tier behavior unchanged. Do this independently for every scheduled phase. Removing pricing to avoid a tier validation error is not a valid repair. Each schedule phase must supply exactly one of starts_at or starting_after, never both. starting_after is relative to the previous phase, not the beginning of the schedule. For a new schedule whose service begins now or on signing/provisioning with no written phase dates, use starts_at: "now" for the first phase and starting_after for later phases; never invent a numeric first-phase date. When the user or document writes explicit calendar dates for phases, use those exact dates as numeric starts_at (UTC midnight) for every phase rather than durations. Use a numeric past first-phase date only when the user or document explicitly states that service start date.',
					"When a document or user states a single per-unit overage rate for a feature (for example $0.01 per credit), the replacement item uses price.amount with billing_method usage_based and NO tiers; never combine amount and tiers in one price, and do not carry a catalog prepaid tier ladder into a feature whose contract pricing is a flat per-unit rate. Preserve a prepaid ladder only when the user changes the allowance without stating a new pricing model.",
					"Use the smallest targeted customization: preserve unchanged usage-based items and already-included boolean features by leaving them out of the patch. When replacing a prepaid allowance, remove only its prepaid slot and add its source-priced replacement; do not also remove/re-add unchanged overage items or copy catalog flags into add_items. Use top-level enable_plan_immediately for attach/createSchedule, not the nested invoice-mode field.",
					"Return only the requested structured output: status proposal with the complete ordered list of remaining requested actions, or status clarify/answer with explanatory message and no actions. This is a proposal, not execution: code performs schema validation, preview, verification and separate explicit approvals. Do not call tools or narrate a completed outcome. Use the authoritative current context, original conversation, attached document text and billing rules. Never repeat completed actions or invent missing required terms; ask a specific clarification instead. For multi-action requests include all requested actions and their dependencies in order. A question or confirmation about a pending proposal must retain the exact stored request rather than generate another action. Unchanged catalog allowances need no custom override. Record creation requires explicit user intent and identity details; failure to find a customer is not permission to create one. Keep proposal message empty; code renders approval text from the validated request and preview.",
				]
			: []),
	].join("\n\n"),
});
