/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export function bigint(): z.ZodType<bigint | string> {
  return z.union([
    z.bigint().transform((v) => String(v)),
    z.string().transform((v, ctx) => {
      try {
        return BigInt(v);
      } catch {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: "Invalid bigint value",
        });
        return z.NEVER;
      }
    }),
    z.number().transform((v) => BigInt(Math.trunc(v))),
    z.union([z.null(), z.undefined()]).transform(() => BigInt(0)),
  ]);
}

export function bigintOptional(): z.ZodType<bigint | string | undefined> {
  return z
    .union([
      z.bigint().transform((v) => String(v)),
      z.string().transform((v, ctx) => {
        try {
          return BigInt(v);
        } catch {
          ctx.addIssue({
            code: z.ZodIssueCode.custom,
            message: "Invalid bigint value",
          });
          return z.NEVER;
        }
      }),
      z.number().transform((v) => BigInt(Math.trunc(v))),
      z.null().transform(() => undefined),
    ])
    .optional();
}

export function bigintNullable(): z.ZodType<bigint | string | null> {
  return z.union([
    z.bigint().transform((v) => String(v)),
    z.string().transform((v, ctx) => {
      try {
        return BigInt(v);
      } catch {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: "Invalid bigint value",
        });
        return z.NEVER;
      }
    }),
    z.number().transform((v) => BigInt(Math.trunc(v))),
    z.null(),
    z.undefined().transform(() => null),
  ]);
}

export function bigintConst<T extends bigint>(value: T): z.ZodType<T> {
  return z
    .union([
      z.bigint(),
      z.string().transform((v, ctx) => {
        try {
          return BigInt(v);
        } catch {
          ctx.addIssue({
            code: z.ZodIssueCode.custom,
            message: "Invalid bigint value",
          });
          return z.NEVER;
        }
      }),
      z.number().transform((v) => BigInt(Math.trunc(v))),
    ])
    .refine((v) => v === value, {
      message: `Value must be ${value}`,
    })
    .transform(() => value as T);
}
