import type { TestGroup } from "./types";

// Still failing after retry — under active triage.
const activeTempPaths = [
	"integration/billing/setup-payment/setup-payment-with-customize.test.ts",
	"integration/billing/stripe-webhooks/subscription-created/sub-created-auto-sync.test.ts",
	"integration/billing/stripe-webhooks/subscription-deleted/subscription-deleted-invoice.test.ts",
	"integration/billing/update-subscription/billing-behavior/next-cycle-only.test.ts",
	"integration/billing/update-subscription/cancel/immediately/cancel-immediately.test.ts",
	"integration/billing/update-subscription/cancel/uncancel/uncancel-combined.test.ts",
	"integration/billing/update-subscription/custom-plan/update-free-to-paid.test.ts",
	"integration/billing/update-subscription/custom-plan/update-paid-basic.test.ts",
	"integration/billing/update-subscription/custom-plan/update-paid-features.test.ts",
	"integration/billing/update-subscription/custom-plan/update-paid-prepaid.test.ts",
	"integration/billing/update-subscription/discounts/percent-off-discount.test.ts",
	"integration/billing/update-subscription/params/recalculate-balances/update-quantity-prepaid-overage.test.ts",
	"integration/billing/update-subscription/version-update/version-entitlements.test.ts",
	"integration/billing/update-subscription/version-update/version-pricing.test.ts",
	"integration/crud/customers/get-customer-entity-rollover-granted.test.ts",
	"integration/crud/plans/create-plan-basic.test.ts",
	"integration/crud/plans/create/pooled-item-validation.test.ts",
	"integration/crud/plans/variants/core-contract.test.ts",
	"integration/crud/plans/variants/feature-drop-propagation.test.ts",
	"integration/crud/plans/variants/interval-family.test.ts",
	"integration/crud/plans/variants/lifecycle.test.ts",
	"integration/crud/plans/variants/reset-tier-ladder.test.ts",
	"integration/crud/plans/versioning/variant-independent-versioning.test.ts",
	"integration/licenses/billing/attach/attach-customize-license.test.ts",
	"integration/licenses/billing/attach/attach-license-parent-stripe-product.test.ts",
	"integration/licenses/billing/attach/attach-parent-customized-license-switch.test.ts",
	"integration/licenses/billing/checkout/stripe-checkout-license-quantity.test.ts",
	"integration/licenses/billing/transitions/immediate-switch/attach-licenses-immediate-switch.test.ts",
	"integration/licenses/billing/transitions/immediate-switch/base-price-transitions/attach-base-price-transitions.test.ts",
	"integration/licenses/billing/transitions/immediate-switch/base-price-transitions/base-price-transition-edge-cases.test.ts",
	"integration/licenses/billing/transitions/immediate-switch/base-price-transitions/update-base-price-transitions.test.ts",
	"integration/licenses/billing/transitions/immediate-switch/item-transitions/free-item-transitions.test.ts",
	"integration/licenses/billing/transitions/immediate-switch/item-transitions/non-consumable-item-transition.test.ts",
	"integration/licenses/billing/transitions/immediate-switch/seat-customer-product-transition.test.ts",
	"integration/licenses/billing/transitions/scheduled-switch/base-price-transitions/scheduled-base-price-transition.test.ts",
	"integration/licenses/billing/transitions/scheduled-switch/item-transitions/non-consumable-item-transition.test.ts",
	"integration/licenses/billing/transitions/scheduled-switch/item-transitions/reset-cycle-anchor-transition.test.ts",
	"integration/licenses/billing/update/update-license-customize-patch.test.ts",
	"integration/licenses/billing/update/update-license-quantity.test.ts",
	"integration/licenses/billing/update/update-license-version.test.ts",
	"integration/licenses/billing/update/update-preserves-license-items.test.ts",
	"integration/licenses/catalog-update/child-plan/propagate/version-parent-with-customer.test.ts",
	"integration/licenses/catalog-update/license-catalog-edit-guards.test.ts",
	"integration/licenses/catalog-update/license-catalog-response.test.ts",
	"integration/licenses/catalog-update/license-sandbox-copy.test.ts",
];

export const temp: TestGroup = {
	name: "temp",
	description: "Still-failing suites from full-run retry — under triage",
	tier: "domain",
	paths: activeTempPaths,
	maxConcurrency: 2,
};
