import type { TestGroup } from "./types";

export const temp: TestGroup = {
	name: "temp",
	description: "Redis customer routing regression tests",
	tier: "domain",
	paths: [
		"balances/track/rollovers/track-rollover1.test.ts",
		"balances/track/rollovers/track-rollover2.test.ts",
		"integration/balances/track/basic/track-event-name.test.ts",
		"integration/balances/reset/get-customer-reset.test.ts",
		"integration/balances/reset/get-customer-reset-concurrent.test.ts",
		"integration/balances/reset/get-customer-reset-rollovers.test.ts",
		"integration/balances/reset/get-customer-reset-rollovers-concurrent.test.ts",
		"integration/balances/lock/check-with-lock-rollovers.test.ts",
		"integration/balances/lock/check-with-lock-concurrent-stress.test.ts",
		"integration/balances/lock/check-with-lock-edge-cases.test.ts",
		"integration/balances/lock/check-with-lock-credit-system.test.ts",
		"integration/balances/lock/basic/check-with-lock-refund.test.ts",
		"integration/balances/lock/basic/check-with-lock-additional-deduct.test.ts",
		"integration/balances/lock/basic/check-with-lock-release.test.ts",
		"integration/balances/lock/basic/check-with-lock-refund-breakdown.test.ts",
		"integration/balances/lock/check-with-lock-expiry.test.ts",
		"integration/balances/lock/postgres/check-with-lock-postgres.test.ts",
		"integration/balances/lock/check-with-lock-race.test.ts",
		"integration/balances/lock/postgres/check-with-lock-postgres-rollovers.test.ts",
		"integration/balances/lock/postgres/check-with-lock-postgres-edge-cases.test.ts",
		"integration/balances/lock/entities/check-lock-per-entity.test.ts",
		"integration/balances/lock/entities/check-lock-entity-product.test.ts",
	],
};
