"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from autumn_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from autumn_sdk.utils import FieldMetadata, HeaderMetadata, validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class BillingUpdateGlobalsTypedDict(TypedDict):
    x_api_version: NotRequired[str]


class BillingUpdateGlobals(BaseModel):
    x_api_version: Annotated[
        Optional[str],
        pydantic.Field(alias="x-api-version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = "2.3.0"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["x-api-version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BillingUpdateFeatureQuantityTypedDict(TypedDict):
    r"""Quantity configuration for a prepaid feature."""

    feature_id: str
    r"""The ID of the feature to set quantity for."""
    quantity: NotRequired[float]
    r"""The quantity of the feature."""
    adjustable: NotRequired[bool]
    r"""Whether the customer can adjust the quantity."""


class BillingUpdateFeatureQuantity(BaseModel):
    r"""Quantity configuration for a prepaid feature."""

    feature_id: str
    r"""The ID of the feature to set quantity for."""

    quantity: Optional[float] = None
    r"""The quantity of the feature."""

    adjustable: Optional[bool] = None
    r"""Whether the customer can adjust the quantity."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["quantity", "adjustable"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


BillingUpdatePriceInterval = Literal[
    "one_off",
    "week",
    "month",
    "quarter",
    "semi_annual",
    "year",
]
r"""Billing interval (e.g. 'month', 'year')."""


class BillingUpdateAdditionalCurrencyTypedDict(TypedDict):
    currency: str
    r"""Three-letter ISO currency code (e.g. 'eur', 'gbp')."""
    amount: float
    r"""Price amount in this currency. Set explicitly per currency, not converted from the base amount."""


class BillingUpdateAdditionalCurrency(BaseModel):
    currency: str
    r"""Three-letter ISO currency code (e.g. 'eur', 'gbp')."""

    amount: float
    r"""Price amount in this currency. Set explicitly per currency, not converted from the base amount."""


class BillingUpdateBasePriceTypedDict(TypedDict):
    r"""Base price configuration for a plan."""

    amount: float
    r"""Base price amount for the plan."""
    interval: BillingUpdatePriceInterval
    r"""Billing interval (e.g. 'month', 'year')."""
    interval_count: NotRequired[float]
    r"""Number of intervals per billing cycle. Defaults to 1."""
    additional_currencies: NotRequired[List[BillingUpdateAdditionalCurrencyTypedDict]]
    r"""Base price amounts in additional currencies. The base 'amount' is in the org's default currency."""


class BillingUpdateBasePrice(BaseModel):
    r"""Base price configuration for a plan."""

    amount: float
    r"""Base price amount for the plan."""

    interval: BillingUpdatePriceInterval
    r"""Billing interval (e.g. 'month', 'year')."""

    interval_count: Optional[float] = None
    r"""Number of intervals per billing cycle. Defaults to 1."""

    additional_currencies: Optional[List[BillingUpdateAdditionalCurrency]] = None
    r"""Base price amounts in additional currencies. The base 'amount' is in the org's default currency."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["interval_count", "additional_currencies"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


BillingUpdateItemResetInterval = Literal[
    "one_off",
    "minute",
    "hour",
    "day",
    "week",
    "month",
    "quarter",
    "semi_annual",
    "year",
]
r"""Interval at which balance resets (e.g. 'month', 'year'). For consumable features only."""


class BillingUpdateItemResetTypedDict(TypedDict):
    r"""Reset configuration for consumable features. Omit for non-consumable features like seats."""

    interval: BillingUpdateItemResetInterval
    r"""Interval at which balance resets (e.g. 'month', 'year'). For consumable features only."""
    interval_count: NotRequired[float]
    r"""Number of intervals between resets. Defaults to 1."""


class BillingUpdateItemReset(BaseModel):
    r"""Reset configuration for consumable features. Omit for non-consumable features like seats."""

    interval: BillingUpdateItemResetInterval
    r"""Interval at which balance resets (e.g. 'month', 'year'). For consumable features only."""

    interval_count: Optional[float] = None
    r"""Number of intervals between resets. Defaults to 1."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["interval_count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BillingUpdateItemAdditionalCurrencyTypedDict(TypedDict):
    currency: str
    r"""Three-letter ISO currency code (e.g. 'eur', 'gbp')."""
    amount: float
    r"""Price amount in this currency. Set explicitly per currency, not converted from the base amount."""


class BillingUpdateItemAdditionalCurrency(BaseModel):
    currency: str
    r"""Three-letter ISO currency code (e.g. 'eur', 'gbp')."""

    amount: float
    r"""Price amount in this currency. Set explicitly per currency, not converted from the base amount."""


BillingUpdateItemToTypedDict = TypeAliasType(
    "BillingUpdateItemToTypedDict", Union[float, str]
)


BillingUpdateItemTo = TypeAliasType("BillingUpdateItemTo", Union[float, str])


class BillingUpdateItemTierAdditionalCurrencyTypedDict(TypedDict):
    currency: str
    r"""Three-letter ISO currency code (e.g. 'eur', 'gbp')."""
    amount: NotRequired[float]
    r"""Per-unit amount for this tier in this currency."""
    flat_amount: NotRequired[float]
    r"""Flat amount for this tier in this currency, if the tier uses one."""


class BillingUpdateItemTierAdditionalCurrency(BaseModel):
    currency: str
    r"""Three-letter ISO currency code (e.g. 'eur', 'gbp')."""

    amount: Optional[float] = None
    r"""Per-unit amount for this tier in this currency."""

    flat_amount: Optional[float] = None
    r"""Flat amount for this tier in this currency, if the tier uses one."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["amount", "flat_amount"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BillingUpdateItemTierTypedDict(TypedDict):
    to: BillingUpdateItemToTypedDict
    amount: NotRequired[float]
    flat_amount: NotRequired[float]
    additional_currencies: NotRequired[
        List[BillingUpdateItemTierAdditionalCurrencyTypedDict]
    ]
    r"""Per-currency amounts for this tier. Tier boundaries ('to') are shared across all currencies."""


class BillingUpdateItemTier(BaseModel):
    to: BillingUpdateItemTo

    amount: Optional[float] = None

    flat_amount: Optional[float] = None

    additional_currencies: Optional[List[BillingUpdateItemTierAdditionalCurrency]] = (
        None
    )
    r"""Per-currency amounts for this tier. Tier boundaries ('to') are shared across all currencies."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["amount", "flat_amount", "additional_currencies"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


BillingUpdateItemTierBehavior = Literal[
    "graduated",
    "volume",
]


BillingUpdateItemPriceInterval = Literal[
    "one_off",
    "week",
    "month",
    "quarter",
    "semi_annual",
    "year",
]
r"""Billing interval. For consumable features, should match reset.interval."""


BillingUpdateItemBillingMethod = Literal[
    "prepaid",
    "usage_based",
]
r"""'prepaid' for upfront payment (seats), 'usage_based' for pay-as-you-go."""


class BillingUpdateItemPriceTypedDict(TypedDict):
    r"""Pricing for usage beyond included units. Omit for free features."""

    interval: BillingUpdateItemPriceInterval
    r"""Billing interval. For consumable features, should match reset.interval."""
    billing_method: BillingUpdateItemBillingMethod
    r"""'prepaid' for upfront payment (seats), 'usage_based' for pay-as-you-go."""
    amount: NotRequired[float]
    r"""Price per billing_units after included usage. Either 'amount' or 'tiers' is required."""
    additional_currencies: NotRequired[
        List[BillingUpdateItemAdditionalCurrencyTypedDict]
    ]
    r"""Amounts in additional currencies for this flat price. The base 'amount' is in the org's default currency. Only valid with 'amount', not 'tiers'."""
    tiers: NotRequired[List[BillingUpdateItemTierTypedDict]]
    r"""Tiered pricing.  Either 'amount' or 'tiers' is required."""
    tier_behavior: NotRequired[BillingUpdateItemTierBehavior]
    interval_count: NotRequired[float]
    r"""Number of intervals per billing cycle. Defaults to 1."""
    billing_units: NotRequired[float]
    r"""Units per price increment. Usage is rounded UP when billed (e.g. billing_units=100 means 101 rounds to 200)."""
    max_purchase: NotRequired[Nullable[float]]
    r"""Max units purchasable beyond included. E.g. included=100, max_purchase=300 allows 400 total. Null for no limit."""


class BillingUpdateItemPrice(BaseModel):
    r"""Pricing for usage beyond included units. Omit for free features."""

    interval: BillingUpdateItemPriceInterval
    r"""Billing interval. For consumable features, should match reset.interval."""

    billing_method: BillingUpdateItemBillingMethod
    r"""'prepaid' for upfront payment (seats), 'usage_based' for pay-as-you-go."""

    amount: Optional[float] = None
    r"""Price per billing_units after included usage. Either 'amount' or 'tiers' is required."""

    additional_currencies: Optional[List[BillingUpdateItemAdditionalCurrency]] = None
    r"""Amounts in additional currencies for this flat price. The base 'amount' is in the org's default currency. Only valid with 'amount', not 'tiers'."""

    tiers: Optional[List[BillingUpdateItemTier]] = None
    r"""Tiered pricing.  Either 'amount' or 'tiers' is required."""

    tier_behavior: Optional[BillingUpdateItemTierBehavior] = None

    interval_count: Optional[float] = 1
    r"""Number of intervals per billing cycle. Defaults to 1."""

    billing_units: Optional[float] = 1
    r"""Units per price increment. Usage is rounded UP when billed (e.g. billing_units=100 means 101 rounds to 200)."""

    max_purchase: OptionalNullable[float] = UNSET
    r"""Max units purchasable beyond included. E.g. included=100, max_purchase=300 allows 400 total. Null for no limit."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "amount",
                "additional_currencies",
                "tiers",
                "tier_behavior",
                "interval_count",
                "billing_units",
                "max_purchase",
            ]
        )
        nullable_fields = set(["max_purchase"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


BillingUpdateItemOnIncrease = Literal[
    "bill_immediately",
    "prorate_immediately",
    "prorate_next_cycle",
    "bill_next_cycle",
]
r"""Billing behavior when quantity increases mid-cycle."""


BillingUpdateItemOnDecrease = Literal[
    "prorate",
    "prorate_immediately",
    "prorate_next_cycle",
    "none",
    "no_prorations",
]
r"""Credit behavior when quantity decreases mid-cycle."""


class BillingUpdateItemProrationTypedDict(TypedDict):
    r"""Proration settings for prepaid features. Controls mid-cycle quantity change billing."""

    on_increase: BillingUpdateItemOnIncrease
    r"""Billing behavior when quantity increases mid-cycle."""
    on_decrease: BillingUpdateItemOnDecrease
    r"""Credit behavior when quantity decreases mid-cycle."""


class BillingUpdateItemProration(BaseModel):
    r"""Proration settings for prepaid features. Controls mid-cycle quantity change billing."""

    on_increase: BillingUpdateItemOnIncrease
    r"""Billing behavior when quantity increases mid-cycle."""

    on_decrease: BillingUpdateItemOnDecrease
    r"""Credit behavior when quantity decreases mid-cycle."""


BillingUpdateItemExpiryDurationType = Literal[
    "month",
    "forever",
]
r"""When rolled over units expire."""


class BillingUpdateItemRolloverTypedDict(TypedDict):
    r"""Rollover config for unused units. If set, unused included units carry over."""

    expiry_duration_type: BillingUpdateItemExpiryDurationType
    r"""When rolled over units expire."""
    max: NotRequired[float]
    r"""Max rollover units. Omit for unlimited rollover."""
    max_percentage: NotRequired[float]
    r"""Maximum rollover as a percentage (0-100) of included + prepaid grant. Mutually exclusive with max."""
    expiry_duration_length: NotRequired[float]
    r"""Number of periods before expiry."""


class BillingUpdateItemRollover(BaseModel):
    r"""Rollover config for unused units. If set, unused included units carry over."""

    expiry_duration_type: BillingUpdateItemExpiryDurationType
    r"""When rolled over units expire."""

    max: Optional[float] = None
    r"""Max rollover units. Omit for unlimited rollover."""

    max_percentage: Optional[float] = None
    r"""Maximum rollover as a percentage (0-100) of included + prepaid grant. Mutually exclusive with max."""

    expiry_duration_length: Optional[float] = None
    r"""Number of periods before expiry."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["max", "max_percentage", "expiry_duration_length"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BillingUpdateItemPlanItemTypedDict(TypedDict):
    r"""Configuration for a feature item in a plan, including usage limits, pricing, and rollover settings."""

    feature_id: str
    r"""The ID of the feature to configure."""
    included: NotRequired[float]
    r"""Number of free units included. Balance resets to this each interval for consumable features."""
    unlimited: NotRequired[bool]
    r"""If true, customer has unlimited access to this feature."""
    reset: NotRequired[BillingUpdateItemResetTypedDict]
    r"""Reset configuration for consumable features. Omit for non-consumable features like seats."""
    price: NotRequired[BillingUpdateItemPriceTypedDict]
    r"""Pricing for usage beyond included units. Omit for free features."""
    proration: NotRequired[BillingUpdateItemProrationTypedDict]
    r"""Proration settings for prepaid features. Controls mid-cycle quantity change billing."""
    rollover: NotRequired[BillingUpdateItemRolloverTypedDict]
    r"""Rollover config for unused units. If set, unused included units carry over."""


class BillingUpdateItemPlanItem(BaseModel):
    r"""Configuration for a feature item in a plan, including usage limits, pricing, and rollover settings."""

    feature_id: str
    r"""The ID of the feature to configure."""

    included: Optional[float] = None
    r"""Number of free units included. Balance resets to this each interval for consumable features."""

    unlimited: Optional[bool] = None
    r"""If true, customer has unlimited access to this feature."""

    reset: Optional[BillingUpdateItemReset] = None
    r"""Reset configuration for consumable features. Omit for non-consumable features like seats."""

    price: Optional[BillingUpdateItemPrice] = None
    r"""Pricing for usage beyond included units. Omit for free features."""

    proration: Optional[BillingUpdateItemProration] = None
    r"""Proration settings for prepaid features. Controls mid-cycle quantity change billing."""

    rollover: Optional[BillingUpdateItemRollover] = None
    r"""Rollover config for unused units. If set, unused included units carry over."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["included", "unlimited", "reset", "price", "proration", "rollover"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


BillingUpdateAddItemResetInterval = Literal[
    "one_off",
    "minute",
    "hour",
    "day",
    "week",
    "month",
    "quarter",
    "semi_annual",
    "year",
]
r"""Interval at which balance resets (e.g. 'month', 'year'). For consumable features only."""


class BillingUpdateAddItemResetTypedDict(TypedDict):
    r"""Reset configuration for consumable features. Omit for non-consumable features like seats."""

    interval: BillingUpdateAddItemResetInterval
    r"""Interval at which balance resets (e.g. 'month', 'year'). For consumable features only."""
    interval_count: NotRequired[float]
    r"""Number of intervals between resets. Defaults to 1."""


class BillingUpdateAddItemReset(BaseModel):
    r"""Reset configuration for consumable features. Omit for non-consumable features like seats."""

    interval: BillingUpdateAddItemResetInterval
    r"""Interval at which balance resets (e.g. 'month', 'year'). For consumable features only."""

    interval_count: Optional[float] = None
    r"""Number of intervals between resets. Defaults to 1."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["interval_count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BillingUpdateAddItemAdditionalCurrencyTypedDict(TypedDict):
    currency: str
    r"""Three-letter ISO currency code (e.g. 'eur', 'gbp')."""
    amount: float
    r"""Price amount in this currency. Set explicitly per currency, not converted from the base amount."""


class BillingUpdateAddItemAdditionalCurrency(BaseModel):
    currency: str
    r"""Three-letter ISO currency code (e.g. 'eur', 'gbp')."""

    amount: float
    r"""Price amount in this currency. Set explicitly per currency, not converted from the base amount."""


BillingUpdateAddItemToTypedDict = TypeAliasType(
    "BillingUpdateAddItemToTypedDict", Union[float, str]
)


BillingUpdateAddItemTo = TypeAliasType("BillingUpdateAddItemTo", Union[float, str])


class BillingUpdateAddItemTierAdditionalCurrencyTypedDict(TypedDict):
    currency: str
    r"""Three-letter ISO currency code (e.g. 'eur', 'gbp')."""
    amount: NotRequired[float]
    r"""Per-unit amount for this tier in this currency."""
    flat_amount: NotRequired[float]
    r"""Flat amount for this tier in this currency, if the tier uses one."""


class BillingUpdateAddItemTierAdditionalCurrency(BaseModel):
    currency: str
    r"""Three-letter ISO currency code (e.g. 'eur', 'gbp')."""

    amount: Optional[float] = None
    r"""Per-unit amount for this tier in this currency."""

    flat_amount: Optional[float] = None
    r"""Flat amount for this tier in this currency, if the tier uses one."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["amount", "flat_amount"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BillingUpdateAddItemTierTypedDict(TypedDict):
    to: BillingUpdateAddItemToTypedDict
    amount: NotRequired[float]
    flat_amount: NotRequired[float]
    additional_currencies: NotRequired[
        List[BillingUpdateAddItemTierAdditionalCurrencyTypedDict]
    ]
    r"""Per-currency amounts for this tier. Tier boundaries ('to') are shared across all currencies."""


class BillingUpdateAddItemTier(BaseModel):
    to: BillingUpdateAddItemTo

    amount: Optional[float] = None

    flat_amount: Optional[float] = None

    additional_currencies: Optional[
        List[BillingUpdateAddItemTierAdditionalCurrency]
    ] = None
    r"""Per-currency amounts for this tier. Tier boundaries ('to') are shared across all currencies."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["amount", "flat_amount", "additional_currencies"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


BillingUpdateAddItemTierBehavior = Literal[
    "graduated",
    "volume",
]


BillingUpdateAddItemPriceInterval = Literal[
    "one_off",
    "week",
    "month",
    "quarter",
    "semi_annual",
    "year",
]
r"""Billing interval. For consumable features, should match reset.interval."""


BillingUpdateAddItemBillingMethod = Literal[
    "prepaid",
    "usage_based",
]
r"""'prepaid' for upfront payment (seats), 'usage_based' for pay-as-you-go."""


class BillingUpdateAddItemPriceTypedDict(TypedDict):
    r"""Pricing for usage beyond included units. Omit for free features."""

    interval: BillingUpdateAddItemPriceInterval
    r"""Billing interval. For consumable features, should match reset.interval."""
    billing_method: BillingUpdateAddItemBillingMethod
    r"""'prepaid' for upfront payment (seats), 'usage_based' for pay-as-you-go."""
    amount: NotRequired[float]
    r"""Price per billing_units after included usage. Either 'amount' or 'tiers' is required."""
    additional_currencies: NotRequired[
        List[BillingUpdateAddItemAdditionalCurrencyTypedDict]
    ]
    r"""Amounts in additional currencies for this flat price. The base 'amount' is in the org's default currency. Only valid with 'amount', not 'tiers'."""
    tiers: NotRequired[List[BillingUpdateAddItemTierTypedDict]]
    r"""Tiered pricing.  Either 'amount' or 'tiers' is required."""
    tier_behavior: NotRequired[BillingUpdateAddItemTierBehavior]
    interval_count: NotRequired[float]
    r"""Number of intervals per billing cycle. Defaults to 1."""
    billing_units: NotRequired[float]
    r"""Units per price increment. Usage is rounded UP when billed (e.g. billing_units=100 means 101 rounds to 200)."""
    max_purchase: NotRequired[Nullable[float]]
    r"""Max units purchasable beyond included. E.g. included=100, max_purchase=300 allows 400 total. Null for no limit."""


class BillingUpdateAddItemPrice(BaseModel):
    r"""Pricing for usage beyond included units. Omit for free features."""

    interval: BillingUpdateAddItemPriceInterval
    r"""Billing interval. For consumable features, should match reset.interval."""

    billing_method: BillingUpdateAddItemBillingMethod
    r"""'prepaid' for upfront payment (seats), 'usage_based' for pay-as-you-go."""

    amount: Optional[float] = None
    r"""Price per billing_units after included usage. Either 'amount' or 'tiers' is required."""

    additional_currencies: Optional[List[BillingUpdateAddItemAdditionalCurrency]] = None
    r"""Amounts in additional currencies for this flat price. The base 'amount' is in the org's default currency. Only valid with 'amount', not 'tiers'."""

    tiers: Optional[List[BillingUpdateAddItemTier]] = None
    r"""Tiered pricing.  Either 'amount' or 'tiers' is required."""

    tier_behavior: Optional[BillingUpdateAddItemTierBehavior] = None

    interval_count: Optional[float] = 1
    r"""Number of intervals per billing cycle. Defaults to 1."""

    billing_units: Optional[float] = 1
    r"""Units per price increment. Usage is rounded UP when billed (e.g. billing_units=100 means 101 rounds to 200)."""

    max_purchase: OptionalNullable[float] = UNSET
    r"""Max units purchasable beyond included. E.g. included=100, max_purchase=300 allows 400 total. Null for no limit."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "amount",
                "additional_currencies",
                "tiers",
                "tier_behavior",
                "interval_count",
                "billing_units",
                "max_purchase",
            ]
        )
        nullable_fields = set(["max_purchase"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


BillingUpdateAddItemOnIncrease = Literal[
    "bill_immediately",
    "prorate_immediately",
    "prorate_next_cycle",
    "bill_next_cycle",
]
r"""Billing behavior when quantity increases mid-cycle."""


BillingUpdateAddItemOnDecrease = Literal[
    "prorate",
    "prorate_immediately",
    "prorate_next_cycle",
    "none",
    "no_prorations",
]
r"""Credit behavior when quantity decreases mid-cycle."""


class BillingUpdateAddItemProrationTypedDict(TypedDict):
    r"""Proration settings for prepaid features. Controls mid-cycle quantity change billing."""

    on_increase: BillingUpdateAddItemOnIncrease
    r"""Billing behavior when quantity increases mid-cycle."""
    on_decrease: BillingUpdateAddItemOnDecrease
    r"""Credit behavior when quantity decreases mid-cycle."""


class BillingUpdateAddItemProration(BaseModel):
    r"""Proration settings for prepaid features. Controls mid-cycle quantity change billing."""

    on_increase: BillingUpdateAddItemOnIncrease
    r"""Billing behavior when quantity increases mid-cycle."""

    on_decrease: BillingUpdateAddItemOnDecrease
    r"""Credit behavior when quantity decreases mid-cycle."""


BillingUpdateAddItemExpiryDurationType = Literal[
    "month",
    "forever",
]
r"""When rolled over units expire."""


class BillingUpdateAddItemRolloverTypedDict(TypedDict):
    r"""Rollover config for unused units. If set, unused included units carry over."""

    expiry_duration_type: BillingUpdateAddItemExpiryDurationType
    r"""When rolled over units expire."""
    max: NotRequired[float]
    r"""Max rollover units. Omit for unlimited rollover."""
    max_percentage: NotRequired[float]
    r"""Maximum rollover as a percentage (0-100) of included + prepaid grant. Mutually exclusive with max."""
    expiry_duration_length: NotRequired[float]
    r"""Number of periods before expiry."""


class BillingUpdateAddItemRollover(BaseModel):
    r"""Rollover config for unused units. If set, unused included units carry over."""

    expiry_duration_type: BillingUpdateAddItemExpiryDurationType
    r"""When rolled over units expire."""

    max: Optional[float] = None
    r"""Max rollover units. Omit for unlimited rollover."""

    max_percentage: Optional[float] = None
    r"""Maximum rollover as a percentage (0-100) of included + prepaid grant. Mutually exclusive with max."""

    expiry_duration_length: Optional[float] = None
    r"""Number of periods before expiry."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["max", "max_percentage", "expiry_duration_length"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BillingUpdateAddItemPlanItemTypedDict(TypedDict):
    r"""Configuration for a feature item in a plan, including usage limits, pricing, and rollover settings."""

    feature_id: str
    r"""The ID of the feature to configure."""
    included: NotRequired[float]
    r"""Number of free units included. Balance resets to this each interval for consumable features."""
    unlimited: NotRequired[bool]
    r"""If true, customer has unlimited access to this feature."""
    reset: NotRequired[BillingUpdateAddItemResetTypedDict]
    r"""Reset configuration for consumable features. Omit for non-consumable features like seats."""
    price: NotRequired[BillingUpdateAddItemPriceTypedDict]
    r"""Pricing for usage beyond included units. Omit for free features."""
    proration: NotRequired[BillingUpdateAddItemProrationTypedDict]
    r"""Proration settings for prepaid features. Controls mid-cycle quantity change billing."""
    rollover: NotRequired[BillingUpdateAddItemRolloverTypedDict]
    r"""Rollover config for unused units. If set, unused included units carry over."""


class BillingUpdateAddItemPlanItem(BaseModel):
    r"""Configuration for a feature item in a plan, including usage limits, pricing, and rollover settings."""

    feature_id: str
    r"""The ID of the feature to configure."""

    included: Optional[float] = None
    r"""Number of free units included. Balance resets to this each interval for consumable features."""

    unlimited: Optional[bool] = None
    r"""If true, customer has unlimited access to this feature."""

    reset: Optional[BillingUpdateAddItemReset] = None
    r"""Reset configuration for consumable features. Omit for non-consumable features like seats."""

    price: Optional[BillingUpdateAddItemPrice] = None
    r"""Pricing for usage beyond included units. Omit for free features."""

    proration: Optional[BillingUpdateAddItemProration] = None
    r"""Proration settings for prepaid features. Controls mid-cycle quantity change billing."""

    rollover: Optional[BillingUpdateAddItemRollover] = None
    r"""Rollover config for unused units. If set, unused included units carry over."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["included", "unlimited", "reset", "price", "proration", "rollover"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


BillingUpdateRemoveItemBillingMethod = Literal[
    "prepaid",
    "usage_based",
]
r"""Match items with this billing method (prepaid or usage_based)."""


BillingUpdateIntervalRemoveItemEnum2 = Literal[
    "one_off",
    "minute",
    "hour",
    "day",
    "week",
    "month",
    "quarter",
    "semi_annual",
    "year",
]


BillingUpdateIntervalRemoveItemEnum1 = Literal[
    "one_off",
    "week",
    "month",
    "quarter",
    "semi_annual",
    "year",
]


BillingUpdateIntervalUnionTypedDict = TypeAliasType(
    "BillingUpdateIntervalUnionTypedDict",
    Union[BillingUpdateIntervalRemoveItemEnum1, BillingUpdateIntervalRemoveItemEnum2],
)
r"""Match items with this interval. Accepts either a BillingInterval (price-side) or a ResetInterval (reset-side, includes day/hour/minute) so price-less items keyed by reset.interval can be disambiguated."""


BillingUpdateIntervalUnion = TypeAliasType(
    "BillingUpdateIntervalUnion",
    Union[BillingUpdateIntervalRemoveItemEnum1, BillingUpdateIntervalRemoveItemEnum2],
)
r"""Match items with this interval. Accepts either a BillingInterval (price-side) or a ResetInterval (reset-side, includes day/hour/minute) so price-less items keyed by reset.interval can be disambiguated."""


class BillingUpdatePlanItemFilterTypedDict(TypedDict):
    r"""Filter for matching plan items. All provided fields must match (AND)."""

    feature_id: NotRequired[str]
    r"""Match items linked to this feature."""
    billing_method: NotRequired[BillingUpdateRemoveItemBillingMethod]
    r"""Match items with this billing method (prepaid or usage_based)."""
    interval: NotRequired[BillingUpdateIntervalUnionTypedDict]
    r"""Match items with this interval. Accepts either a BillingInterval (price-side) or a ResetInterval (reset-side, includes day/hour/minute) so price-less items keyed by reset.interval can be disambiguated."""
    interval_count: NotRequired[int]
    r"""Match items with this interval_count. Disambiguates between items that share an interval but differ in count."""


class BillingUpdatePlanItemFilter(BaseModel):
    r"""Filter for matching plan items. All provided fields must match (AND)."""

    feature_id: Optional[str] = None
    r"""Match items linked to this feature."""

    billing_method: Optional[BillingUpdateRemoveItemBillingMethod] = None
    r"""Match items with this billing method (prepaid or usage_based)."""

    interval: Optional[BillingUpdateIntervalUnion] = None
    r"""Match items with this interval. Accepts either a BillingInterval (price-side) or a ResetInterval (reset-side, includes day/hour/minute) so price-less items keyed by reset.interval can be disambiguated."""

    interval_count: Optional[int] = None
    r"""Match items with this interval_count. Disambiguates between items that share an interval but differ in count."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["feature_id", "billing_method", "interval", "interval_count"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


BillingUpdateDurationType = Literal[
    "day",
    "month",
    "year",
]
r"""Unit of time for the trial ('day', 'month', 'year')."""


BillingUpdateOnEnd = Literal[
    "bill",
    "revert",
]
r"""Behavior when the trial ends. 'bill' charges the customer (default). 'revert' expires the trial and restores the customer's previous plan."""


class BillingUpdateFreeTrialParamsTypedDict(TypedDict):
    r"""Free trial configuration for a plan."""

    duration_length: float
    r"""Number of duration_type periods the trial lasts."""
    duration_type: NotRequired[BillingUpdateDurationType]
    r"""Unit of time for the trial ('day', 'month', 'year')."""
    card_required: NotRequired[bool]
    r"""If true, payment method required to start trial. Customer is charged after trial ends."""
    on_end: NotRequired[BillingUpdateOnEnd]
    r"""Behavior when the trial ends. 'bill' charges the customer (default). 'revert' expires the trial and restores the customer's previous plan."""


class BillingUpdateFreeTrialParams(BaseModel):
    r"""Free trial configuration for a plan."""

    duration_length: float
    r"""Number of duration_type periods the trial lasts."""

    duration_type: Optional[BillingUpdateDurationType] = "month"
    r"""Unit of time for the trial ('day', 'month', 'year')."""

    card_required: Optional[bool] = True
    r"""If true, payment method required to start trial. Customer is charged after trial ends."""

    on_end: Optional[BillingUpdateOnEnd] = None
    r"""Behavior when the trial ends. 'bill' charges the customer (default). 'revert' expires the trial and restores the customer's previous plan."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["duration_type", "card_required", "on_end"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


BillingUpdatePurchaseLimitInterval = Literal[
    "hour",
    "day",
    "week",
    "month",
]
r"""The time interval for the purchase limit window."""


class BillingUpdatePurchaseLimitTypedDict(TypedDict):
    r"""Optional rate limit to cap how often auto top-ups occur."""

    interval: BillingUpdatePurchaseLimitInterval
    r"""The time interval for the purchase limit window."""
    limit: float
    r"""Maximum number of auto top-ups allowed within the interval."""
    interval_count: NotRequired[float]
    r"""Number of intervals in the purchase limit window."""


class BillingUpdatePurchaseLimit(BaseModel):
    r"""Optional rate limit to cap how often auto top-ups occur."""

    interval: BillingUpdatePurchaseLimitInterval
    r"""The time interval for the purchase limit window."""

    limit: float
    r"""Maximum number of auto top-ups allowed within the interval."""

    interval_count: Optional[float] = 1
    r"""Number of intervals in the purchase limit window."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["interval_count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BillingUpdateAutoTopupTypedDict(TypedDict):
    feature_id: str
    r"""The ID of the feature (credit balance) to auto top-up."""
    threshold: float
    r"""When the balance drops below this threshold, an auto top-up will be purchased."""
    quantity: float
    r"""Amount of credits to add per auto top-up."""
    enabled: NotRequired[bool]
    r"""Whether auto top-up is enabled."""
    purchase_limit: NotRequired[BillingUpdatePurchaseLimitTypedDict]
    r"""Optional rate limit to cap how often auto top-ups occur."""
    invoice_mode: NotRequired[bool]
    r"""When true, auto top-up creates a send_invoice invoice instead of auto-charging."""


class BillingUpdateAutoTopup(BaseModel):
    feature_id: str
    r"""The ID of the feature (credit balance) to auto top-up."""

    threshold: float
    r"""When the balance drops below this threshold, an auto top-up will be purchased."""

    quantity: float
    r"""Amount of credits to add per auto top-up."""

    enabled: Optional[bool] = False
    r"""Whether auto top-up is enabled."""

    purchase_limit: Optional[BillingUpdatePurchaseLimit] = None
    r"""Optional rate limit to cap how often auto top-ups occur."""

    invoice_mode: Optional[bool] = None
    r"""When true, auto top-up creates a send_invoice invoice instead of auto-charging."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["enabled", "purchase_limit", "invoice_mode"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


BillingUpdateLimitType = Literal[
    "absolute",
    "usage_percentage",
]
r"""How overage_limit is interpreted: an absolute overage cap (default) or a percentage of the main-plan allowance."""


class BillingUpdateSpendLimitTypedDict(TypedDict):
    feature_id: NotRequired[str]
    r"""Optional feature ID this spend limit applies to."""
    enabled: NotRequired[bool]
    r"""Whether the overage spend limit is enabled."""
    limit_type: NotRequired[BillingUpdateLimitType]
    r"""How overage_limit is interpreted: an absolute overage cap (default) or a percentage of the main-plan allowance."""
    overage_limit: NotRequired[float]
    r"""Overage cap for the feature: absolute units, or a percent (e.g. 120) when limit_type is usage_percentage."""


class BillingUpdateSpendLimit(BaseModel):
    feature_id: Optional[str] = None
    r"""Optional feature ID this spend limit applies to."""

    enabled: Optional[bool] = False
    r"""Whether the overage spend limit is enabled."""

    limit_type: Optional[BillingUpdateLimitType] = None
    r"""How overage_limit is interpreted: an absolute overage cap (default) or a percentage of the main-plan allowance."""

    overage_limit: Optional[float] = None
    r"""Overage cap for the feature: absolute units, or a percent (e.g. 120) when limit_type is usage_percentage."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["feature_id", "enabled", "limit_type", "overage_limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


BillingUpdateUsageLimitInterval = Literal[
    "day",
    "week",
    "month",
    "year",
]
r"""Interval for the cap, aligned to the customer's billing cycle."""


class BillingUpdateUsageLimitTypedDict(TypedDict):
    feature_id: str
    r"""The feature this usage limit applies to."""
    limit: float
    r"""Maximum units allowed per interval."""
    interval: BillingUpdateUsageLimitInterval
    r"""Interval for the cap, aligned to the customer's billing cycle."""
    enabled: NotRequired[bool]
    r"""Whether this usage limit is enabled."""


class BillingUpdateUsageLimit(BaseModel):
    feature_id: str
    r"""The feature this usage limit applies to."""

    limit: float
    r"""Maximum units allowed per interval."""

    interval: BillingUpdateUsageLimitInterval
    r"""Interval for the cap, aligned to the customer's billing cycle."""

    enabled: Optional[bool] = True
    r"""Whether this usage limit is enabled."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["enabled"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


BillingUpdateThresholdType = Literal[
    "usage",
    "usage_percentage",
    "remaining",
    "remaining_percentage",
]
r"""Whether the threshold is an absolute count or a percentage of the usage allowance or remaining balance."""


class BillingUpdateUsageAlertTypedDict(TypedDict):
    threshold: float
    r"""The threshold value that triggers the alert. For usage or remaining, this is an absolute count. For usage_percentage or remaining_percentage, this is a percentage (0-100)."""
    threshold_type: BillingUpdateThresholdType
    r"""Whether the threshold is an absolute count or a percentage of the usage allowance or remaining balance."""
    feature_id: NotRequired[str]
    r"""The feature ID this alert applies to."""
    enabled: NotRequired[bool]
    r"""Whether this usage alert is enabled."""
    name: NotRequired[str]
    r"""Optional user-defined label to distinguish multiple alerts on the same feature."""


class BillingUpdateUsageAlert(BaseModel):
    threshold: float
    r"""The threshold value that triggers the alert. For usage or remaining, this is an absolute count. For usage_percentage or remaining_percentage, this is a percentage (0-100)."""

    threshold_type: BillingUpdateThresholdType
    r"""Whether the threshold is an absolute count or a percentage of the usage allowance or remaining balance."""

    feature_id: Optional[str] = None
    r"""The feature ID this alert applies to."""

    enabled: Optional[bool] = True
    r"""Whether this usage alert is enabled."""

    name: Optional[str] = None
    r"""Optional user-defined label to distinguish multiple alerts on the same feature."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["feature_id", "enabled", "name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BillingUpdateOverageAllowedTypedDict(TypedDict):
    feature_id: str
    r"""The feature ID this overage allowed control applies to."""
    enabled: NotRequired[bool]
    r"""Whether overage is allowed for this feature."""


class BillingUpdateOverageAllowed(BaseModel):
    feature_id: str
    r"""The feature ID this overage allowed control applies to."""

    enabled: Optional[bool] = False
    r"""Whether overage is allowed for this feature."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["enabled"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BillingUpdateBillingControlsTypedDict(TypedDict):
    r"""Override the plan's billing controls (auto top-ups, spend limits, usage limits, usage alerts, overage allowed) for this customer."""

    auto_topups: NotRequired[List[BillingUpdateAutoTopupTypedDict]]
    r"""List of auto top-up configurations per feature."""
    spend_limits: NotRequired[List[BillingUpdateSpendLimitTypedDict]]
    r"""List of overage spend limits per feature (caps overage spend)."""
    usage_limits: NotRequired[List[BillingUpdateUsageLimitTypedDict]]
    r"""List of hard usage caps per feature (max units per interval)."""
    usage_alerts: NotRequired[List[BillingUpdateUsageAlertTypedDict]]
    r"""List of usage alert configurations per feature."""
    overage_allowed: NotRequired[List[BillingUpdateOverageAllowedTypedDict]]
    r"""List of overage allowed controls per feature. When enabled, usage can exceed balance."""


class BillingUpdateBillingControls(BaseModel):
    r"""Override the plan's billing controls (auto top-ups, spend limits, usage limits, usage alerts, overage allowed) for this customer."""

    auto_topups: Optional[List[BillingUpdateAutoTopup]] = None
    r"""List of auto top-up configurations per feature."""

    spend_limits: Optional[List[BillingUpdateSpendLimit]] = None
    r"""List of overage spend limits per feature (caps overage spend)."""

    usage_limits: Optional[List[BillingUpdateUsageLimit]] = None
    r"""List of hard usage caps per feature (max units per interval)."""

    usage_alerts: Optional[List[BillingUpdateUsageAlert]] = None
    r"""List of usage alert configurations per feature."""

    overage_allowed: Optional[List[BillingUpdateOverageAllowed]] = None
    r"""List of overage allowed controls per feature. When enabled, usage can exceed balance."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "auto_topups",
                "spend_limits",
                "usage_limits",
                "usage_alerts",
                "overage_allowed",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BillingUpdateCustomizeTypedDict(TypedDict):
    r"""Customize the plan to attach. Can override the price, items, free trial, or a combination."""

    price: NotRequired[Nullable[BillingUpdateBasePriceTypedDict]]
    r"""Override the base price of the plan. Pass null to remove the base price."""
    items: NotRequired[List[BillingUpdateItemPlanItemTypedDict]]
    r"""Override the items in the plan (PUT-style — replaces all existing items). Mutually exclusive with add_items / remove_items / deprecated update_items."""
    add_items: NotRequired[List[BillingUpdateAddItemPlanItemTypedDict]]
    r"""Items to add to the plan."""
    remove_items: NotRequired[List[BillingUpdatePlanItemFilterTypedDict]]
    r"""Filters selecting items to remove from the plan."""
    free_trial: NotRequired[Nullable[BillingUpdateFreeTrialParamsTypedDict]]
    r"""Override the plan's default free trial. Pass an object to set a custom trial, or null to remove the trial entirely."""
    billing_controls: NotRequired[BillingUpdateBillingControlsTypedDict]
    r"""Override the plan's billing controls (auto top-ups, spend limits, usage limits, usage alerts, overage allowed) for this customer."""


class BillingUpdateCustomize(BaseModel):
    r"""Customize the plan to attach. Can override the price, items, free trial, or a combination."""

    price: OptionalNullable[BillingUpdateBasePrice] = UNSET
    r"""Override the base price of the plan. Pass null to remove the base price."""

    items: Optional[List[BillingUpdateItemPlanItem]] = None
    r"""Override the items in the plan (PUT-style — replaces all existing items). Mutually exclusive with add_items / remove_items / deprecated update_items."""

    add_items: Optional[List[BillingUpdateAddItemPlanItem]] = None
    r"""Items to add to the plan."""

    remove_items: Optional[List[BillingUpdatePlanItemFilter]] = None
    r"""Filters selecting items to remove from the plan."""

    free_trial: OptionalNullable[BillingUpdateFreeTrialParams] = UNSET
    r"""Override the plan's default free trial. Pass an object to set a custom trial, or null to remove the trial entirely."""

    billing_controls: Optional[BillingUpdateBillingControls] = None
    r"""Override the plan's billing controls (auto top-ups, spend limits, usage limits, usage alerts, overage allowed) for this customer."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "price",
                "items",
                "add_items",
                "remove_items",
                "free_trial",
                "billing_controls",
            ]
        )
        nullable_fields = set(["price", "free_trial"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class BillingUpdateInvoiceModeTypedDict(TypedDict):
    r"""Invoice mode creates a draft or open invoice and sends it to the customer, instead of charging their card immediately. This uses Stripe's send_invoice collection method."""

    enabled: bool
    r"""When true, creates an invoice and sends it to the customer instead of charging their card immediately. Uses Stripe's send_invoice collection method."""
    enable_plan_immediately: NotRequired[bool]
    r"""If true, enables the plan immediately even though the invoice is not paid yet."""
    finalize: NotRequired[bool]
    r"""If true, finalizes the invoice so it can be sent to the customer. If false, keeps it as a draft for manual review."""
    invoice_template_id: NotRequired[str]
    r"""ID of an invoice template (configured in billing settings) whose footer (e.g. bank details) is applied to the invoice."""
    net_terms_days: NotRequired[int]
    r"""Number of days the customer has to pay the invoice before it is due (Stripe days_until_due)."""


class BillingUpdateInvoiceMode(BaseModel):
    r"""Invoice mode creates a draft or open invoice and sends it to the customer, instead of charging their card immediately. This uses Stripe's send_invoice collection method."""

    enabled: bool
    r"""When true, creates an invoice and sends it to the customer instead of charging their card immediately. Uses Stripe's send_invoice collection method."""

    enable_plan_immediately: Optional[bool] = False
    r"""If true, enables the plan immediately even though the invoice is not paid yet."""

    finalize: Optional[bool] = True
    r"""If true, finalizes the invoice so it can be sent to the customer. If false, keeps it as a draft for manual review."""

    invoice_template_id: Optional[str] = None
    r"""ID of an invoice template (configured in billing settings) whose footer (e.g. bank details) is applied to the invoice."""

    net_terms_days: Optional[int] = None
    r"""Number of days the customer has to pay the invoice before it is due (Stripe days_until_due)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "enable_plan_immediately",
                "finalize",
                "invoice_template_id",
                "net_terms_days",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


BillingUpdateProrationBehavior = Literal[
    "prorate_immediately",
    "none",
]
r"""How to handle proration when updating an existing subscription. 'prorate_immediately' charges/credits prorated amounts now, 'none' skips creating any charges."""


BillingUpdateRedirectMode = Literal[
    "always",
    "if_required",
    "never",
]
r"""Controls when to return a checkout URL. 'always' returns a URL even if payment succeeds, 'if_required' only when payment action is needed, 'never' disables redirects."""


class BillingUpdateAttachDiscountTypedDict(TypedDict):
    r"""A discount to apply. Can be either a reward ID or a promotion code."""

    reward_id: NotRequired[str]
    r"""The ID of the reward to apply as a discount."""
    promotion_code: NotRequired[str]
    r"""The promotion code to apply as a discount."""


class BillingUpdateAttachDiscount(BaseModel):
    r"""A discount to apply. Can be either a reward ID or a promotion code."""

    reward_id: Optional[str] = None
    r"""The ID of the reward to apply as a discount."""

    promotion_code: Optional[str] = None
    r"""The promotion code to apply as a discount."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["reward_id", "promotion_code"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


BillingUpdateCancelAction = Literal[
    "cancel_immediately",
    "cancel_end_of_cycle",
    "uncancel",
]
r"""Action to perform for cancellation. 'cancel_immediately' cancels now with prorated refund, 'cancel_end_of_cycle' cancels at period end, 'uncancel' reverses a pending cancellation."""


class BillingUpdateRecalculateBalancesTypedDict(TypedDict):
    r"""Controls whether balances should be recalculated during the subscription update."""

    enabled: bool
    r"""If true, recalculates balances during the subscription update. Only applicable when updating feature quantities."""


class BillingUpdateRecalculateBalances(BaseModel):
    r"""Controls whether balances should be recalculated during the subscription update."""

    enabled: bool
    r"""If true, recalculates balances during the subscription update. Only applicable when updating feature quantities."""


class BillingUpdateCarryOverUsagesTypedDict(TypedDict):
    r"""Whether to carry over usages from the previous plan."""

    enabled: bool
    r"""Whether to carry over usages from the previous plan."""
    feature_ids: NotRequired[List[str]]
    r"""The IDs of the features to carry over usages for. If left undefined, all consumable features will be carried over."""


class BillingUpdateCarryOverUsages(BaseModel):
    r"""Whether to carry over usages from the previous plan."""

    enabled: bool
    r"""Whether to carry over usages from the previous plan."""

    feature_ids: Optional[List[str]] = None
    r"""The IDs of the features to carry over usages for. If left undefined, all consumable features will be carried over."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["feature_ids"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateSubscriptionParamsTypedDict(TypedDict):
    customer_id: str
    r"""The ID of the customer to attach the plan to."""
    entity_id: NotRequired[str]
    r"""The ID of the entity to attach the plan to."""
    plan_id: NotRequired[str]
    r"""The ID of the plan to update. Optional if subscription_id is provided, or if the customer has only one product."""
    feature_quantities: NotRequired[List[BillingUpdateFeatureQuantityTypedDict]]
    r"""If this plan contains prepaid features, use this field to specify the quantity of each prepaid feature. This quantity includes the included amount and billing units defined when setting up the plan."""
    version: NotRequired[float]
    r"""The version of the plan to attach."""
    customize: NotRequired[BillingUpdateCustomizeTypedDict]
    r"""Customize the plan to attach. Can override the price, items, free trial, or a combination."""
    invoice_mode: NotRequired[BillingUpdateInvoiceModeTypedDict]
    r"""Invoice mode creates a draft or open invoice and sends it to the customer, instead of charging their card immediately. This uses Stripe's send_invoice collection method."""
    proration_behavior: NotRequired[BillingUpdateProrationBehavior]
    r"""How to handle proration when updating an existing subscription. 'prorate_immediately' charges/credits prorated amounts now, 'none' skips creating any charges."""
    redirect_mode: NotRequired[BillingUpdateRedirectMode]
    r"""Controls when to return a checkout URL. 'always' returns a URL even if payment succeeds, 'if_required' only when payment action is needed, 'never' disables redirects."""
    subscription_id: NotRequired[str]
    r"""A unique ID to identify this subscription. Can be used to target specific subscriptions in update operations when a customer has multiple products with the same plan."""
    discounts: NotRequired[List[BillingUpdateAttachDiscountTypedDict]]
    r"""List of discounts to apply. Each discount can be an Autumn reward ID, Stripe coupon ID, or Stripe promotion code."""
    cancel_action: NotRequired[BillingUpdateCancelAction]
    r"""Action to perform for cancellation. 'cancel_immediately' cancels now with prorated refund, 'cancel_end_of_cycle' cancels at period end, 'uncancel' reverses a pending cancellation."""
    billing_cycle_anchor: Literal["now"]
    r"""Reset the billing cycle anchor immediately with 'now'"""
    no_billing_changes: NotRequired[bool]
    r"""If true, the subscription is updated internally without applying billing changes in Stripe."""
    recalculate_balances: NotRequired[BillingUpdateRecalculateBalancesTypedDict]
    r"""Controls whether balances should be recalculated during the subscription update."""
    carry_over_usages: NotRequired[BillingUpdateCarryOverUsagesTypedDict]
    r"""Whether to carry over usages from the previous plan."""


class UpdateSubscriptionParams(BaseModel):
    customer_id: str
    r"""The ID of the customer to attach the plan to."""

    entity_id: Optional[str] = None
    r"""The ID of the entity to attach the plan to."""

    plan_id: Optional[str] = None
    r"""The ID of the plan to update. Optional if subscription_id is provided, or if the customer has only one product."""

    feature_quantities: Optional[List[BillingUpdateFeatureQuantity]] = None
    r"""If this plan contains prepaid features, use this field to specify the quantity of each prepaid feature. This quantity includes the included amount and billing units defined when setting up the plan."""

    version: Optional[float] = None
    r"""The version of the plan to attach."""

    customize: Optional[BillingUpdateCustomize] = None
    r"""Customize the plan to attach. Can override the price, items, free trial, or a combination."""

    invoice_mode: Optional[BillingUpdateInvoiceMode] = None
    r"""Invoice mode creates a draft or open invoice and sends it to the customer, instead of charging their card immediately. This uses Stripe's send_invoice collection method."""

    proration_behavior: Optional[BillingUpdateProrationBehavior] = None
    r"""How to handle proration when updating an existing subscription. 'prorate_immediately' charges/credits prorated amounts now, 'none' skips creating any charges."""

    redirect_mode: Optional[BillingUpdateRedirectMode] = "if_required"
    r"""Controls when to return a checkout URL. 'always' returns a URL even if payment succeeds, 'if_required' only when payment action is needed, 'never' disables redirects."""

    subscription_id: Optional[str] = None
    r"""A unique ID to identify this subscription. Can be used to target specific subscriptions in update operations when a customer has multiple products with the same plan."""

    discounts: Optional[List[BillingUpdateAttachDiscount]] = None
    r"""List of discounts to apply. Each discount can be an Autumn reward ID, Stripe coupon ID, or Stripe promotion code."""

    cancel_action: Optional[BillingUpdateCancelAction] = None
    r"""Action to perform for cancellation. 'cancel_immediately' cancels now with prorated refund, 'cancel_end_of_cycle' cancels at period end, 'uncancel' reverses a pending cancellation."""

    billing_cycle_anchor: Annotated[
        Annotated[Optional[Literal["now"]], AfterValidator(validate_const("now"))],
        pydantic.Field(alias="billing_cycle_anchor"),
    ] = "now"
    r"""Reset the billing cycle anchor immediately with 'now'"""

    no_billing_changes: Optional[bool] = None
    r"""If true, the subscription is updated internally without applying billing changes in Stripe."""

    recalculate_balances: Optional[BillingUpdateRecalculateBalances] = None
    r"""Controls whether balances should be recalculated during the subscription update."""

    carry_over_usages: Optional[BillingUpdateCarryOverUsages] = None
    r"""Whether to carry over usages from the previous plan."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "entity_id",
                "plan_id",
                "feature_quantities",
                "version",
                "customize",
                "invoice_mode",
                "proration_behavior",
                "redirect_mode",
                "subscription_id",
                "discounts",
                "cancel_action",
                "billing_cycle_anchor",
                "no_billing_changes",
                "recalculate_balances",
                "carry_over_usages",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BillingUpdateInvoiceTypedDict(TypedDict):
    r"""Invoice details if an invoice was created. Only present when a charge was made."""

    status: Nullable[str]
    r"""The status of the invoice (e.g., 'paid', 'open', 'draft')."""
    stripe_id: str
    r"""The Stripe invoice ID."""
    total: float
    r"""The total amount of the invoice in cents."""
    currency: str
    r"""The three-letter ISO currency code (e.g., 'usd')."""
    hosted_invoice_url: Nullable[str]
    r"""URL to the hosted invoice page where the customer can view and pay the invoice."""


class BillingUpdateInvoice(BaseModel):
    r"""Invoice details if an invoice was created. Only present when a charge was made."""

    status: Nullable[str]
    r"""The status of the invoice (e.g., 'paid', 'open', 'draft')."""

    stripe_id: str
    r"""The Stripe invoice ID."""

    total: float
    r"""The total amount of the invoice in cents."""

    currency: str
    r"""The three-letter ISO currency code (e.g., 'usd')."""

    hosted_invoice_url: Nullable[str]
    r"""URL to the hosted invoice page where the customer can view and pay the invoice."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


BillingUpdateCode = Union[
    Literal[
        "3ds_required",
        "payment_method_required",
        "payment_failed",
    ],
    UnrecognizedStr,
]
r"""The type of action required to complete the payment."""


class BillingUpdateRequiredActionTypedDict(TypedDict):
    r"""Details about any action required to complete the payment. Present when the payment could not be processed automatically."""

    code: BillingUpdateCode
    r"""The type of action required to complete the payment."""
    reason: str
    r"""A human-readable explanation of why this action is required."""


class BillingUpdateRequiredAction(BaseModel):
    r"""Details about any action required to complete the payment. Present when the payment could not be processed automatically."""

    code: BillingUpdateCode
    r"""The type of action required to complete the payment."""

    reason: str
    r"""A human-readable explanation of why this action is required."""


class BillingUpdateResponseTypedDict(TypedDict):
    r"""OK"""

    customer_id: str
    r"""The ID of the customer."""
    payment_url: Nullable[str]
    r"""URL to redirect the customer to complete payment. Null if no payment action is required."""
    entity_id: NotRequired[str]
    r"""The ID of the entity, if the plan was attached to an entity."""
    invoice: NotRequired[BillingUpdateInvoiceTypedDict]
    r"""Invoice details if an invoice was created. Only present when a charge was made."""
    required_action: NotRequired[BillingUpdateRequiredActionTypedDict]
    r"""Details about any action required to complete the payment. Present when the payment could not be processed automatically."""


class BillingUpdateResponse(BaseModel):
    r"""OK"""

    customer_id: str
    r"""The ID of the customer."""

    payment_url: Nullable[str]
    r"""URL to redirect the customer to complete payment. Null if no payment action is required."""

    entity_id: Optional[str] = None
    r"""The ID of the entity, if the plan was attached to an entity."""

    invoice: Optional[BillingUpdateInvoice] = None
    r"""Invoice details if an invoice was created. Only present when a charge was made."""

    required_action: Optional[BillingUpdateRequiredAction] = None
    r"""Details about any action required to complete the payment. Present when the payment could not be processed automatically."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["entity_id", "invoice", "required_action"])
        nullable_fields = set(["payment_url"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    UpdateSubscriptionParams.model_rebuild()
except NameError:
    pass
