"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from autumn_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from autumn_sdk.utils import FieldMetadata, HeaderMetadata, validate_const
import pydantic
from pydantic import Field, model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Any, List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class CreateRewardGlobalsTypedDict(TypedDict):
    x_api_version: NotRequired[str]


class CreateRewardGlobals(BaseModel):
    x_api_version: Annotated[
        Optional[str],
        pydantic.Field(alias="x-api-version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = "2.3.0"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["x-api-version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


CreateRewardParamsExpiryType = Literal[
    "day",
    "week",
    "month",
    "year",
]


class ExpiryRequestTypedDict(TypedDict):
    type: CreateRewardParamsExpiryType
    length: int


class ExpiryRequest(BaseModel):
    type: CreateRewardParamsExpiryType

    length: int


class GrantRequestTypedDict(TypedDict):
    feature_id: str
    included: Nullable[float]
    expiry: Nullable[ExpiryRequestTypedDict]


class GrantRequest(BaseModel):
    feature_id: str

    included: Nullable[float]

    expiry: Nullable[ExpiryRequest]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class FeatureGrantPromoCodeRequestTypedDict(TypedDict):
    code: str
    max_uses: Nullable[int]


class FeatureGrantPromoCodeRequest(BaseModel):
    code: str

    max_uses: Nullable[int]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class FeatureGrantRequestTypedDict(TypedDict):
    id: str
    name: str
    grants: List[GrantRequestTypedDict]
    promo_codes: List[FeatureGrantPromoCodeRequestTypedDict]


class FeatureGrantRequest(BaseModel):
    id: str

    name: str

    grants: List[GrantRequest]

    promo_codes: List[FeatureGrantPromoCodeRequest]


class CreateRewardParams2TypedDict(TypedDict):
    feature_grant: FeatureGrantRequestTypedDict


class CreateRewardParams2(BaseModel):
    feature_grant: FeatureGrantRequest


CreateRewardParamsCouponType = Literal[
    "percentage_discount",
    "fixed_discount",
]


class CreateRewardParamsDuration3TypedDict(TypedDict):
    length: Nullable[Any]
    type: Literal["forever"]


class CreateRewardParamsDuration3(BaseModel):
    length: Nullable[Any]

    type: Annotated[
        Annotated[Literal["forever"], AfterValidator(validate_const("forever"))],
        pydantic.Field(alias="type"),
    ] = "forever"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class CreateRewardParamsDuration2TypedDict(TypedDict):
    length: int
    type: Literal["months"]


class CreateRewardParamsDuration2(BaseModel):
    length: int

    type: Annotated[
        Annotated[Literal["months"], AfterValidator(validate_const("months"))],
        pydantic.Field(alias="type"),
    ] = "months"


class CreateRewardParamsDuration1TypedDict(TypedDict):
    length: Nullable[Any]
    type: Literal["one_off"]


class CreateRewardParamsDuration1(BaseModel):
    length: Nullable[Any]

    type: Annotated[
        Annotated[Literal["one_off"], AfterValidator(validate_const("one_off"))],
        pydantic.Field(alias="type"),
    ] = "one_off"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


DurationTypedDict = TypeAliasType(
    "DurationTypedDict",
    Union[
        CreateRewardParamsDuration1TypedDict,
        CreateRewardParamsDuration2TypedDict,
        CreateRewardParamsDuration3TypedDict,
    ],
)


Duration = Annotated[
    Union[
        CreateRewardParamsDuration1,
        CreateRewardParamsDuration2,
        CreateRewardParamsDuration3,
    ],
    Field(discriminator="type"),
]


class CouponPromoCodeRequestTypedDict(TypedDict):
    code: str
    global_max_redemption: NotRequired[Nullable[int]]
    first_time_transaction: NotRequired[Nullable[bool]]


class CouponPromoCodeRequest(BaseModel):
    code: str

    global_max_redemption: OptionalNullable[int] = UNSET

    first_time_transaction: OptionalNullable[bool] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["global_max_redemption", "first_time_transaction"])
        nullable_fields = set(["global_max_redemption", "first_time_transaction"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class CouponRequestTypedDict(TypedDict):
    id: str
    name: str
    type: CreateRewardParamsCouponType
    value: float
    duration: DurationTypedDict
    plan_ids: Nullable[List[str]]
    promo_codes: List[CouponPromoCodeRequestTypedDict]


class CouponRequest(BaseModel):
    id: str

    name: str

    type: CreateRewardParamsCouponType

    value: float

    duration: Duration

    plan_ids: Nullable[List[str]]

    promo_codes: List[CouponPromoCodeRequest]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class CreateRewardParams1TypedDict(TypedDict):
    coupon: CouponRequestTypedDict


class CreateRewardParams1(BaseModel):
    coupon: CouponRequest


CreateRewardParamsUnionTypedDict = TypeAliasType(
    "CreateRewardParamsUnionTypedDict",
    Union[CreateRewardParams1TypedDict, CreateRewardParams2TypedDict],
)


CreateRewardParamsUnion = TypeAliasType(
    "CreateRewardParamsUnion", Union[CreateRewardParams1, CreateRewardParams2]
)


CreateRewardExpiryTypeResponse = Union[
    Literal[
        "day",
        "week",
        "month",
        "year",
    ],
    UnrecognizedStr,
]
r"""The unit of time the duration is measured in."""


class CreateRewardExpiryResponseTypedDict(TypedDict):
    type: CreateRewardExpiryTypeResponse
    r"""The unit of time the duration is measured in."""
    length: Nullable[float]
    r"""The number of `type` periods the duration lasts, or null when the type has no length (e.g. one_off, forever)."""


class CreateRewardExpiryResponse(BaseModel):
    type: CreateRewardExpiryTypeResponse
    r"""The unit of time the duration is measured in."""

    length: Nullable[float]
    r"""The number of `type` periods the duration lasts, or null when the type has no length (e.g. one_off, forever)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class CreateRewardGrantResponseTypedDict(TypedDict):
    feature_id: str
    r"""The feature ID this grant applies to."""
    included: Nullable[float]
    r"""The amount of the feature granted, or null for boolean features."""
    expiry: Nullable[CreateRewardExpiryResponseTypedDict]
    r"""How long the granted amount lasts before expiring, or null for a permanent grant."""


class CreateRewardGrantResponse(BaseModel):
    feature_id: str
    r"""The feature ID this grant applies to."""

    included: Nullable[float]
    r"""The amount of the feature granted, or null for boolean features."""

    expiry: Nullable[CreateRewardExpiryResponse]
    r"""How long the granted amount lasts before expiring, or null for a permanent grant."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class CreateRewardFeatureGrantPromoCodeResponseTypedDict(TypedDict):
    code: str
    r"""The promo code customers enter to redeem the feature grant."""
    max_uses: Nullable[float]
    r"""Maximum number of times this promo code can be redeemed, or null for unlimited."""


class CreateRewardFeatureGrantPromoCodeResponse(BaseModel):
    code: str
    r"""The promo code customers enter to redeem the feature grant."""

    max_uses: Nullable[float]
    r"""Maximum number of times this promo code can be redeemed, or null for unlimited."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class CreateRewardFeatureGrantResponseTypedDict(TypedDict):
    id: str
    r"""The unique identifier for the feature grant."""
    grants: List[CreateRewardGrantResponseTypedDict]
    r"""The feature grants awarded when the grant is redeemed."""
    promo_codes: List[CreateRewardFeatureGrantPromoCodeResponseTypedDict]
    r"""The promo codes customers can use to redeem the feature grant."""
    created_at: float
    r"""The Unix timestamp (in milliseconds) when the feature grant was created."""
    name: NotRequired[Nullable[str]]
    r"""A human-readable name for the feature grant."""


class CreateRewardFeatureGrantResponse(BaseModel):
    id: str
    r"""The unique identifier for the feature grant."""

    grants: List[CreateRewardGrantResponse]
    r"""The feature grants awarded when the grant is redeemed."""

    promo_codes: List[CreateRewardFeatureGrantPromoCodeResponse]
    r"""The promo codes customers can use to redeem the feature grant."""

    created_at: float
    r"""The Unix timestamp (in milliseconds) when the feature grant was created."""

    name: OptionalNullable[str] = UNSET
    r"""A human-readable name for the feature grant."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name"])
        nullable_fields = set(["name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class ResponseBody2TypedDict(TypedDict):
    feature_grant: CreateRewardFeatureGrantResponseTypedDict


class ResponseBody2(BaseModel):
    feature_grant: CreateRewardFeatureGrantResponse


CreateRewardCouponTypeResponse = Union[
    Literal[
        "percentage_discount",
        "fixed_discount",
        "invoice_credits",
    ],
    UnrecognizedStr,
]
r"""The type of discount: percentage_discount, fixed_discount, or invoice_credits."""


CreateRewardDurationType = Union[
    Literal[
        "one_off",
        "months",
        "forever",
    ],
    UnrecognizedStr,
]
r"""The unit of time the duration is measured in."""


class CreateRewardDurationResponseTypedDict(TypedDict):
    r"""How long the coupon applies once redeemed."""

    type: CreateRewardDurationType
    r"""The unit of time the duration is measured in."""
    length: Nullable[float]
    r"""The number of `type` periods the duration lasts, or null when the type has no length (e.g. one_off, forever)."""


class CreateRewardDurationResponse(BaseModel):
    r"""How long the coupon applies once redeemed."""

    type: CreateRewardDurationType
    r"""The unit of time the duration is measured in."""

    length: Nullable[float]
    r"""The number of `type` periods the duration lasts, or null when the type has no length (e.g. one_off, forever)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class CreateRewardCouponPromoCodeResponseTypedDict(TypedDict):
    code: str
    r"""The promo code customers enter to redeem the coupon."""
    global_max_redemption: NotRequired[Nullable[float]]
    r"""Maximum number of times this promo code can be redeemed across all customers, or null for unlimited."""
    first_time_transaction: NotRequired[Nullable[bool]]
    r"""Whether this promo code can only be applied to a customer's first transaction."""


class CreateRewardCouponPromoCodeResponse(BaseModel):
    code: str
    r"""The promo code customers enter to redeem the coupon."""

    global_max_redemption: OptionalNullable[float] = UNSET
    r"""Maximum number of times this promo code can be redeemed across all customers, or null for unlimited."""

    first_time_transaction: OptionalNullable[bool] = UNSET
    r"""Whether this promo code can only be applied to a customer's first transaction."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["global_max_redemption", "first_time_transaction"])
        nullable_fields = set(["global_max_redemption", "first_time_transaction"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class CreateRewardCouponResponseTypedDict(TypedDict):
    id: str
    r"""The unique identifier for the coupon."""
    type: CreateRewardCouponTypeResponse
    r"""The type of discount: percentage_discount, fixed_discount, or invoice_credits."""
    value: float
    r"""The discount value. A percentage for percentage_discount, or an amount for fixed_discount / invoice_credits."""
    duration: CreateRewardDurationResponseTypedDict
    r"""How long the coupon applies once redeemed."""
    plan_ids: Nullable[List[str]]
    r"""The plan IDs the coupon applies to, or null when it applies to all plans."""
    promo_codes: List[CreateRewardCouponPromoCodeResponseTypedDict]
    r"""The promo codes customers can use to redeem the coupon."""
    created_at: float
    r"""The Unix timestamp (in milliseconds) when the coupon was created."""
    name: NotRequired[Nullable[str]]
    r"""A human-readable name for the coupon."""


class CreateRewardCouponResponse(BaseModel):
    id: str
    r"""The unique identifier for the coupon."""

    type: CreateRewardCouponTypeResponse
    r"""The type of discount: percentage_discount, fixed_discount, or invoice_credits."""

    value: float
    r"""The discount value. A percentage for percentage_discount, or an amount for fixed_discount / invoice_credits."""

    duration: CreateRewardDurationResponse
    r"""How long the coupon applies once redeemed."""

    plan_ids: Nullable[List[str]]
    r"""The plan IDs the coupon applies to, or null when it applies to all plans."""

    promo_codes: List[CreateRewardCouponPromoCodeResponse]
    r"""The promo codes customers can use to redeem the coupon."""

    created_at: float
    r"""The Unix timestamp (in milliseconds) when the coupon was created."""

    name: OptionalNullable[str] = UNSET
    r"""A human-readable name for the coupon."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name"])
        nullable_fields = set(["name", "plan_ids"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class ResponseBody1TypedDict(TypedDict):
    coupon: CreateRewardCouponResponseTypedDict


class ResponseBody1(BaseModel):
    coupon: CreateRewardCouponResponse


CreateRewardResponseTypedDict = TypeAliasType(
    "CreateRewardResponseTypedDict",
    Union[ResponseBody1TypedDict, ResponseBody2TypedDict],
)
r"""OK"""


CreateRewardResponse = TypeAliasType(
    "CreateRewardResponse", Union[ResponseBody1, ResponseBody2]
)
r"""OK"""


try:
    CreateRewardParamsDuration3.model_rebuild()
except NameError:
    pass
try:
    CreateRewardParamsDuration2.model_rebuild()
except NameError:
    pass
try:
    CreateRewardParamsDuration1.model_rebuild()
except NameError:
    pass
