"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from autumn_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Any, Dict, List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


CustomerDataInterval = Literal[
    "hour",
    "day",
    "week",
    "month",
]
r"""The time interval for the purchase limit window."""


class CustomerDataPurchaseLimitTypedDict(TypedDict):
    r"""Optional rate limit to cap how often auto top-ups occur."""

    interval: CustomerDataInterval
    r"""The time interval for the purchase limit window."""
    limit: float
    r"""Maximum number of auto top-ups allowed within the interval."""
    interval_count: NotRequired[float]
    r"""Number of intervals in the purchase limit window."""


class CustomerDataPurchaseLimit(BaseModel):
    r"""Optional rate limit to cap how often auto top-ups occur."""

    interval: CustomerDataInterval
    r"""The time interval for the purchase limit window."""

    limit: float
    r"""Maximum number of auto top-ups allowed within the interval."""

    interval_count: Optional[float] = 1
    r"""Number of intervals in the purchase limit window."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["interval_count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CustomerDataAutoTopupTypedDict(TypedDict):
    feature_id: str
    r"""The ID of the feature (credit balance) to auto top-up."""
    threshold: float
    r"""When the balance drops below this threshold, an auto top-up will be purchased."""
    quantity: float
    r"""Amount of credits to add per auto top-up."""
    enabled: NotRequired[bool]
    r"""Whether auto top-up is enabled."""
    purchase_limit: NotRequired[CustomerDataPurchaseLimitTypedDict]
    r"""Optional rate limit to cap how often auto top-ups occur."""
    invoice_mode: NotRequired[bool]
    r"""When true, auto top-up creates a send_invoice invoice instead of auto-charging."""


class CustomerDataAutoTopup(BaseModel):
    feature_id: str
    r"""The ID of the feature (credit balance) to auto top-up."""

    threshold: float
    r"""When the balance drops below this threshold, an auto top-up will be purchased."""

    quantity: float
    r"""Amount of credits to add per auto top-up."""

    enabled: Optional[bool] = False
    r"""Whether auto top-up is enabled."""

    purchase_limit: Optional[CustomerDataPurchaseLimit] = None
    r"""Optional rate limit to cap how often auto top-ups occur."""

    invoice_mode: Optional[bool] = None
    r"""When true, auto top-up creates a send_invoice invoice instead of auto-charging."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["enabled", "purchase_limit", "invoice_mode"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CustomerDataSpendLimitTypedDict(TypedDict):
    feature_id: NotRequired[str]
    r"""Optional feature ID this spend limit applies to."""
    enabled: NotRequired[bool]
    r"""Whether this spend limit is enabled."""
    overage_limit: NotRequired[float]
    r"""Maximum allowed overage spend for the target feature."""


class CustomerDataSpendLimit(BaseModel):
    feature_id: Optional[str] = None
    r"""Optional feature ID this spend limit applies to."""

    enabled: Optional[bool] = False
    r"""Whether this spend limit is enabled."""

    overage_limit: Optional[float] = None
    r"""Maximum allowed overage spend for the target feature."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["feature_id", "enabled", "overage_limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


CustomerDataThresholdType = Literal[
    "usage",
    "usage_percentage",
]
r"""Whether the threshold is an absolute usage count or a percentage of the usage allowance."""


class CustomerDataUsageAlertTypedDict(TypedDict):
    threshold: float
    r"""The threshold value that triggers the alert. For usage, this is an absolute count. For usage_percentage, this is a percentage (0-100)."""
    threshold_type: CustomerDataThresholdType
    r"""Whether the threshold is an absolute usage count or a percentage of the usage allowance."""
    feature_id: NotRequired[str]
    r"""The feature ID this alert applies to."""
    enabled: NotRequired[bool]
    r"""Whether this usage alert is enabled."""
    name: NotRequired[str]
    r"""Optional user-defined label to distinguish multiple alerts on the same feature."""


class CustomerDataUsageAlert(BaseModel):
    threshold: float
    r"""The threshold value that triggers the alert. For usage, this is an absolute count. For usage_percentage, this is a percentage (0-100)."""

    threshold_type: CustomerDataThresholdType
    r"""Whether the threshold is an absolute usage count or a percentage of the usage allowance."""

    feature_id: Optional[str] = None
    r"""The feature ID this alert applies to."""

    enabled: Optional[bool] = True
    r"""Whether this usage alert is enabled."""

    name: Optional[str] = None
    r"""Optional user-defined label to distinguish multiple alerts on the same feature."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["feature_id", "enabled", "name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CustomerDataOverageAllowedTypedDict(TypedDict):
    feature_id: str
    r"""The feature ID this overage allowed control applies to."""
    enabled: NotRequired[bool]
    r"""Whether overage is allowed for this feature."""


class CustomerDataOverageAllowed(BaseModel):
    feature_id: str
    r"""The feature ID this overage allowed control applies to."""

    enabled: Optional[bool] = False
    r"""Whether overage is allowed for this feature."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["enabled"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CustomerDataBillingControlsTypedDict(TypedDict):
    r"""Billing controls for the customer (auto top-ups, etc.)"""

    auto_topups: NotRequired[List[CustomerDataAutoTopupTypedDict]]
    r"""List of auto top-up configurations per feature."""
    spend_limits: NotRequired[List[CustomerDataSpendLimitTypedDict]]
    r"""List of overage spend limits per feature."""
    usage_alerts: NotRequired[List[CustomerDataUsageAlertTypedDict]]
    r"""List of usage alert configurations per feature."""
    overage_allowed: NotRequired[List[CustomerDataOverageAllowedTypedDict]]
    r"""List of overage allowed controls per feature. When enabled, usage can exceed balance."""


class CustomerDataBillingControls(BaseModel):
    r"""Billing controls for the customer (auto top-ups, etc.)"""

    auto_topups: Optional[List[CustomerDataAutoTopup]] = None
    r"""List of auto top-up configurations per feature."""

    spend_limits: Optional[List[CustomerDataSpendLimit]] = None
    r"""List of overage spend limits per feature."""

    usage_alerts: Optional[List[CustomerDataUsageAlert]] = None
    r"""List of usage alert configurations per feature."""

    overage_allowed: Optional[List[CustomerDataOverageAllowed]] = None
    r"""List of overage allowed controls per feature. When enabled, usage can exceed balance."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["auto_topups", "spend_limits", "usage_alerts", "overage_allowed"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CustomerDataTypedDict(TypedDict):
    r"""Customer details to set when creating a customer"""

    name: NotRequired[Nullable[str]]
    r"""Customer's name"""
    email: NotRequired[Nullable[str]]
    r"""Customer's email address"""
    fingerprint: NotRequired[Nullable[str]]
    r"""Unique identifier (eg, serial number) to detect duplicate customers and prevent free trial abuse"""
    metadata: NotRequired[Nullable[Dict[str, Any]]]
    r"""Additional metadata for the customer"""
    stripe_id: NotRequired[Nullable[str]]
    r"""Stripe customer ID if you already have one"""
    create_in_stripe: NotRequired[bool]
    r"""Whether to create the customer in Stripe"""
    auto_enable_plan_id: NotRequired[str]
    r"""The ID of the free plan to auto-enable for the customer"""
    send_email_receipts: NotRequired[bool]
    r"""Whether to send email receipts to this customer"""
    billing_controls: NotRequired[CustomerDataBillingControlsTypedDict]
    r"""Billing controls for the customer (auto top-ups, etc.)"""


class CustomerData(BaseModel):
    r"""Customer details to set when creating a customer"""

    name: OptionalNullable[str] = UNSET
    r"""Customer's name"""

    email: OptionalNullable[str] = UNSET
    r"""Customer's email address"""

    fingerprint: OptionalNullable[str] = UNSET
    r"""Unique identifier (eg, serial number) to detect duplicate customers and prevent free trial abuse"""

    metadata: OptionalNullable[Dict[str, Any]] = UNSET
    r"""Additional metadata for the customer"""

    stripe_id: OptionalNullable[str] = UNSET
    r"""Stripe customer ID if you already have one"""

    create_in_stripe: Optional[bool] = None
    r"""Whether to create the customer in Stripe"""

    auto_enable_plan_id: Optional[str] = None
    r"""The ID of the free plan to auto-enable for the customer"""

    send_email_receipts: Optional[bool] = None
    r"""Whether to send email receipts to this customer"""

    billing_controls: Optional[CustomerDataBillingControls] = None
    r"""Billing controls for the customer (auto top-ups, etc.)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "name",
                "email",
                "fingerprint",
                "metadata",
                "stripe_id",
                "create_in_stripe",
                "auto_enable_plan_id",
                "send_email_receipts",
                "billing_controls",
            ]
        )
        nullable_fields = set(["name", "email", "fingerprint", "metadata", "stripe_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
