"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from autumn_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from autumn_sdk.utils import FieldMetadata, HeaderMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class GetFeatureGlobalsTypedDict(TypedDict):
    x_api_version: NotRequired[str]


class GetFeatureGlobals(BaseModel):
    x_api_version: Annotated[
        Optional[str],
        pydantic.Field(alias="x-api-version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = "2.1"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["x-api-version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetFeatureParamsTypedDict(TypedDict):
    feature_id: str
    r"""The ID of the feature."""


class GetFeatureParams(BaseModel):
    feature_id: str
    r"""The ID of the feature."""


GetFeatureType = Union[
    Literal[
        "boolean",
        "metered",
        "credit_system",
    ],
    UnrecognizedStr,
]
r"""Feature type: 'boolean' for on/off access, 'metered' for usage-tracked features, 'credit_system' for unified credit pools."""


class GetFeatureCreditSchemaTypedDict(TypedDict):
    metered_feature_id: str
    r"""ID of the metered feature that draws from this credit system."""
    credit_cost: float
    r"""Credits consumed per unit of the metered feature."""


class GetFeatureCreditSchema(BaseModel):
    metered_feature_id: str
    r"""ID of the metered feature that draws from this credit system."""

    credit_cost: float
    r"""Credits consumed per unit of the metered feature."""


class GetFeatureDisplayTypedDict(TypedDict):
    r"""Display names for the feature in billing UI and customer-facing components."""

    singular: NotRequired[Nullable[str]]
    r"""Singular form for UI display (e.g., 'API call', 'seat')."""
    plural: NotRequired[Nullable[str]]
    r"""Plural form for UI display (e.g., 'API calls', 'seats')."""


class GetFeatureDisplay(BaseModel):
    r"""Display names for the feature in billing UI and customer-facing components."""

    singular: OptionalNullable[str] = UNSET
    r"""Singular form for UI display (e.g., 'API call', 'seat')."""

    plural: OptionalNullable[str] = UNSET
    r"""Plural form for UI display (e.g., 'API calls', 'seats')."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["singular", "plural"])
        nullable_fields = set(["singular", "plural"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class GetFeatureResponseTypedDict(TypedDict):
    r"""OK"""

    id: str
    r"""The unique identifier for this feature, used in /check and /track calls."""
    name: str
    r"""Human-readable name displayed in the dashboard and billing UI."""
    type: GetFeatureType
    r"""Feature type: 'boolean' for on/off access, 'metered' for usage-tracked features, 'credit_system' for unified credit pools."""
    consumable: bool
    r"""For metered features: true if usage resets periodically (API calls, credits), false if allocated persistently (seats, storage)."""
    archived: bool
    r"""Whether the feature is archived and hidden from the dashboard."""
    event_names: NotRequired[List[str]]
    r"""Event names that trigger this feature's balance. Allows multiple features to respond to a single event."""
    credit_schema: NotRequired[List[GetFeatureCreditSchemaTypedDict]]
    r"""For credit_system features: maps metered features to their credit costs."""
    display: NotRequired[GetFeatureDisplayTypedDict]
    r"""Display names for the feature in billing UI and customer-facing components."""


class GetFeatureResponse(BaseModel):
    r"""OK"""

    id: str
    r"""The unique identifier for this feature, used in /check and /track calls."""

    name: str
    r"""Human-readable name displayed in the dashboard and billing UI."""

    type: GetFeatureType
    r"""Feature type: 'boolean' for on/off access, 'metered' for usage-tracked features, 'credit_system' for unified credit pools."""

    consumable: bool
    r"""For metered features: true if usage resets periodically (API calls, credits), false if allocated persistently (seats, storage)."""

    archived: bool
    r"""Whether the feature is archived and hidden from the dashboard."""

    event_names: Optional[List[str]] = None
    r"""Event names that trigger this feature's balance. Allows multiple features to respond to a single event."""

    credit_schema: Optional[List[GetFeatureCreditSchema]] = None
    r"""For credit_system features: maps metered features to their credit costs."""

    display: Optional[GetFeatureDisplay] = None
    r"""Display names for the feature in billing UI and customer-facing components."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["event_names", "credit_schema", "display"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
