"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .balance import Balance, BalanceTypedDict
from .plan import Plan, PlanTypedDict
from autumn_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from autumn_sdk.utils import FieldMetadata, HeaderMetadata
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class ListCustomersGlobalsTypedDict(TypedDict):
    x_api_version: NotRequired[str]


class ListCustomersGlobals(BaseModel):
    x_api_version: Annotated[
        Optional[str],
        pydantic.Field(alias="x-api-version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = "2.2.0"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["x-api-version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListCustomersPlanTypedDict(TypedDict):
    id: str
    versions: NotRequired[List[float]]


class ListCustomersPlan(BaseModel):
    id: str

    versions: Optional[List[float]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["versions"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


SubscriptionStatus = Literal[
    "active",
    "scheduled",
]
r"""Filter by customer product status. Defaults to active and scheduled"""


class ListCustomersParamsTypedDict(TypedDict):
    offset: NotRequired[int]
    r"""Number of items to skip"""
    limit: NotRequired[int]
    r"""Number of items to return. Default 10, max 1000."""
    plans: NotRequired[List[ListCustomersPlanTypedDict]]
    r"""Filter by plan ID and version. Returns customers with active subscriptions to this plan."""
    subscription_status: NotRequired[SubscriptionStatus]
    r"""Filter by customer product status. Defaults to active and scheduled"""
    search: NotRequired[str]
    r"""Search customers by id, name, or email"""


class ListCustomersParams(BaseModel):
    offset: Optional[int] = 0
    r"""Number of items to skip"""

    limit: Optional[int] = 10
    r"""Number of items to return. Default 10, max 1000."""

    plans: Optional[List[ListCustomersPlan]] = None
    r"""Filter by plan ID and version. Returns customers with active subscriptions to this plan."""

    subscription_status: Optional[SubscriptionStatus] = None
    r"""Filter by customer product status. Defaults to active and scheduled"""

    search: Optional[str] = None
    r"""Search customers by id, name, or email"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["offset", "limit", "plans", "subscription_status", "search"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListCustomersEnv = Union[
    Literal[
        "sandbox",
        "live",
    ],
    UnrecognizedStr,
]
r"""The environment this customer was created in."""


ListCustomersInterval = Union[
    Literal[
        "hour",
        "day",
        "week",
        "month",
    ],
    UnrecognizedStr,
]
r"""The time interval for the purchase limit window."""


class ListCustomersPurchaseLimitTypedDict(TypedDict):
    r"""Optional rate limit to cap how often auto top-ups occur."""

    interval: ListCustomersInterval
    r"""The time interval for the purchase limit window."""
    limit: float
    r"""Maximum number of auto top-ups allowed within the interval."""
    interval_count: NotRequired[float]
    r"""Number of intervals in the purchase limit window."""


class ListCustomersPurchaseLimit(BaseModel):
    r"""Optional rate limit to cap how often auto top-ups occur."""

    interval: ListCustomersInterval
    r"""The time interval for the purchase limit window."""

    limit: float
    r"""Maximum number of auto top-ups allowed within the interval."""

    interval_count: Optional[float] = 1
    r"""Number of intervals in the purchase limit window."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["interval_count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListCustomersAutoTopupTypedDict(TypedDict):
    feature_id: str
    r"""The ID of the feature (credit balance) to auto top-up."""
    threshold: float
    r"""When the balance drops below this threshold, an auto top-up will be purchased."""
    quantity: float
    r"""Amount of credits to add per auto top-up."""
    enabled: NotRequired[bool]
    r"""Whether auto top-up is enabled."""
    purchase_limit: NotRequired[ListCustomersPurchaseLimitTypedDict]
    r"""Optional rate limit to cap how often auto top-ups occur."""


class ListCustomersAutoTopup(BaseModel):
    feature_id: str
    r"""The ID of the feature (credit balance) to auto top-up."""

    threshold: float
    r"""When the balance drops below this threshold, an auto top-up will be purchased."""

    quantity: float
    r"""Amount of credits to add per auto top-up."""

    enabled: Optional[bool] = False
    r"""Whether auto top-up is enabled."""

    purchase_limit: Optional[ListCustomersPurchaseLimit] = None
    r"""Optional rate limit to cap how often auto top-ups occur."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["enabled", "purchase_limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListCustomersSpendLimitTypedDict(TypedDict):
    feature_id: NotRequired[str]
    r"""Optional feature ID this spend limit applies to."""
    enabled: NotRequired[bool]
    r"""Whether this spend limit is enabled."""
    overage_limit: NotRequired[float]
    r"""Maximum allowed overage spend for the target feature."""


class ListCustomersSpendLimit(BaseModel):
    feature_id: Optional[str] = None
    r"""Optional feature ID this spend limit applies to."""

    enabled: Optional[bool] = False
    r"""Whether this spend limit is enabled."""

    overage_limit: Optional[float] = None
    r"""Maximum allowed overage spend for the target feature."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["feature_id", "enabled", "overage_limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListCustomersThresholdType = Union[
    Literal[
        "usage",
        "usage_percentage",
    ],
    UnrecognizedStr,
]
r"""Whether the threshold is an absolute usage count or a percentage of the usage allowance."""


class ListCustomersUsageAlertTypedDict(TypedDict):
    threshold: float
    r"""The threshold value that triggers the alert. For usage, this is an absolute count. For usage_percentage, this is a percentage (0-100)."""
    threshold_type: ListCustomersThresholdType
    r"""Whether the threshold is an absolute usage count or a percentage of the usage allowance."""
    feature_id: NotRequired[str]
    r"""The feature ID this alert applies to. If omitted, the alert applies globally."""
    enabled: NotRequired[bool]
    r"""Whether this usage alert is enabled."""
    name: NotRequired[str]
    r"""Optional user-defined label to distinguish multiple alerts on the same feature."""


class ListCustomersUsageAlert(BaseModel):
    threshold: float
    r"""The threshold value that triggers the alert. For usage, this is an absolute count. For usage_percentage, this is a percentage (0-100)."""

    threshold_type: ListCustomersThresholdType
    r"""Whether the threshold is an absolute usage count or a percentage of the usage allowance."""

    feature_id: Optional[str] = None
    r"""The feature ID this alert applies to. If omitted, the alert applies globally."""

    enabled: Optional[bool] = True
    r"""Whether this usage alert is enabled."""

    name: Optional[str] = None
    r"""Optional user-defined label to distinguish multiple alerts on the same feature."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["feature_id", "enabled", "name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListCustomersBillingControlsTypedDict(TypedDict):
    r"""Billing controls for the customer (auto top-ups, etc.)"""

    auto_topups: NotRequired[List[ListCustomersAutoTopupTypedDict]]
    r"""List of auto top-up configurations per feature."""
    spend_limits: NotRequired[List[ListCustomersSpendLimitTypedDict]]
    r"""List of overage spend limits per feature."""
    usage_alerts: NotRequired[List[ListCustomersUsageAlertTypedDict]]
    r"""List of usage alert configurations per feature."""


class ListCustomersBillingControls(BaseModel):
    r"""Billing controls for the customer (auto top-ups, etc.)"""

    auto_topups: Optional[List[ListCustomersAutoTopup]] = None
    r"""List of auto top-up configurations per feature."""

    spend_limits: Optional[List[ListCustomersSpendLimit]] = None
    r"""List of overage spend limits per feature."""

    usage_alerts: Optional[List[ListCustomersUsageAlert]] = None
    r"""List of usage alert configurations per feature."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["auto_topups", "spend_limits", "usage_alerts"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListCustomersStatus = Union[
    Literal[
        "active",
        "scheduled",
    ],
    UnrecognizedStr,
]
r"""Current status of the subscription."""


class ListCustomersSubscriptionTypedDict(TypedDict):
    id: str
    r"""The unique identifier of this subscription. If a subscription_id was provided at attach time, it is used; otherwise, falls back to the internal ID."""
    plan_id: str
    r"""The unique identifier of the subscribed plan."""
    auto_enable: bool
    r"""Whether the plan was automatically enabled for the customer."""
    add_on: bool
    r"""Whether this is an add-on plan rather than a base subscription."""
    status: ListCustomersStatus
    r"""Current status of the subscription."""
    past_due: bool
    r"""Whether the subscription has overdue payments."""
    canceled_at: Nullable[float]
    r"""Timestamp when the subscription was canceled, or null if not canceled."""
    expires_at: Nullable[float]
    r"""Timestamp when the subscription will expire, or null if no expiry set."""
    trial_ends_at: Nullable[float]
    r"""Timestamp when the trial period ends, or null if not on trial."""
    started_at: float
    r"""Timestamp when the subscription started."""
    current_period_start: Nullable[float]
    r"""Start timestamp of the current billing period."""
    current_period_end: Nullable[float]
    r"""End timestamp of the current billing period."""
    quantity: float
    r"""Number of units of this subscription (for per-seat plans)."""
    plan: NotRequired[PlanTypedDict]


class ListCustomersSubscription(BaseModel):
    id: str
    r"""The unique identifier of this subscription. If a subscription_id was provided at attach time, it is used; otherwise, falls back to the internal ID."""

    plan_id: str
    r"""The unique identifier of the subscribed plan."""

    auto_enable: bool
    r"""Whether the plan was automatically enabled for the customer."""

    add_on: bool
    r"""Whether this is an add-on plan rather than a base subscription."""

    status: ListCustomersStatus
    r"""Current status of the subscription."""

    past_due: bool
    r"""Whether the subscription has overdue payments."""

    canceled_at: Nullable[float]
    r"""Timestamp when the subscription was canceled, or null if not canceled."""

    expires_at: Nullable[float]
    r"""Timestamp when the subscription will expire, or null if no expiry set."""

    trial_ends_at: Nullable[float]
    r"""Timestamp when the trial period ends, or null if not on trial."""

    started_at: float
    r"""Timestamp when the subscription started."""

    current_period_start: Nullable[float]
    r"""Start timestamp of the current billing period."""

    current_period_end: Nullable[float]
    r"""End timestamp of the current billing period."""

    quantity: float
    r"""Number of units of this subscription (for per-seat plans)."""

    plan: Optional[Plan] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["plan"])
        nullable_fields = set(
            [
                "canceled_at",
                "expires_at",
                "trial_ends_at",
                "current_period_start",
                "current_period_end",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class ListCustomersPurchaseTypedDict(TypedDict):
    plan_id: str
    r"""The unique identifier of the purchased plan."""
    expires_at: Nullable[float]
    r"""Timestamp when the purchase expires, or null for lifetime access."""
    started_at: float
    r"""Timestamp when the purchase was made."""
    quantity: float
    r"""Number of units purchased."""
    plan: NotRequired[PlanTypedDict]


class ListCustomersPurchase(BaseModel):
    plan_id: str
    r"""The unique identifier of the purchased plan."""

    expires_at: Nullable[float]
    r"""Timestamp when the purchase expires, or null for lifetime access."""

    started_at: float
    r"""Timestamp when the purchase was made."""

    quantity: float
    r"""Number of units purchased."""

    plan: Optional[Plan] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["plan"])
        nullable_fields = set(["expires_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


ListCustomersType = Union[
    Literal[
        "boolean",
        "metered",
        "credit_system",
    ],
    UnrecognizedStr,
]
r"""Feature type: 'boolean' for on/off access, 'metered' for usage-tracked features, 'credit_system' for unified credit pools."""


class ListCustomersCreditSchemaTypedDict(TypedDict):
    metered_feature_id: str
    r"""ID of the metered feature that draws from this credit system."""
    credit_cost: float
    r"""Credits consumed per unit of the metered feature."""


class ListCustomersCreditSchema(BaseModel):
    metered_feature_id: str
    r"""ID of the metered feature that draws from this credit system."""

    credit_cost: float
    r"""Credits consumed per unit of the metered feature."""


class ListCustomersDisplayTypedDict(TypedDict):
    r"""Display names for the feature in billing UI and customer-facing components."""

    singular: NotRequired[Nullable[str]]
    r"""Singular form for UI display (e.g., 'API call', 'seat')."""
    plural: NotRequired[Nullable[str]]
    r"""Plural form for UI display (e.g., 'API calls', 'seats')."""


class ListCustomersDisplay(BaseModel):
    r"""Display names for the feature in billing UI and customer-facing components."""

    singular: OptionalNullable[str] = UNSET
    r"""Singular form for UI display (e.g., 'API call', 'seat')."""

    plural: OptionalNullable[str] = UNSET
    r"""Plural form for UI display (e.g., 'API calls', 'seats')."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["singular", "plural"])
        nullable_fields = set(["singular", "plural"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class ListCustomersFeatureTypedDict(TypedDict):
    r"""The full feature object if expanded."""

    id: str
    r"""The unique identifier for this feature, used in /check and /track calls."""
    name: str
    r"""Human-readable name displayed in the dashboard and billing UI."""
    type: ListCustomersType
    r"""Feature type: 'boolean' for on/off access, 'metered' for usage-tracked features, 'credit_system' for unified credit pools."""
    consumable: bool
    r"""For metered features: true if usage resets periodically (API calls, credits), false if allocated persistently (seats, storage)."""
    archived: bool
    r"""Whether the feature is archived and hidden from the dashboard."""
    event_names: NotRequired[List[str]]
    r"""Event names that trigger this feature's balance. Allows multiple features to respond to a single event."""
    credit_schema: NotRequired[List[ListCustomersCreditSchemaTypedDict]]
    r"""For credit_system features: maps metered features to their credit costs."""
    display: NotRequired[ListCustomersDisplayTypedDict]
    r"""Display names for the feature in billing UI and customer-facing components."""


class ListCustomersFeature(BaseModel):
    r"""The full feature object if expanded."""

    id: str
    r"""The unique identifier for this feature, used in /check and /track calls."""

    name: str
    r"""Human-readable name displayed in the dashboard and billing UI."""

    type: ListCustomersType
    r"""Feature type: 'boolean' for on/off access, 'metered' for usage-tracked features, 'credit_system' for unified credit pools."""

    consumable: bool
    r"""For metered features: true if usage resets periodically (API calls, credits), false if allocated persistently (seats, storage)."""

    archived: bool
    r"""Whether the feature is archived and hidden from the dashboard."""

    event_names: Optional[List[str]] = None
    r"""Event names that trigger this feature's balance. Allows multiple features to respond to a single event."""

    credit_schema: Optional[List[ListCustomersCreditSchema]] = None
    r"""For credit_system features: maps metered features to their credit costs."""

    display: Optional[ListCustomersDisplay] = None
    r"""Display names for the feature in billing UI and customer-facing components."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["event_names", "credit_schema", "display"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListCustomersFlagsTypedDict(TypedDict):
    id: str
    r"""The unique identifier for this flag."""
    plan_id: Nullable[str]
    r"""The plan ID this flag originates from, or null for standalone flags."""
    expires_at: Nullable[float]
    r"""Timestamp when this flag expires, or null for no expiration."""
    feature_id: str
    r"""The feature ID this flag is for."""
    feature: NotRequired[ListCustomersFeatureTypedDict]
    r"""The full feature object if expanded."""


class ListCustomersFlags(BaseModel):
    id: str
    r"""The unique identifier for this flag."""

    plan_id: Nullable[str]
    r"""The plan ID this flag originates from, or null for standalone flags."""

    expires_at: Nullable[float]
    r"""Timestamp when this flag expires, or null for no expiration."""

    feature_id: str
    r"""The feature ID this flag is for."""

    feature: Optional[ListCustomersFeature] = None
    r"""The full feature object if expanded."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["feature"])
        nullable_fields = set(["plan_id", "expires_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class ListCustomersListTypedDict(TypedDict):
    id: Nullable[str]
    r"""Your unique identifier for the customer."""
    name: Nullable[str]
    r"""The name of the customer."""
    email: Nullable[str]
    r"""The email address of the customer."""
    created_at: float
    r"""Timestamp of customer creation in milliseconds since epoch."""
    fingerprint: Nullable[str]
    r"""A unique identifier (eg. serial number) to de-duplicate customers across devices or browsers. For example: apple device ID."""
    stripe_id: Nullable[str]
    r"""Stripe customer ID."""
    env: ListCustomersEnv
    r"""The environment this customer was created in."""
    metadata: Dict[str, Any]
    r"""The metadata for the customer."""
    send_email_receipts: bool
    r"""Whether to send email receipts to the customer."""
    billing_controls: ListCustomersBillingControlsTypedDict
    r"""Billing controls for the customer (auto top-ups, etc.)"""
    subscriptions: List[ListCustomersSubscriptionTypedDict]
    r"""Active and scheduled recurring plans that this customer has attached."""
    purchases: List[ListCustomersPurchaseTypedDict]
    r"""One-time purchases made by the customer."""
    balances: Dict[str, BalanceTypedDict]
    r"""Feature balances keyed by feature ID, showing usage limits and remaining amounts."""
    flags: Dict[str, ListCustomersFlagsTypedDict]
    r"""Boolean feature flags keyed by feature ID, showing enabled access for on/off features."""


class ListCustomersList(BaseModel):
    id: Nullable[str]
    r"""Your unique identifier for the customer."""

    name: Nullable[str]
    r"""The name of the customer."""

    email: Nullable[str]
    r"""The email address of the customer."""

    created_at: float
    r"""Timestamp of customer creation in milliseconds since epoch."""

    fingerprint: Nullable[str]
    r"""A unique identifier (eg. serial number) to de-duplicate customers across devices or browsers. For example: apple device ID."""

    stripe_id: Nullable[str]
    r"""Stripe customer ID."""

    env: ListCustomersEnv
    r"""The environment this customer was created in."""

    metadata: Dict[str, Any]
    r"""The metadata for the customer."""

    send_email_receipts: bool
    r"""Whether to send email receipts to the customer."""

    billing_controls: ListCustomersBillingControls
    r"""Billing controls for the customer (auto top-ups, etc.)"""

    subscriptions: List[ListCustomersSubscription]
    r"""Active and scheduled recurring plans that this customer has attached."""

    purchases: List[ListCustomersPurchase]
    r"""One-time purchases made by the customer."""

    balances: Dict[str, Balance]
    r"""Feature balances keyed by feature ID, showing usage limits and remaining amounts."""

    flags: Dict[str, ListCustomersFlags]
    r"""Boolean feature flags keyed by feature ID, showing enabled access for on/off features."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class ListCustomersResponseTypedDict(TypedDict):
    r"""OK"""

    list: List[ListCustomersListTypedDict]
    r"""Array of items for current page"""
    has_more: bool
    r"""Whether more results exist after this page"""
    offset: float
    r"""Current offset position"""
    limit: float
    r"""Limit passed in the request"""
    total: float
    r"""Total number of items returned in the current page"""
    total_count: float
    r"""Total number of customers available in the current organization and environment"""
    total_filtered_count: float
    r"""Total number of customers matching the current filter before pagination is applied"""


class ListCustomersResponse(BaseModel):
    r"""OK"""

    list: List[ListCustomersList]
    r"""Array of items for current page"""

    has_more: bool
    r"""Whether more results exist after this page"""

    offset: float
    r"""Current offset position"""

    limit: float
    r"""Limit passed in the request"""

    total: float
    r"""Total number of items returned in the current page"""

    total_count: float
    r"""Total number of customers available in the current organization and environment"""

    total_filtered_count: float
    r"""Total number of customers matching the current filter before pagination is applied"""
