"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from autumn_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from autumn_sdk.utils import FieldMetadata, HeaderMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class PayInvoiceGlobalsTypedDict(TypedDict):
    x_api_version: NotRequired[str]


class PayInvoiceGlobals(BaseModel):
    x_api_version: Annotated[
        Optional[str],
        pydantic.Field(alias="x-api-version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = "2.4.0"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["x-api-version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PayInvoiceParamsTypedDict(TypedDict):
    invoice_id: str
    r"""The Autumn invoice ID to mark as paid."""


class PayInvoiceParams(BaseModel):
    invoice_id: str
    r"""The Autumn invoice ID to mark as paid."""


PayInvoiceProcessorType = Union[
    Literal[
        "stripe",
        "revenuecat",
    ],
    UnrecognizedStr,
]
r"""The billing processor that owns this invoice."""


class PayInvoiceEntityTypedDict(TypedDict):
    entity_id: str
    r"""The entity this share of the line item is attributed to"""
    quantity: Nullable[float]
    r"""Quantity charged to this entity. Null on fixed-price lines."""
    amount: float
    r"""Amount attributed to this entity, pre-discount and pre-tax"""


class PayInvoiceEntity(BaseModel):
    entity_id: str
    r"""The entity this share of the line item is attributed to"""

    quantity: Nullable[float]
    r"""Quantity charged to this entity. Null on fixed-price lines."""

    amount: float
    r"""Amount attributed to this entity, pre-discount and pre-tax"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class PayInvoiceItemTypedDict(TypedDict):
    id: str
    r"""The Autumn invoice line item ID. Stable across reads, and can be used to reference this line in later calls."""
    description: str
    r"""Description of the invoice line item"""
    period_start: Nullable[float]
    r"""Timestamp when the billing period starts"""
    period_end: Nullable[float]
    r"""Timestamp when the billing period ends"""
    plan_id: Nullable[str]
    r"""The plan this line item came from. Null for lines with no Autumn plan behind them."""
    feature_id: Nullable[str]
    r"""The ID of the feature associated with this line item"""
    feature_name: Nullable[str]
    r"""The name of the feature associated with this line item"""
    quantity: Nullable[float]
    r"""Quantity actually charged on this line. Null on fixed-price lines."""
    amount: float
    r"""Amount charged on this line, pre-discount and pre-tax. Negative for credits."""
    entities: List[PayInvoiceEntityTypedDict]
    r"""How this line splits by entity. Empty for customer-level lines. Only populated for invoices finalized after entity attribution shipped."""


class PayInvoiceItem(BaseModel):
    id: str
    r"""The Autumn invoice line item ID. Stable across reads, and can be used to reference this line in later calls."""

    description: str
    r"""Description of the invoice line item"""

    period_start: Nullable[float]
    r"""Timestamp when the billing period starts"""

    period_end: Nullable[float]
    r"""Timestamp when the billing period ends"""

    plan_id: Nullable[str]
    r"""The plan this line item came from. Null for lines with no Autumn plan behind them."""

    feature_id: Nullable[str]
    r"""The ID of the feature associated with this line item"""

    feature_name: Nullable[str]
    r"""The name of the feature associated with this line item"""

    quantity: Nullable[float]
    r"""Quantity actually charged on this line. Null on fixed-price lines."""

    amount: float
    r"""Amount charged on this line, pre-discount and pre-tax. Negative for credits."""

    entities: List[PayInvoiceEntity]
    r"""How this line splits by entity. Empty for customer-level lines. Only populated for invoices finalized after entity attribution shipped."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class PayInvoiceInvoiceTypedDict(TypedDict):
    plan_ids: List[str]
    r"""Array of plan IDs included in this invoice"""
    stripe_id: str
    r"""The Stripe invoice ID"""
    status: str
    r"""The status of the invoice"""
    total: float
    r"""The total amount of the invoice"""
    currency: str
    r"""The currency code for the invoice"""
    created_at: float
    r"""Timestamp when the invoice was created"""
    id: str
    r"""The Autumn invoice ID"""
    customer_id: Nullable[str]
    r"""The ID of the customer this invoice belongs to. Null for customers created without an ID."""
    entity_id: Nullable[str]
    r"""The ID of the entity this invoice belongs to, if entity-scoped"""
    amount_paid: Nullable[float]
    r"""The amount paid on the invoice. Null on invoices recorded before amounts paid were tracked."""
    refunded_amount: float
    r"""The total amount refunded on the invoice"""
    processor_type: NotRequired[PayInvoiceProcessorType]
    r"""The billing processor that owns this invoice."""
    hosted_invoice_url: NotRequired[Nullable[str]]
    r"""URL to the Stripe-hosted invoice page"""
    items: NotRequired[List[PayInvoiceItemTypedDict]]
    r"""Line items on the invoice, one per line as shown in Stripe. Capped at 100. Empty for invoices recorded before line item storage."""


class PayInvoiceInvoice(BaseModel):
    plan_ids: List[str]
    r"""Array of plan IDs included in this invoice"""

    stripe_id: str
    r"""The Stripe invoice ID"""

    status: str
    r"""The status of the invoice"""

    total: float
    r"""The total amount of the invoice"""

    currency: str
    r"""The currency code for the invoice"""

    created_at: float
    r"""Timestamp when the invoice was created"""

    id: str
    r"""The Autumn invoice ID"""

    customer_id: Nullable[str]
    r"""The ID of the customer this invoice belongs to. Null for customers created without an ID."""

    entity_id: Nullable[str]
    r"""The ID of the entity this invoice belongs to, if entity-scoped"""

    amount_paid: Nullable[float]
    r"""The amount paid on the invoice. Null on invoices recorded before amounts paid were tracked."""

    refunded_amount: float
    r"""The total amount refunded on the invoice"""

    processor_type: Optional[PayInvoiceProcessorType] = "stripe"
    r"""The billing processor that owns this invoice."""

    hosted_invoice_url: OptionalNullable[str] = UNSET
    r"""URL to the Stripe-hosted invoice page"""

    items: Optional[List[PayInvoiceItem]] = None
    r"""Line items on the invoice, one per line as shown in Stripe. Capped at 100. Empty for invoices recorded before line item storage."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["processor_type", "hosted_invoice_url", "items"])
        nullable_fields = set(
            ["hosted_invoice_url", "customer_id", "entity_id", "amount_paid"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class PayInvoiceResponseTypedDict(TypedDict):
    r"""OK"""

    invoice: PayInvoiceInvoiceTypedDict


class PayInvoiceResponse(BaseModel):
    r"""OK"""

    invoice: PayInvoiceInvoice
