"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from autumn_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
from autumn_sdk.utils import FieldMetadata, HeaderMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SyncWebhooksGlobalsTypedDict(TypedDict):
    x_api_version: NotRequired[str]


class SyncWebhooksGlobals(BaseModel):
    x_api_version: Annotated[
        Optional[str],
        pydantic.Field(alias="x-api-version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = "2.4.0"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["x-api-version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


SyncWebhooksEvent = Literal[
    "customer.products.updated",
    "customer.threshold_reached",
    "balances.usage_alert_triggered",
    "balances.limit_reached",
    "billing.auto_topup_failed",
    "billing.auto_topup_succeeded",
    "billing.updated",
    "invoice.finalized",
    "vercel.resources.deleted",
    "vercel.resources.provisioned",
    "vercel.resources.rotate_secrets",
    "vercel.webhooks.event",
]
r"""An event type the webhook receives."""


class SyncWebhooksWebhookRequestTypedDict(TypedDict):
    id: str
    r"""Your ID for the webhook: letters, digits, `-` and `_`. It can't be changed after creation."""
    url: str
    r"""The https URL Autumn sends events to. Localhost and private-network addresses are rejected; tunnels such as ngrok work."""
    events: NotRequired[List[SyncWebhooksEvent]]
    r"""The events sent to this webhook. Leave it out to send every event. `vercel.*` events can't be mixed with other events."""
    description: NotRequired[str]
    r"""A note for your own reference."""
    disabled: NotRequired[bool]
    r"""When true, no events are sent to the webhook."""


class SyncWebhooksWebhookRequest(BaseModel):
    id: str
    r"""Your ID for the webhook: letters, digits, `-` and `_`. It can't be changed after creation."""

    url: str
    r"""The https URL Autumn sends events to. Localhost and private-network addresses are rejected; tunnels such as ngrok work."""

    events: Optional[List[SyncWebhooksEvent]] = None
    r"""The events sent to this webhook. Leave it out to send every event. `vercel.*` events can't be mixed with other events."""

    description: Optional[str] = None
    r"""A note for your own reference."""

    disabled: Optional[bool] = None
    r"""When true, no events are sent to the webhook."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["events", "description", "disabled"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SyncWebhooksSyncWebhooksParamsTypedDict(TypedDict):
    webhooks: List[SyncWebhooksWebhookRequestTypedDict]
    r"""The webhooks to create or update. Webhooks not listed are left alone unless `skip_deletions` is false."""
    skip_deletions: NotRequired[bool]
    r"""When false, `webhooks` is the environment's complete set: every webhook not listed is deleted, including ones made in the dashboard. Defaults true, which leaves unlisted webhooks alone."""


class SyncWebhooksSyncWebhooksParams(BaseModel):
    webhooks: List[SyncWebhooksWebhookRequest]
    r"""The webhooks to create or update. Webhooks not listed are left alone unless `skip_deletions` is false."""

    skip_deletions: Optional[bool] = True
    r"""When false, `webhooks` is the environment's complete set: every webhook not listed is deleted, including ones made in the dashboard. Defaults true, which leaves unlisted webhooks alone."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["skip_deletions"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SyncWebhooksWebhookResponseTypedDict(TypedDict):
    id: str
    r"""The webhook's ID. Webhooks made in the dashboard show their `ep_…` ID."""
    url: str
    r"""The URL Autumn sends events to."""
    description: Nullable[str]
    r"""A note for your own reference."""
    events: List[str]
    r"""The events sent to this webhook, as `WebhookEventType` names; a type newer than your client is returned as-is. Empty means the webhook receives every event."""
    disabled: bool
    r"""When true, no events are sent to the webhook."""
    created_at: float
    r"""When the webhook was created, ms since epoch."""
    updated_at: float
    r"""When the webhook was last changed, ms since epoch."""


class SyncWebhooksWebhookResponse(BaseModel):
    id: str
    r"""The webhook's ID. Webhooks made in the dashboard show their `ep_…` ID."""

    url: str
    r"""The URL Autumn sends events to."""

    description: Nullable[str]
    r"""A note for your own reference."""

    events: List[str]
    r"""The events sent to this webhook, as `WebhookEventType` names; a type newer than your client is returned as-is. Empty means the webhook receives every event."""

    disabled: bool
    r"""When true, no events are sent to the webhook."""

    created_at: float
    r"""When the webhook was created, ms since epoch."""

    updated_at: float
    r"""When the webhook was last changed, ms since epoch."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class SecretTypedDict(TypedDict):
    id: str
    secret: str
    r"""The webhook's signing secret. Shown once, here: store it before you discard the response."""


class Secret(BaseModel):
    id: str

    secret: str
    r"""The webhook's signing secret. Shown once, here: store it before you discard the response."""


class SyncWebhooksErrorTypedDict(TypedDict):
    id: str
    message: str


class SyncWebhooksError(BaseModel):
    id: str

    message: str


class SyncWebhooksResponseTypedDict(TypedDict):
    r"""OK"""

    webhooks: List[SyncWebhooksWebhookResponseTypedDict]
    r"""The listed webhooks as they stand after the sync, except those in `errors`."""
    secrets: List[SecretTypedDict]
    r"""Signing secrets for the webhooks this sync created, shown once. Existing webhooks keep theirs."""
    errors: List[SyncWebhooksErrorTypedDict]
    r"""Webhooks that couldn't be created, updated or deleted. The others were still applied; the request fails only when none could be."""


class SyncWebhooksResponse(BaseModel):
    r"""OK"""

    webhooks: List[SyncWebhooksWebhookResponse]
    r"""The listed webhooks as they stand after the sync, except those in `errors`."""

    secrets: List[Secret]
    r"""Signing secrets for the webhooks this sync created, shown once. Existing webhooks keep theirs."""

    errors: List[SyncWebhooksError]
    r"""Webhooks that couldn't be created, updated or deleted. The others were still applied; the request fails only when none could be."""
