"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from autumn_sdk.types import BaseModel, UNSET_SENTINEL
from autumn_sdk.utils import FieldMetadata, HeaderMetadata
import pydantic
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateBalanceGlobalsTypedDict(TypedDict):
    x_api_version: NotRequired[str]


class UpdateBalanceGlobals(BaseModel):
    x_api_version: Annotated[
        Optional[str],
        pydantic.Field(alias="x-api-version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = "2.1"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["x-api-version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


UpdateBalanceInterval = Literal[
    "one_off",
    "minute",
    "hour",
    "day",
    "week",
    "month",
    "quarter",
    "semi_annual",
    "year",
]
r"""Target a specific balance by its reset interval. Use when the customer has multiple balances for the same feature with different reset intervals."""


class UpdateBalanceParamsTypedDict(TypedDict):
    customer_id: str
    r"""The ID of the customer."""
    feature_id: str
    r"""The ID of the feature."""
    entity_id: NotRequired[str]
    r"""The ID of the entity for entity-scoped balances (e.g., per-seat limits)."""
    remaining: NotRequired[float]
    r"""Set the remaining balance to this exact value. Cannot be combined with add_to_balance."""
    add_to_balance: NotRequired[float]
    r"""Add this amount to the current balance. Use negative values to subtract. Cannot be combined with current_balance."""
    usage: NotRequired[float]
    r"""The usage amount to update. Cannot be combined with remaining or add_to_balance."""
    interval: NotRequired[UpdateBalanceInterval]
    r"""Target a specific balance by its reset interval. Use when the customer has multiple balances for the same feature with different reset intervals."""


class UpdateBalanceParams(BaseModel):
    customer_id: str
    r"""The ID of the customer."""

    feature_id: str
    r"""The ID of the feature."""

    entity_id: Optional[str] = None
    r"""The ID of the entity for entity-scoped balances (e.g., per-seat limits)."""

    remaining: Optional[float] = None
    r"""Set the remaining balance to this exact value. Cannot be combined with add_to_balance."""

    add_to_balance: Optional[float] = None
    r"""Add this amount to the current balance. Use negative values to subtract. Cannot be combined with current_balance."""

    usage: Optional[float] = None
    r"""The usage amount to update. Cannot be combined with remaining or add_to_balance."""

    interval: Optional[UpdateBalanceInterval] = None
    r"""Target a specific balance by its reset interval. Use when the customer has multiple balances for the same feature with different reset intervals."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["entity_id", "remaining", "add_to_balance", "usage", "interval"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateBalanceResponseTypedDict(TypedDict):
    r"""OK"""

    success: bool


class UpdateBalanceResponse(BaseModel):
    r"""OK"""

    success: bool
