"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from autumn_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from autumn_sdk.utils import FieldMetadata, HeaderMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateRewardGlobalsTypedDict(TypedDict):
    x_api_version: NotRequired[str]


class UpdateRewardGlobals(BaseModel):
    x_api_version: Annotated[
        Optional[str],
        pydantic.Field(alias="x-api-version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = "2.3.0"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["x-api-version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateRewardCouponPromoCodeRequestTypedDict(TypedDict):
    code: str
    global_max_redemption: NotRequired[Nullable[int]]
    first_time_transaction: NotRequired[Nullable[bool]]


class UpdateRewardCouponPromoCodeRequest(BaseModel):
    code: str

    global_max_redemption: OptionalNullable[int] = UNSET

    first_time_transaction: OptionalNullable[bool] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["global_max_redemption", "first_time_transaction"])
        nullable_fields = set(["global_max_redemption", "first_time_transaction"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UpdateRewardCouponRequestTypedDict(TypedDict):
    name: NotRequired[str]
    plan_ids: NotRequired[Nullable[List[str]]]
    r"""Plan IDs must be unique. Null applies the coupon to all plans."""
    promo_codes: NotRequired[List[UpdateRewardCouponPromoCodeRequestTypedDict]]
    r"""Replaces the existing promo codes when provided."""


class UpdateRewardCouponRequest(BaseModel):
    name: Optional[str] = None

    plan_ids: OptionalNullable[List[str]] = UNSET
    r"""Plan IDs must be unique. Null applies the coupon to all plans."""

    promo_codes: Optional[List[UpdateRewardCouponPromoCodeRequest]] = None
    r"""Replaces the existing promo codes when provided."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "plan_ids", "promo_codes"])
        nullable_fields = set(["plan_ids"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


UpdateRewardTypeRequestBody = Literal[
    "day",
    "week",
    "month",
    "year",
]
r"""The unit of time the grant lasts."""


class UpdateRewardExpiryRequestTypedDict(TypedDict):
    type: UpdateRewardTypeRequestBody
    r"""The unit of time the grant lasts."""
    length: int
    r"""The positive integer count of periods before the grant expires."""


class UpdateRewardExpiryRequest(BaseModel):
    type: UpdateRewardTypeRequestBody
    r"""The unit of time the grant lasts."""

    length: int
    r"""The positive integer count of periods before the grant expires."""


class UpdateRewardGrantRequestTypedDict(TypedDict):
    feature_id: str
    included: Nullable[float]
    expiry: Nullable[UpdateRewardExpiryRequestTypedDict]
    r"""How long the granted amount lasts before expiring, or null for a permanent grant."""


class UpdateRewardGrantRequest(BaseModel):
    feature_id: str

    included: Nullable[float]

    expiry: Nullable[UpdateRewardExpiryRequest]
    r"""How long the granted amount lasts before expiring, or null for a permanent grant."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class UpdateRewardFeatureGrantPromoCodeRequestTypedDict(TypedDict):
    code: str
    max_uses: Nullable[int]


class UpdateRewardFeatureGrantPromoCodeRequest(BaseModel):
    code: str

    max_uses: Nullable[int]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class UpdateRewardFeatureGrantRequestTypedDict(TypedDict):
    name: NotRequired[str]
    grants: NotRequired[List[UpdateRewardGrantRequestTypedDict]]
    r"""Replaces the existing grants when provided."""
    promo_codes: NotRequired[List[UpdateRewardFeatureGrantPromoCodeRequestTypedDict]]
    r"""Replaces the existing promo codes when provided."""


class UpdateRewardFeatureGrantRequest(BaseModel):
    name: Optional[str] = None

    grants: Optional[List[UpdateRewardGrantRequest]] = None
    r"""Replaces the existing grants when provided."""

    promo_codes: Optional[List[UpdateRewardFeatureGrantPromoCodeRequest]] = None
    r"""Replaces the existing promo codes when provided."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "grants", "promo_codes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateRewardParamsTypedDict(TypedDict):
    id: str
    r"""The ID of the coupon or feature grant to update."""
    coupon: NotRequired[UpdateRewardCouponRequestTypedDict]
    feature_grant: NotRequired[UpdateRewardFeatureGrantRequestTypedDict]


class UpdateRewardParams(BaseModel):
    id: str
    r"""The ID of the coupon or feature grant to update."""

    coupon: Optional[UpdateRewardCouponRequest] = None

    feature_grant: Optional[UpdateRewardFeatureGrantRequest] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["coupon", "feature_grant"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


UpdateRewardCouponType = Union[
    Literal[
        "percentage_discount",
        "fixed_discount",
        "invoice_credits",
    ],
    UnrecognizedStr,
]
r"""The type of discount: percentage_discount, fixed_discount, or invoice_credits."""


UpdateRewardDurationType = Union[
    Literal[
        "one_off",
        "months",
        "forever",
    ],
    UnrecognizedStr,
]
r"""The unit of time the duration is measured in."""


class UpdateRewardDurationTypedDict(TypedDict):
    r"""How long the coupon applies once redeemed."""

    type: UpdateRewardDurationType
    r"""The unit of time the duration is measured in."""
    length: Nullable[float]
    r"""The number of `type` periods the duration lasts, or null when the type has no length (e.g. one_off, forever)."""


class UpdateRewardDuration(BaseModel):
    r"""How long the coupon applies once redeemed."""

    type: UpdateRewardDurationType
    r"""The unit of time the duration is measured in."""

    length: Nullable[float]
    r"""The number of `type` periods the duration lasts, or null when the type has no length (e.g. one_off, forever)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class UpdateRewardCouponPromoCodeResponseTypedDict(TypedDict):
    code: str
    r"""The promo code customers enter to redeem the coupon."""
    global_max_redemption: NotRequired[Nullable[float]]
    r"""Maximum number of times this promo code can be redeemed across all customers, or null for unlimited."""
    first_time_transaction: NotRequired[Nullable[bool]]
    r"""Whether this promo code can only be applied to a customer's first transaction."""


class UpdateRewardCouponPromoCodeResponse(BaseModel):
    code: str
    r"""The promo code customers enter to redeem the coupon."""

    global_max_redemption: OptionalNullable[float] = UNSET
    r"""Maximum number of times this promo code can be redeemed across all customers, or null for unlimited."""

    first_time_transaction: OptionalNullable[bool] = UNSET
    r"""Whether this promo code can only be applied to a customer's first transaction."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["global_max_redemption", "first_time_transaction"])
        nullable_fields = set(["global_max_redemption", "first_time_transaction"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UpdateRewardCouponTypedDict(TypedDict):
    id: str
    r"""The unique identifier for the coupon."""
    type: UpdateRewardCouponType
    r"""The type of discount: percentage_discount, fixed_discount, or invoice_credits."""
    value: float
    r"""The discount value. A percentage for percentage_discount, or an amount for fixed_discount / invoice_credits."""
    duration: UpdateRewardDurationTypedDict
    r"""How long the coupon applies once redeemed."""
    plan_ids: Nullable[List[str]]
    r"""The plan IDs the coupon applies to, or null when it applies to all plans."""
    promo_codes: List[UpdateRewardCouponPromoCodeResponseTypedDict]
    created_at: float
    r"""The Unix timestamp (in milliseconds) when the coupon was created."""
    name: NotRequired[Nullable[str]]
    r"""A human-readable name for the coupon."""


class UpdateRewardCoupon(BaseModel):
    id: str
    r"""The unique identifier for the coupon."""

    type: UpdateRewardCouponType
    r"""The type of discount: percentage_discount, fixed_discount, or invoice_credits."""

    value: float
    r"""The discount value. A percentage for percentage_discount, or an amount for fixed_discount / invoice_credits."""

    duration: UpdateRewardDuration
    r"""How long the coupon applies once redeemed."""

    plan_ids: Nullable[List[str]]
    r"""The plan IDs the coupon applies to, or null when it applies to all plans."""

    promo_codes: List[UpdateRewardCouponPromoCodeResponse]

    created_at: float
    r"""The Unix timestamp (in milliseconds) when the coupon was created."""

    name: OptionalNullable[str] = UNSET
    r"""A human-readable name for the coupon."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name"])
        nullable_fields = set(["name", "plan_ids"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


UpdateRewardExpiryTypeResponse = Union[
    Literal[
        "day",
        "week",
        "month",
        "year",
    ],
    UnrecognizedStr,
]
r"""The unit of time the grant lasts."""


class UpdateRewardExpiryResponseTypedDict(TypedDict):
    type: UpdateRewardExpiryTypeResponse
    r"""The unit of time the grant lasts."""
    length: int
    r"""The positive integer count of periods before the grant expires."""


class UpdateRewardExpiryResponse(BaseModel):
    type: UpdateRewardExpiryTypeResponse
    r"""The unit of time the grant lasts."""

    length: int
    r"""The positive integer count of periods before the grant expires."""


class UpdateRewardGrantResponseTypedDict(TypedDict):
    feature_id: str
    r"""The feature ID this grant applies to."""
    included: Nullable[float]
    r"""The amount of the feature granted, or null for boolean features."""
    expiry: Nullable[UpdateRewardExpiryResponseTypedDict]
    r"""How long the granted amount lasts before expiring, or null for a permanent grant."""


class UpdateRewardGrantResponse(BaseModel):
    feature_id: str
    r"""The feature ID this grant applies to."""

    included: Nullable[float]
    r"""The amount of the feature granted, or null for boolean features."""

    expiry: Nullable[UpdateRewardExpiryResponse]
    r"""How long the granted amount lasts before expiring, or null for a permanent grant."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class UpdateRewardFeatureGrantPromoCodeResponseTypedDict(TypedDict):
    code: str
    r"""The promo code customers enter to redeem the feature grant."""
    max_uses: Nullable[float]
    r"""Maximum number of times this promo code can be redeemed, or null for unlimited."""


class UpdateRewardFeatureGrantPromoCodeResponse(BaseModel):
    code: str
    r"""The promo code customers enter to redeem the feature grant."""

    max_uses: Nullable[float]
    r"""Maximum number of times this promo code can be redeemed, or null for unlimited."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class UpdateRewardFeatureGrantTypedDict(TypedDict):
    id: str
    r"""The unique identifier for the feature grant."""
    grants: List[UpdateRewardGrantResponseTypedDict]
    promo_codes: List[UpdateRewardFeatureGrantPromoCodeResponseTypedDict]
    created_at: float
    r"""The Unix timestamp (in milliseconds) when the feature grant was created."""
    name: NotRequired[Nullable[str]]
    r"""A human-readable name for the feature grant."""


class UpdateRewardFeatureGrant(BaseModel):
    id: str
    r"""The unique identifier for the feature grant."""

    grants: List[UpdateRewardGrantResponse]

    promo_codes: List[UpdateRewardFeatureGrantPromoCodeResponse]

    created_at: float
    r"""The Unix timestamp (in milliseconds) when the feature grant was created."""

    name: OptionalNullable[str] = UNSET
    r"""A human-readable name for the feature grant."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name"])
        nullable_fields = set(["name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UpdateRewardResponseTypedDict(TypedDict):
    r"""OK"""

    coupon: NotRequired[UpdateRewardCouponTypedDict]
    feature_grant: NotRequired[UpdateRewardFeatureGrantTypedDict]


class UpdateRewardResponse(BaseModel):
    r"""OK"""

    coupon: Optional[UpdateRewardCoupon] = None

    feature_grant: Optional[UpdateRewardFeatureGrant] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["coupon", "feature_grant"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
