import { readFileSync } from "node:fs";
import { join } from "node:path";
import { LABEL_OVERLAY } from "../overlay/overlay";

const SHARED_LABELS = join(
	import.meta.dir,
	"../../../../shared/utils/planV1Utils/diff/planPreviousAttributeLabels.ts",
);
const LABEL_LINE = /^\s*([a-z_]+):\s*"([^"]*)",?\s*$/gm;

const GENERATED_HEADER = `// Generated by @autumn/atmn-generator from shared/utils/planV1Utils/diff/planPreviousAttributeLabels.ts.
// Do not edit — run \`bun generate\` in packages/atmn-generator instead.
`;

/** The shared label map, read from its source so this package needs no
 * dependency on shared, with the CLI's own wording layered on top. */
export const emitLabelsModule = (): string => {
	const source = readFileSync(SHARED_LABELS, "utf8");
	const shared = Object.fromEntries(
		[...source.matchAll(LABEL_LINE)].map((match) => [match[1], match[2]]),
	);
	if (Object.keys(shared).length === 0)
		throw new Error(`No labels found in ${SHARED_LABELS}`);
	const labels = { ...shared, ...LABEL_OVERLAY };
	return `${GENERATED_HEADER}
/** Wire-named (snake_case) keys of previous_attributes → what the terminal prints. */
export const PREVIOUS_ATTRIBUTE_LABELS: Readonly<Record<string, string>> = ${JSON.stringify(labels, null, "\t")};
`;
};
